# 1 Assignment 3

1. Generate a function named **beta_OLS**. This function must return the estimated beta using OLS. The inputs of this function should be `X`, `y`, and `intercept`. `X` (covariables) must be a **pd.DataFrame** and `y` (endog) must be a **pd.Series** and `intercept` can be `True` or `False`, by default `True`. When `intercept` is `False`, the estimated beta does not include **intercept**. Also, you must specify the type of your function's parameters and output and It must raise an error if the inputs do not meet the requirements. The function's output must be a **pd.DataFrame** (`n`, 1) where `n` is the total number of regressors ( it includes the **Intercept** when `intercept` is `True`). The column should be named as **Coef.** and the row index should be named as the original name of the columns in `X` input. Your results should look like `beta_OLS_output`. Apply your function to find $\widehat{\boldsymbol{\beta}}^{(OLS)}$ of the equation below. Use `data`.  **Hint: Use NumPy to generate the OLS beta and check [this link](https://pandas.pydata.org/docs/reference/api/pandas.DataFrame.set_index.html) to change the index name of a pd.Dataframe, [link](https://notebooks.githubusercontent.com/view/ipynb?browser=chrome&color_mode=auto&commit=69c80e1f2c1c268f0480a32932262201785a576c&device=unknown_device&enc_url=68747470733a2f2f7261772e67697468756275736572636f6e74656e742e636f6d2f616c6578616e6465727175697370652f4469706c6f6d61646f5f505543502f363963383065316632633163323638663034383061333239333232363232303137383561353736632f4c6563747572655f352f4c6563747572655f352e6970796e62&logged_in=true&nwo=alexanderquispe%2FDiplomado_PUCP&path=Lecture_5%2FLecture_5.ipynb&platform=windows&repository_id=427747212&repository_type=Repository&version=96##5.1.7.).**

$$
\widehat{\boldsymbol{\beta}}^{(OLS)} = \left( \mathbf{X}^\top \mathbf{X}\right)^{-1} \mathbf{X}^\top \mathbf{Y}
$$

$$
\begin{aligned} 
lnCT &= \beta_{0}+\beta_{q}lnq+ \beta_{qq}(lnq)^2+\beta_{q1}lnqlnp_1+\beta_{q2}lnqlnp_2+ \beta_{q3}lnqlnp_{3} +\beta_{1}lnp_1+\beta_{2}lnp_2+ \beta_{3}lnp_3 \\
& + \beta_{11}(lnp_{1})^2+ \beta_{22}(lnp_{2})^2+ \beta_{33}(lnp_{3})^2 + \beta_{12}lnp_{1}lnp_{2}+ \beta_{13}lnp_{1}lnp_{3}+\beta_{23}lnp_{2}lnp_{3} 
\end{aligned}
$$

In [240]:
import pandas as pd
import numpy as np
import pickle
import scipy.stats as stats

In [241]:
greene = pd.read_csv(r"../../_data/christensen_greene_f4.csv")
ct = greene.COST.values
q = greene.Q.values
p1 = greene.PL.values
p2 = greene.PF.values
p3 = greene.PK.values

In [242]:
greene

,id,YEAR,COST,Q,PL,SL,PK,SK,PF,SF
0,1,1970,0.2130,8.0,6869.47,0.3291,64.945,0.4197,18.000,0.2512
1,4,1970,3.0427,869.0,8372.96,0.1030,68.227,0.2913,21.067,0.6057
2,5,1970,9.4059,1412.0,7960.90,0.0891,40.692,0.1567,41.530,0.7542
3,14,1970,0.7606,65.0,8971.89,0.2802,41.243,0.1282,28.539,0.5916
4,15,1970,2.2587,295.0,8218.40,0.1772,71.940,0.1623,39.200,0.6606
...,...,...,...,...,...,...,...,...,...,...
153,214,1970,6.8293,946.6,10642.16,0.0883,43.600,0.1914,51.463,0.7203
154,215,1970,3.7605,377.0,7432.24,0.2117,74.120,0.2274,33.436,0.5609
155,216,1970,3.9822,391.0,5826.04,0.1926,78.288,0.0924,44.633,0.7151
156,217,1970,30.1880,5317.0,9586.63,0.0845,78.008,0.2009,41.840,0.7147
157,218,1970,67.8562,15220.0,6986.09,0.1451,74.025,0.2596,25.662,0.5945

In [243]:
file_to_open = open( r'../../_data/data_greene.pkl' , "rb" )
data = pickle.load( file_to_open )

In [244]:
y_0 = pd.DataFrame ([np.log(ct)]) # lnCT
y_1 = y_0.T.iloc[:,0]
y=y_1.rename("np.log(COST)", inplace =True)
y

0     -1.546463
1      1.112745
2      2.241337
3     -0.273648
4      0.814789
         ...
153    1.921222
154    1.324552
155    1.381834
156    3.407444
157    4.217391
Name: np.log(COST), Length: 158, dtype: float64

In [245]:

ln_q = np.log(q) 
ln_q_2 = np.multiply(ln_q,ln_q)

ln_p1 = np.log(p1)
ln_p2 = np.log(p2) 
ln_p3 = np.log(p3) 

ln_q_ln_p1 = np.multiply(ln_q,ln_p1)
ln_q_ln_p2 = np.multiply(ln_q,ln_p2)
ln_q_ln_p3 = np.multiply(ln_q,ln_p3)


ln_p1_2 = np.multiply(ln_p1,ln_p1) 
ln_p2_2 = np.multiply(ln_p2,ln_p2) 
ln_p3_2 = np.multiply(ln_p3,ln_p3) 

ln_p1_ln_p2 = np.multiply (ln_p1,ln_p2)
ln_p1_ln_p3 = np.multiply (ln_p1,ln_p3)
ln_p2_ln_p3 = np.multiply (ln_p2,ln_p3)

x = pd.DataFrame([ln_q, ln_q_2, ln_q_ln_p1, ln_q_ln_p2, ln_q_ln_p3, ln_p1, ln_p2, ln_p3, ln_p1_2, ln_p2_2, ln_p3_2, ln_p1_ln_p2, ln_p1_ln_p3, ln_p2_ln_p3]).T

x.rename(columns = {0:'lnq', 1:'lnq2', 2:'lnqlnp1', 3:'lnqlnp2', 4:'lnqlnp3',
                    5:'lnp1', 6:'lnp2', 7:'lnp3',
                    8:'lnp1_2', 9:'lnp2_2', 10:'lnp3_2',
                    11:'lnp1lnp2', 12:'lnp1lnp3', 13:'lnp2lnp3'}, inplace = True)
x

,lnq,lnq2,lnqlnp1,lnqlnp2,lnqlnp3,lnp1,lnp2,lnp3,lnp1_2,lnp2_2,lnp3_2,lnp1lnp2,lnp1lnp3,lnp2lnp3
0,2.079442,4.324077,18.371538,6.010359,8.678634,8.834842,2.890372,4.173541,78.054437,8.354249,17.418442,25.535978,36.872574,12.063084
1,6.767343,45.796933,61.127805,20.624885,28.577410,9.032763,3.047708,4.222840,81.590803,9.288523,17.832381,27.529222,38.143915,12.869984
2,7.252762,52.602563,65.146469,27.026810,26.878966,8.982297,3.726416,3.706032,80.681665,13.886177,13.734670,33.471777,33.288677,13.810215
3,4.174387,17.425509,37.994654,13.989505,15.526556,9.101852,3.351272,3.719481,82.843703,11.231021,13.834542,30.502777,33.854168,12.464992
4,5.686975,32.341689,51.263140,20.863674,24.316554,9.014131,3.668677,4.275832,81.254554,13.459189,18.282743,33.069932,38.542913,15.686647
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
153,6.852877,46.961918,63.543838,27.006249,25.870001,9.272579,3.940863,3.775057,85.980717,15.530402,14.251056,36.541963,35.004515,14.876983
154,5.932245,35.191533,52.877557,20.820004,25.542382,8.913583,3.509633,4.305685,79.451954,12.317525,18.538927,31.283405,38.379082,15.111376
155,5.968708,35.625470,51.749248,22.671977,26.025919,8.670093,3.798473,4.360394,75.170509,14.428401,19.013039,32.933118,37.805024,16.562842
156,8.578665,73.593485,78.650266,32.031471,37.375623,9.168125,3.733853,4.356811,84.054510,13.941657,18.981805,34.232428,39.943790,16.267692
157,9.630366,92.743942,85.244879,31.250645,41.452974,8.851676,3.245011,4.304403,78.352173,10.530098,18.527884,28.723790,38.101181,13.967836

In [246]:
file_to_open = open( r'../../_data/beta_OLS_output.pkl' , "rb" )
beta_OLS_output = pickle.load( file_to_open )
beta_OLS_output

                  Coef.
Intercept    -76.259259
lnq           -1.080425
(lnq)^2        0.026489
(lnq)(lnp1)    0.131041
(lnq)(lnp2)    0.058652
(lnq)(lnp3)    0.040144
lnp1          14.718292
lnp2          -0.894733
lnp3           6.380797
(lnp1)^2      -1.538527
(lnp2)^2      -0.073506
(lnp3)^2      -0.327414
(lnp1)(lnp2)   0.324566
(lnp1)(lnp3)  -1.144101
(lnp2)(lnp3)  -0.048049

In [247]:
beta_OLS_output_test

               Coef.
Intercept -76.259261
lnq        -1.080425
lnq2        0.026489
lnqlnp1     0.131041
lnqlnp2     0.058652
lnqlnp3     0.040144
lnp1       14.718293
lnp2       -0.894733
lnp3        6.380797
lnp1_2     -0.769264
lnp2_2     -0.036753
lnp3_2     -0.163707
lnp1lnp2    0.162283
lnp1lnp3   -0.572050
lnp2lnp3   -0.024025

In [248]:
def beta_OLS( X : pd.DataFrame, y : pd.Series, intercept = True ):
        
    if not isinstance( X, pd.DataFrame ):
        raise TypeError( 'X is not a pd.DataFrame' )
    
    if not isinstance( y, pd.Series ):
        raise TypeError( 'y is not a pd.Series' )
    
    if not isinstance( intercept, bool ):
        raise TypeError( 'intercept is not a bool' )
        
    if len( X ) != len( y ):
        raise ValueError( 'Number of rows in x and y differ' )
    
    X_mat = X.copy()
    y_vec = y.copy()
    
    if intercept == True:
        const = np.ones( len( X_mat ) )
        X_mat.insert(0, "Intercept", const)
    
    var_names = list( X_mat.columns )
    X_mat = X_mat.to_numpy()
    y_vec = y_vec.to_numpy()
    
    xtx_inv = np.linalg.inv( np.dot( np.transpose( X_mat ), X_mat ) )
    coefs = np.dot( xtx_inv, np.dot( np.transpose( X_mat ), y_vec ) )
    coefs = pd.DataFrame( coefs, index = var_names, columns = [ 'Coef.' ] )
    
    return coefs

In [249]:
coef=beta_OLS (x,y )
coef

               Coef.
Intercept -76.259258
lnq        -1.080425
lnq2        0.026489
lnqlnp1     0.131041
lnqlnp2     0.058652
lnqlnp3     0.040144
lnp1       14.718292
lnp2       -0.894733
lnp3        6.380797
lnp1_2     -0.769264
lnp2_2     -0.036753
lnp3_2     -0.163707
lnp1lnp2    0.162283
lnp1lnp3   -0.572050
lnp2lnp3   -0.024025

2. Generate a new function named **var_OLS**. This function must return the estimated variance for OLS. The inputs of this function should be `X`, `y`, and `intercept`. `X` (covariables) must be a **pd.DataFrame** and `y` (endog) must be a **pd.Series** and `intercept` can be `True` or `False`, by default `True`. When `intercept` is `False`, the estimated variance does not include **intercept** in the `X` regressor. Also, you must specify the type of your function's parameters and output and It must raise an error if the inputs do not meet the requirements. The output of the function should look like `var_OLS_output` where the columns and the index use the name of `X` columns.  Apply your function to find $\mathbb{V}{\rm ar} (\widehat{\boldsymbol{\beta}}^{(OLS)})$ of the equation below. Use greene data.  **Hint: Use numpy, `def` function, and `columns` method, [link](https://notebooks.githubusercontent.com/view/ipynb?browser=chrome&color_mode=auto&commit=69c80e1f2c1c268f0480a32932262201785a576c&device=unknown_device&enc_url=68747470733a2f2f7261772e67697468756275736572636f6e74656e742e636f6d2f616c6578616e6465727175697370652f4469706c6f6d61646f5f505543502f363963383065316632633163323638663034383061333239333232363232303137383561353736632f4c6563747572655f352f4c6563747572655f352e6970796e62&logged_in=true&nwo=alexanderquispe%2FDiplomado_PUCP&path=Lecture_5%2FLecture_5.ipynb&platform=windows&repository_id=427747212&repository_type=Repository&version=96##5.1.7.).**

$$
\widehat{\boldsymbol{\varepsilon}} = \mathbf{Y} - \mathbf{X} \widehat{\boldsymbol{\beta}}_{OLS}
$$

$$
\widehat{\sigma}^2_{OLS} = \dfrac{\widehat{\boldsymbol{\varepsilon}}^\top \widehat{\boldsymbol{\varepsilon}}}{N - (k+1)}
$$


$$
\begin{aligned}
\mathbb{V}{\rm ar} (\widehat{\boldsymbol{\beta}}^{(OLS)}) = 
\sigma^2 \left( \mathbf{X}^\top  \mathbf{X}\right)^{-1}
\end{aligned}
$$

$$
\begin{aligned} 
lnCT &= \beta_{0}+\beta_{q}lnq+ \beta_{qq}(lnq)^2+\beta_{q1}lnqlnp_1+\beta_{q2}lnqlnp_2+ \beta_{q3}lnqlnp_{3} +\beta_{1}lnp_1+\beta_{2}lnp_2+ \beta_{3}lnp_3 \\
& + \beta_{11}(lnp_{1})^2+ \beta_{22}(lnp_{2})^2+ \beta_{33}(lnp_{3})^2 + \beta_{12}lnp_{1}lnp_{2}+ \beta_{13}lnp_{1}lnp_{3}+\beta_{23}lnp_{2}lnp_{3} 
\end{aligned}
$$

In [250]:
file_to_open = open( r'../../_data/var_OLS_output.pkl' , "rb" )
var_OLS_output = pickle.load( file_to_open )

In [251]:
var_OLS_output = result.fit().cov_params()
var_OLS_output

,Intercept,lnq,lnq2,lnqlnp1,lnqlnp2,lnqlnp3,lnp1,lnp2,lnp3,lnp1_2,lnp2_2,lnp3_2,lnp1lnp2,lnp1lnp3,lnp2lnp3
Intercept,1465.361176,0.192537,-0.011698,-0.026677,0.015949,0.039538,-262.932577,-8.392679,-128.192050,11.880857,-0.266944,3.540639,0.990253,10.902441,0.197435
lnq,0.192537,0.141034,0.000308,-0.013459,0.000161,-0.006089,-0.186223,0.148320,-0.090714,0.015321,0.000381,-0.000898,-0.015046,0.017546,-0.003570
lnq2,-0.011698,0.000308,0.000006,-0.000036,-0.000005,-0.000011,0.001491,0.001052,0.000862,-0.000043,0.000013,-0.000060,-0.000099,-0.000014,-0.000048
lnqlnp1,-0.026677,-0.013459,-0.000036,0.001466,-0.000168,0.000348,0.021561,-0.015127,0.005430,-0.001961,0.000019,0.000285,0.001850,-0.001141,-0.000085
lnqlnp2,0.015949,0.000161,-0.000005,-0.000168,0.000653,-0.000189,-0.008293,0.003306,0.008035,0.000587,-0.000170,-0.000103,-0.000170,-0.000144,-0.001375
lnqlnp3,0.039538,-0.006089,-0.000011,0.000348,-0.000189,0.000888,-0.000337,-0.008853,0.000268,0.000211,-0.000033,-0.000067,0.000102,-0.001537,0.002212
lnp1,-262.932577,-0.186223,0.001491,0.021561,-0.008293,-0.000337,50.194723,-1.253531,19.099543,-2.388986,0.070493,-0.420154,0.038416,-1.788158,0.132157
lnp2,-8.392679,0.148320,0.001052,-0.015127,0.003306,-0.008853,-1.253531,8.078742,-0.214871,0.161643,-0.058647,-0.033147,-0.685050,0.199482,-0.367388
lnp3,-128.192050,-0.090714,0.000862,0.005430,0.008035,0.000268,19.099543,-0.214871,20.513715,-0.705214,0.023665,-0.763050,0.036229,-1.555553,-0.072591
lnp1_2,11.880857,0.015321,-0.000043,-0.001961,0.000587,0.000211,-2.388986,0.161643,-0.705214,0.119855,-0.003079,0.011353,-0.013413,0.070381,-0.006656
lnp2_2,-0.266944,0.000381,0.000013,0.000019,-0.000170,-0.000033,0.070493,-0.058647,0.023665,-0.003079,0.008285,-0.002049,-0.001552,-0.002485,0.004467
lnp3_2,3.540639,-0.000898,-0.000060,0.000285,-0.000103,-0.000067,-0.420154,-0.033147,-0.763050,0.011353,-0.002049,0.048556,0.008386,0.043314,-0.006653
lnp1lnp2,0.990253,-0.015046,-0.000099,0.001850,-0.000170,0.000102,0.038416,-0.685050,0.036229,-0.013413,-0.001552,0.008386,0.072939,-0.015413,0.009949
lnp1lnp3,10.902441,0.017546,-0.000014,-0.001141,-0.000144,-0.001537,-1.788158,0.199482,-1.555553,0.070381,-0.002485,0.043314,-0.015413,0.138302,-0.010534
lnp2lnp3,0.197435,-0.003570,-0.000048,-0.000085,-0.001375,0.002212,0.132157,-0.367388,-0.072591,-0.006656,0.004467,-0.006653,0.009949,-0.010534,0.060678

In [252]:
def var_OLS( X : pd.DataFrame, y : pd.Series, intercept = True ):
        
    if not isinstance( X, pd.DataFrame ):
        raise TypeError( 'X is not a pd.DataFrame' )
    
    if not isinstance( y, pd.Series ):
        raise TypeError( 'y is not a pd.Series' )
    
    if not isinstance( intercept, bool ):
        raise TypeError( 'intercept is not a bool' )
        
    if len( X ) != len( y ):
        raise ValueError( 'X and y do not have the same number of rows' )
    
    X_mat = X.copy()
    y_vec = y.copy()
    
    if intercept == True:
        const = np.ones( len( X_mat ) )
        X_mat.insert(0, "Intercept", const)
    
    var_names = list( X_mat.columns )
    X_mat = X_mat.to_numpy()
    y_vec = y_vec.to_numpy()
    
    xtx_inv = np.linalg.inv( np.dot( np.transpose( X_mat ), X_mat ) )
    coefs = np.dot( xtx_inv, np.dot( np.transpose( X_mat ), y_vec ) )
    
    errores=np.add(y_vec,-np.dot( X_mat , coefs ))
    var_error=np.dot(np.transpose(errores),errores)/(len(errores)-14-1)

    var_coef=var_error*xtx_inv
    
    var_coef = pd.DataFrame( var_coef, index = var_names, columns=var_names)

    
    return var_coef

In [253]:
var_OLS(X,y ,True)

,Intercept,lnq,(lnq)^2,(lnq)(lnp1),(lnq)(lnp2),(lnq)(lnp3),lnp1,lnp2,lnp3,(lnp1)^2,(lnp2)^2,(lnp3)^2,(lnp1)(lnp2),(lnp1)(lnp3),(lnp2)(lnp3)
Intercept,1465.361103,0.192537,-0.011698,-0.026677,0.015949,0.039538,-262.932564,-8.392679,-128.192044,23.761712,-0.533889,7.081277,1.980507,21.804880,0.394870
lnq,0.192537,0.141034,0.000308,-0.013459,0.000161,-0.006089,-0.186223,0.148320,-0.090714,0.030641,0.000762,-0.001796,-0.030093,0.035093,-0.007141
(lnq)^2,-0.011698,0.000308,0.000006,-0.000036,-0.000005,-0.000011,0.001491,0.001052,0.000862,-0.000086,0.000026,-0.000120,-0.000198,-0.000028,-0.000097
(lnq)(lnp1),-0.026677,-0.013459,-0.000036,0.001466,-0.000168,0.000348,0.021561,-0.015127,0.005430,-0.003923,0.000038,0.000571,0.003700,-0.002282,-0.000170
(lnq)(lnp2),0.015949,0.000161,-0.000005,-0.000168,0.000653,-0.000189,-0.008293,0.003306,0.008035,0.001175,-0.000340,-0.000205,-0.000340,-0.000289,-0.002751
(lnq)(lnp3),0.039538,-0.006089,-0.000011,0.000348,-0.000189,0.000888,-0.000337,-0.008853,0.000268,0.000421,-0.000066,-0.000134,0.000204,-0.003074,0.004424
lnp1,-262.932564,-0.186223,0.001491,0.021561,-0.008293,-0.000337,50.194721,-1.253531,19.099542,-4.777971,0.140987,-0.840307,0.076832,-3.576317,0.264314
lnp2,-8.392679,0.148320,0.001052,-0.015127,0.003306,-0.008853,-1.253531,8.078742,-0.214871,0.323286,-0.117293,-0.066294,-1.370100,0.398963,-0.734776
lnp3,-128.192045,-0.090714,0.000862,0.005430,0.008035,0.000268,19.099542,-0.214871,20.513714,-1.410427,0.047330,-1.526100,0.072458,-3.111107,-0.145182
(lnp1)^2,23.761712,0.030641,-0.000086,-0.003923,0.001175,0.000421,-4.777971,0.323286,-1.410427,0.479422,-0.012318,0.045414,-0.053651,0.281523,-0.026624
(lnp2)^2,-0.533889,0.000762,0.000026,0.000038,-0.000340,-0.000066,0.140987,-0.117293,0.047330,-0.012318,0.033138,-0.008197,-0.006208,-0.009941,0.017867
(lnp3)^2,7.081277,-0.001796,-0.000120,0.000571,-0.000205,-0.000134,-0.840307,-0.066294,-1.526100,0.045414,-0.008197,0.194224,0.033545,0.173257,-0.026611
(lnp1)(lnp2),1.980507,-0.030093,-0.000198,0.003700,-0.000340,0.000204,0.076832,-1.370100,0.072458,-0.053651,-0.006208,0.033545,0.291755,-0.061653,0.039798
(lnp1)(lnp3),21.804880,0.035093,-0.000028,-0.002282,-0.000289,-0.003074,-3.576317,0.398963,-3.111107,0.281523,-0.009941,0.173257,-0.061653,0.553209,-0.042134
(lnp2)(lnp3),0.394870,-0.007141,-0.000097,-0.000170,-0.002751,0.004424,0.264314,-0.734776,-0.145182,-0.026624,0.017867,-0.026611,0.039798,-0.042134,0.242712

3. Generate a new function named as `reg_OLS` that uses your previos functions `beta_OLS` and `var_OLS` to return an ouput similar to `reg_OLS_output`. The inputs of this function should be `X`, `y`, and `intercept`. `X` (covariables) must be a **pd.DataFrame** and `y` (endog) must be a **pd.Series** and `intercept` can be `True` or `False`, by default `True`. When `intercept` is `False`, the output does not include **intercept**. Also, you must specify the type of your function's parameters and output and It must raise an error if the inputs do not meet the requirements. The ouput of this function should look like `reg_OLS_ouput` Apply your function to the equation below. Use greene data.**Hint: Use numpy, `def` function, and `columns` method, [link](https://notebooks.githubusercontent.com/view/ipynb?browser=chrome&color_mode=auto&commit=69c80e1f2c1c268f0480a32932262201785a576c&device=unknown_device&enc_url=68747470733a2f2f7261772e67697468756275736572636f6e74656e742e636f6d2f616c6578616e6465727175697370652f4469706c6f6d61646f5f505543502f363963383065316632633163323638663034383061333239333232363232303137383561353736632f4c6563747572655f352f4c6563747572655f352e6970796e62&logged_in=true&nwo=alexanderquispe%2FDiplomado_PUCP&path=Lecture_5%2FLecture_5.ipynb&platform=windows&repository_id=427747212&repository_type=Repository&version=96##5.1.7.).**

$$
\begin{aligned} 
lnCT &= \beta_{0}+\beta_{q}lnq+ \beta_{qq}(lnq)^2+\beta_{q1}lnqlnp_1+\beta_{q2}lnqlnp_2+ \beta_{q3}lnqlnp_{3} +\beta_{1}lnp_1+\beta_{2}lnp_2+ \beta_{3}lnp_3 \\
& + \beta_{11}(lnp_{1})^2+ \beta_{22}(lnp_{2})^2+ \beta_{33}(lnp_{3})^2 + \beta_{12}lnp_{1}lnp_{2}+ \beta_{13}lnp_{1}lnp_{3}+\beta_{23}lnp_{2}lnp_{3} 
\end{aligned}
$$

$$
\widehat{\boldsymbol{\varepsilon}} = \mathbf{Y} - \mathbf{X} \widehat{\boldsymbol{\beta}}_{RLS}
$$

$$
\widehat{\sigma}^2_{RLS} = \dfrac{\widehat{\boldsymbol{\varepsilon}}^\top \widehat{\boldsymbol{\varepsilon}}}{N - (k+1 - M)}
$$

In [254]:
file_to_open = open( r'../../_data/reg_OLS_output.pkl' , "rb" )
reg_OLS_output = pickle.load( file_to_open )
reg_OLS_output

,Coef.,Std.Err.,t,P>|t|,[0.025,0.975]
Intercept,-76.259259,38.280036,-1.992142,4.825953e-02,-151.927107,-0.591411
lnq,-1.080425,0.375545,-2.876952,4.630885e-03,-1.822762,-0.338088
(lnq)^2,0.026489,0.002357,11.240060,2.112040e-21,0.021831,0.031148
(lnq)(lnp1),0.131041,0.038284,3.422854,8.084865e-04,0.055365,0.206716
(lnq)(lnp2),0.058652,0.025549,2.295650,2.315002e-02,0.008149,0.109155
(lnq)(lnp3),0.040144,0.029791,1.347518,1.799447e-01,-0.018744,0.099033
lnp1,14.718292,7.084823,2.077440,3.954949e-02,0.713777,28.722807
lnp2,-0.894733,2.842313,-0.314790,7.533796e-01,-6.513111,4.723645
lnp3,6.380797,4.529207,1.408811,1.610617e-01,-2.572051,15.333645
(lnp1)^2,-1.538527,0.692403,-2.222011,2.785341e-02,-2.907195,-0.169860
(lnp2)^2,-0.073506,0.182039,-0.403791,6.869699e-01,-0.433340,0.286329
(lnp3)^2,-0.327414,0.440709,-0.742927,4.587448e-01,-1.198560,0.543731
(lnp1)(lnp2),0.324566,0.540144,0.600888,5.488659e-01,-0.743132,1.392263
(lnp1)(lnp3),-1.144101,0.743781,-1.538224,1.262037e-01,-2.614326,0.326124
(lnp2)(lnp3),-0.048049,0.492659,-0.097531,9.224414e-01,-1.021884,0.925785

In [255]:
import scipy.stats as stats
def reg_OLS( x : pd.DataFrame, y : pd.Series, intercept = True ):
    
    if not isinstance( x, pd.DataFrame ):
        raise TypeError( 'x is not a pd.DataFrame' )
    
    if not isinstance( y, pd.Series ):
        raise TypeError( 'y is not a pd.Series' )
    
    if not isinstance( intercept, bool ):
        raise TypeError( 'intercept is not a bool' )
        
    if (intercept == True):
        
        beta = beta_OLS( x, y, intercept = True )
        var = var_OLS( x, y, intercept = True )
                     
        reg_OLS = pd.DataFrame( beta )
        
        var_cov = var.to_numpy() 
        
        diagonal = [var_cov[i][i] for i in range( len(var_cov[0]) )] #extract diagonal
        
        std_error = np.sqrt( np.array(diagonal) )

        reg_OLS[ 'Std.Err.' ] = std_error 

        reg_OLS[ 't' ] = reg_OLS[ 'Coef.' ] / reg_OLS[ 'Std.Err.' ]
        
        p = stats.t.sf( abs( reg_OLS[ 't' ] ), df = len( y ) - len( beta ) ) * 2
        
        reg_OLS[ 'P>|t|' ] = p
                
        reg_OLS['[0.025'] = reg_OLS[ 'Coef.' ] - stats.t.ppf(q = 1 - 0.05 / 2, df = len(y)-len(beta)) * reg_OLS[ 'Std.Err.' ]
               
        reg_OLS['0.975]'] = reg_OLS[ 'Coef.' ] + stats.t.ppf(q = 1 - 0.05 / 2, df = len(y)-len(beta)) * reg_OLS[ 'Std.Err.' ]

        
    else:
        
        beta = beta_OLS( X, y, intercept = False )
        var = var_OLS( X, y, intercept = False )
            
        reg_OLS = pd.DataFrame( beta )
        
        var_cov = var.to_numpy() 
        
        diagonal = [var_cov[i][i] for i in range( len(var_cov[0]) )] #extract diagonal
        
        std_error = np.sqrt( np.array(diagonal) )

        reg_OLS[ 'Std.Err.' ] = std_error 
        
        reg_OLS[ 't' ] = reg_OLS[ 'Coef.' ] / reg_OLS[ 'Std.Err.' ]
        
        p = stats.t.sf( abs( reg_OLS[ 't' ] ), df = len( y ) - len( beta ) ) * 2
        
        reg_OLS[ 'P>|t|' ] = p
               
        reg_OLS['[0.025'] = reg_OLS[ 'Coef.' ] - stats.t.ppf(q = 1 - 0.05 / 2, df = len(y)-len(beta)) * reg_OLS[ 'Std.Err.' ]
               
        reg_OLS['0.975]'] = reg_OLS[ 'Coef.' ] + stats.t.ppf(q = 1 - 0.05 / 2, df = len(y)-len(beta)) * reg_OLS[ 'Std.Err.' ]

        
    return reg_OLS

In [256]:
reg_OLS (x, y, intercept = True)

,Coef.,Std.Err.,t,P>|t|,[0.025,0.975]
Intercept,-76.259258,38.280035,-1.992142,4.825953e-02,-151.927105,-0.591411
lnq,-1.080425,0.375545,-2.876952,4.630885e-03,-1.822762,-0.338088
lnq2,0.026489,0.002357,11.240060,2.112040e-21,0.021831,0.031148
lnqlnp1,0.131041,0.038284,3.422854,8.084865e-04,0.055365,0.206716
lnqlnp2,0.058652,0.025549,2.295650,2.315002e-02,0.008149,0.109155
lnqlnp3,0.040144,0.029791,1.347518,1.799447e-01,-0.018744,0.099033
lnp1,14.718292,7.084823,2.077440,3.954949e-02,0.713777,28.722807
lnp2,-0.894733,2.842313,-0.314790,7.533796e-01,-6.513110,4.723645
lnp3,6.380797,4.529207,1.408811,1.610617e-01,-2.572051,15.333644
lnp1_2,-0.769264,0.346201,-2.222011,2.785341e-02,-1.453597,-0.084930
lnp2_2,-0.036753,0.091019,-0.403791,6.869699e-01,-0.216670,0.143165
lnp3_2,-0.163707,0.220354,-0.742927,4.587448e-01,-0.599280,0.271866
lnp1lnp2,0.162283,0.270072,0.600888,5.488659e-01,-0.371566,0.696132
lnp1lnp3,-0.572050,0.371890,-1.538224,1.262037e-01,-1.307163,0.163062
lnp2lnp3,-0.024025,0.246329,-0.097531,9.224414e-01,-0.510942,0.462892

4. Generate a new function named as `restricted_OLS` that uses your previos functions `beta_OLS` and `var_OLS` to return an ouput similar to `reg_OLS_output`. The inputs of this function should be `X`, `y`,  `L`, `r`, and `intercept`. `X` (covariables) must be a **pd.DataFrame** and `y` (endog) must be a **pd.Series**,  `L` (coef) must be a **np.array**, `r` must be a **np.array**,  and `intercept` can be `True` or `False`.  When `intercept` is `False`, the estimated beta does not include **intercept**. Also, you must specify the type of your function's parameters and output and It must raise an error if the inputs do not meet the requirements. The ouput of this function should look like `restricted_OLS_ouput`. Apply your function to the equation below. Use greene data.
 **Hint: Use numpy, `def` function, and `columns` method, [link](https://notebooks.githubusercontent.com/view/ipynb?browser=chrome&color_mode=auto&commit=69c80e1f2c1c268f0480a32932262201785a576c&device=unknown_device&enc_url=68747470733a2f2f7261772e67697468756275736572636f6e74656e742e636f6d2f616c6578616e6465727175697370652f4469706c6f6d61646f5f505543502f363963383065316632633163323638663034383061333239333232363232303137383561353736632f4c6563747572655f352f4c6563747572655f352e6970796e62&logged_in=true&nwo=alexanderquispe%2FDiplomado_PUCP&path=Lecture_5%2FLecture_5.ipynb&platform=windows&repository_id=427747212&repository_type=Repository&version=96##5.1.7.).**

$$
\hat{\boldsymbol{\beta}}^{(RLS)} =\hat{\boldsymbol{\beta}}^{(OLS)} - \left( \boldsymbol{X}^\top \boldsymbol{X} \right)^{-1} \boldsymbol{L}^\top \left( \boldsymbol{L}\left( \boldsymbol{X}^\top \boldsymbol{X} \right)^{-1} \boldsymbol{L}^\top \right)^{-1} \left( \boldsymbol{L}\widehat{\boldsymbol{\beta}}^{(OLS)} - \boldsymbol{r} \right)
$$

$$
\begin{aligned}
\mathbb{V}{\rm ar} \left(\widehat{\boldsymbol{\beta}}^{(RLS)} \right) 
&= \sigma^2 \left( \mathbf{X}^\top  \mathbf{X}\right)^{-1} - \sigma^2 \left( \mathbf{X}^\top  \mathbf{X}\right)^{-1}  \mathbf{L}^\top \left( \mathbf{L}\left( \mathbf{X}^\top \mathbf{X} \right)^{-1} \mathbf{L}^\top \right)^{-1}  \mathbf{L} \left( \mathbf{X}^\top  \mathbf{X}\right)^{-1}
\end{aligned}
$$

$$
\begin{aligned} 
lnCT &= \beta_{0}+\beta_{q}lnq+ \beta_{qq}(lnq)^2+\beta_{q1}lnqlnp_1+\beta_{q2}lnqlnp_2+ \beta_{q3}lnqlnp_{3} +\beta_{1}lnp_1+\beta_{2}lnp_2+ \beta_{3}lnp_3 \\
& + \beta_{11}(lnp_{1})^2+ \beta_{22}(lnp_{2})^2+ \beta_{33}(lnp_{3})^2 + \beta_{12}lnp_{1}lnp_{2}+ \beta_{13}lnp_{1}lnp_{3}+\beta_{23}lnp_{2}lnp_{3} 
\end{aligned}
$$

ST: 

<br>
$$
\begin{aligned} 
\beta_{1} + \beta_{2} + \beta_{3} &= 1 \\
\beta_{q1} + \beta_{q2} + \beta_{q3} &= 0 \\
\beta_{11} + \beta_{12} + \beta_{13} &= 0 \\
\beta_{21} + \beta_{22} + \beta_{23} &= 0 \\
\beta_{31} + \beta_{32} + \beta_{33} &= 0 \\
\beta_{ij} = \beta_{ji}
\end{aligned}
$$

In [257]:
L = np.array( ( [ 0, 0, 0, 0, 0, 0, 1, 1, 1, 0, 0, 0, 0, 0, 0 ], 
              [ 0, 0, 0, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0 ], 
              [ 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 1, 0 ], 
              [ 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 1 ], 
              [ 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 1 ] ) )

r = np.array(  [  1,  0,  0,  0,  0  ]  ).reshape( -1 , 1 )

5. Generate a new class named `RegClass`. The initial attributes of your class must be `X`, `y`, and `intercept`. `X` (covariables) must be a **pd.DataFrame** and `y` (endog) must be a **pd.Series** and `intercept` can be `True` or `False`, by default `True`. Also, you must specify the type of your class' parameters, and output and It must raise an error if the inputs do not meet the requirements.  This class should have two methods: `reg_OLS` and `restricted_OLS` (You can add more if you think it is necessary). These methods should return the same output as the previously defined functions with the same name. The method `reg_OLS` does not need an extra parameter to be executed. After executing the method `reg_OLS`, any user should access the following attributes: `beta_OLS` and `var_OLS`. They should look like `beta_OLS_output` and `var_OLS_output`. The `restricted_OLS` method needs two extra parameters before being executed, `L` and `r`. They refer to the restrictions. After running the method `restricted_OLS`, any user should access the following attributes: `beta_OLS`, `var_OLS`, `rest_beta_OLS`, and `rest_var_OLS`. These attributes refer to the beta and variance estimated using OLS and restricted OLS. They should look like  `beta_OLS_output` and `var_OLS_output`. Fix all the methods and attributes. No user should be able to change them. **Hint: Use [lecture 6](https://notebooks.githubusercontent.com/view/ipynb?browser=chrome&color_mode=auto&commit=69c80e1f2c1c268f0480a32932262201785a576c&device=unknown_device&enc_url=68747470733a2f2f7261772e67697468756275736572636f6e74656e742e636f6d2f616c6578616e6465727175697370652f4469706c6f6d61646f5f505543502f363963383065316632633163323638663034383061333239333232363232303137383561353736632f4c6563747572655f362f4c6563747572655f362e6970796e62&logged_in=true&nwo=alexanderquispe%2FDiplomado_PUCP&path=Lecture_6%2FLecture_6.ipynb&platform=windows&repository_id=427747212&repository_type=Repository&version=96#6.3.).**