**Group 6** 
1. Carmen Mendoza
2. Joaquín Pérez
3. Lizbeth Minaya
4. Valeria Albarracín

# 1 Assignment

It is totally prohibited to use any kind of loop. You can use stackoverflow. If you copy codes from previous answers, explain each step. No explanation is `0 points`.

## 1.1 Numpy
1. Replace all the `even_numbers` in `np1` with 100. **Hint: Use `indexing` in arrys and [this filer](https://stackoverflow.com/questions/41638751/filtering-even-numbers-in-python).** <br><br>
2. Create a 3x3 matrix with values ranging from 0 to 8. **Hint: Use `np.arange` and `np.reshape` method.** <br><br>
3. Consider an array `Z = [1,2,3,4,5,6,7,8,9,10]`, generate an array `R = [ [ 1, 2, 3, 4], [ 2, 3, 4, 5 ], [ 3, 4, 5, 6 ], ..., [ 7, 8, 9, 10 ] ]`?.**Hint: Use `np.arange` and `np.concatenate`** <br><br>
4. Create a 3x3x3 array with random values. **Hint: Use [`np.random.random`](https://docs.scipy.org/doc/numpy-1.15.0/reference/generated/numpy.random.random.html).** <br><br>
5. Comment why this expression `np.nan == np.nan` is False. **Hint: Use stackoverflow.** <br><br>
6. Print the `mean` and `standard deviation` of `np2`. **Hint: Use `f-string`, `np.mean`, and `np.var` methods.**

In [3]:
import numpy as np
np1 = np.arange( 200, 750)
np2 = np.random.normal( 50 , 4, 300)

1. Replace all the even_numbers in np1 with 100. Hint: Use indexing in arrys and this filer.

In [17]:
#Show np1
np1 = np.arange( 200, 750)
np1

array([200, 201, 202, 203, 204, 205, 206, 207, 208, 209, 210, 211, 212,
       213, 214, 215, 216, 217, 218, 219, 220, 221, 222, 223, 224, 225,
       226, 227, 228, 229, 230, 231, 232, 233, 234, 235, 236, 237, 238,
       239, 240, 241, 242, 243, 244, 245, 246, 247, 248, 249, 250, 251,
       252, 253, 254, 255, 256, 257, 258, 259, 260, 261, 262, 263, 264,
       265, 266, 267, 268, 269, 270, 271, 272, 273, 274, 275, 276, 277,
       278, 279, 280, 281, 282, 283, 284, 285, 286, 287, 288, 289, 290,
       291, 292, 293, 294, 295, 296, 297, 298, 299, 300, 301, 302, 303,
       304, 305, 306, 307, 308, 309, 310, 311, 312, 313, 314, 315, 316,
       317, 318, 319, 320, 321, 322, 323, 324, 325, 326, 327, 328, 329,
       330, 331, 332, 333, 334, 335, 336, 337, 338, 339, 340, 341, 342,
       343, 344, 345, 346, 347, 348, 349, 350, 351, 352, 353, 354, 355,
       356, 357, 358, 359, 360, 361, 362, 363, 364, 365, 366, 367, 368,
       369, 370, 371, 372, 373, 374, 375, 376, 377, 378, 379, 380, 381,
       382, 383, 384, 385, 386, 387, 388, 389, 390, 391, 392, 393, 394,
       395, 396, 397, 398, 399, 400, 401, 402, 403, 404, 405, 406, 407,
       408, 409, 410, 411, 412, 413, 414, 415, 416, 417, 418, 419, 420,
       421, 422, 423, 424, 425, 426, 427, 428, 429, 430, 431, 432, 433,
       434, 435, 436, 437, 438, 439, 440, 441, 442, 443, 444, 445, 446,
       447, 448, 449, 450, 451, 452, 453, 454, 455, 456, 457, 458, 459,
       460, 461, 462, 463, 464, 465, 466, 467, 468, 469, 470, 471, 472,
       473, 474, 475, 476, 477, 478, 479, 480, 481, 482, 483, 484, 485,
       486, 487, 488, 489, 490, 491, 492, 493, 494, 495, 496, 497, 498,
       499, 500, 501, 502, 503, 504, 505, 506, 507, 508, 509, 510, 511,
       512, 513, 514, 515, 516, 517, 518, 519, 520, 521, 522, 523, 524,
       525, 526, 527, 528, 529, 530, 531, 532, 533, 534, 535, 536, 537,
       538, 539, 540, 541, 542, 543, 544, 545, 546, 547, 548, 549, 550,
       551, 552, 553, 554, 555, 556, 557, 558, 559, 560, 561, 562, 563,
       564, 565, 566, 567, 568, 569, 570, 571, 572, 573, 574, 575, 576,
       577, 578, 579, 580, 581, 582, 583, 584, 585, 586, 587, 588, 589,
       590, 591, 592, 593, 594, 595, 596, 597, 598, 599, 600, 601, 602,
       603, 604, 605, 606, 607, 608, 609, 610, 611, 612, 613, 614, 615,
       616, 617, 618, 619, 620, 621, 622, 623, 624, 625, 626, 627, 628,
       629, 630, 631, 632, 633, 634, 635, 636, 637, 638, 639, 640, 641,
       642, 643, 644, 645, 646, 647, 648, 649, 650, 651, 652, 653, 654,
       655, 656, 657, 658, 659, 660, 661, 662, 663, 664, 665, 666, 667,
       668, 669, 670, 671, 672, 673, 674, 675, 676, 677, 678, 679, 680,
       681, 682, 683, 684, 685, 686, 687, 688, 689, 690, 691, 692, 693,
       694, 695, 696, 697, 698, 699, 700, 701, 702, 703, 704, 705, 706,
       707, 708, 709, 710, 711, 712, 713, 714, 715, 716, 717, 718, 719,
       720, 721, 722, 723, 724, 725, 726, 727, 728, 729, 730, 731, 732,
       733, 734, 735, 736, 737, 738, 739, 740, 741, 742, 743, 744, 745,
       746, 747, 748, 749])

In [18]:
# Create a boolean that when a value of 'np1' is divided by 2 and the remainder is 0,it returns True
#This boolean works as a kind of filter
number=np1%2==0
#Now, every time the filer get a true result, this will be replace with 100
np1[number] =100
np1

array([200, 201, 202, 100, 204, 205, 206, 207, 208, 100, 210, 211, 212,
       213, 214, 100, 216, 217, 218, 219, 220, 100, 222, 223, 224, 225,
       226, 100, 228, 229, 230, 231, 232, 100, 234, 235, 236, 237, 238,
       100, 240, 241, 242, 243, 244, 100, 246, 247, 248, 249, 250, 100,
       252, 253, 254, 255, 256, 100, 258, 259, 260, 261, 262, 100, 264,
       265, 266, 267, 268, 100, 270, 271, 272, 273, 274, 100, 276, 277,
       278, 279, 280, 100, 282, 283, 284, 285, 286, 100, 288, 289, 290,
       291, 292, 100, 294, 295, 296, 297, 298, 100, 300, 301, 302, 303,
       304, 100, 306, 307, 308, 309, 310, 100, 312, 313, 314, 315, 316,
       100, 318, 319, 320, 321, 322, 100, 324, 325, 326, 327, 328, 100,
       330, 331, 332, 333, 334, 100, 336, 337, 338, 339, 340, 100, 342,
       343, 344, 345, 346, 100, 348, 349, 350, 351, 352, 100, 354, 355,
       356, 357, 358, 100, 360, 361, 362, 363, 364, 100, 366, 367, 368,
       369, 370, 100, 372, 373, 374, 375, 376, 100, 378, 379, 380, 381,
       382, 100, 384, 385, 386, 387, 388, 100, 390, 391, 392, 393, 394,
       100, 396, 397, 398, 399, 400, 100, 402, 403, 404, 405, 406, 100,
       408, 409, 410, 411, 412, 100, 414, 415, 416, 417, 418, 100, 420,
       421, 422, 423, 424, 100, 426, 427, 428, 429, 430, 100, 432, 433,
       434, 435, 436, 100, 438, 439, 440, 441, 442, 100, 444, 445, 446,
       447, 448, 100, 450, 451, 452, 453, 454, 100, 456, 457, 458, 459,
       460, 100, 462, 463, 464, 465, 466, 100, 468, 469, 470, 471, 472,
       100, 474, 475, 476, 477, 478, 100, 480, 481, 482, 483, 484, 100,
       486, 487, 488, 489, 490, 100, 492, 493, 494, 495, 496, 100, 498,
       499, 500, 501, 502, 100, 504, 505, 506, 507, 508, 100, 510, 511,
       512, 513, 514, 100, 516, 517, 518, 519, 520, 100, 522, 523, 524,
       525, 526, 100, 528, 529, 530, 531, 532, 100, 534, 535, 536, 537,
       538, 100, 540, 541, 542, 543, 544, 100, 546, 547, 548, 549, 550,
       100, 552, 553, 554, 555, 556, 100, 558, 559, 560, 561, 562, 100,
       564, 565, 566, 567, 568, 100, 570, 571, 572, 573, 574, 100, 576,
       577, 578, 579, 580, 100, 582, 583, 584, 585, 586, 100, 588, 589,
       590, 591, 592, 100, 594, 595, 596, 597, 598, 100, 600, 601, 602,
       603, 604, 100, 606, 607, 608, 609, 610, 100, 612, 613, 614, 615,
       616, 100, 618, 619, 620, 621, 622, 100, 624, 625, 626, 627, 628,
       100, 630, 631, 632, 633, 634, 100, 636, 637, 638, 639, 640, 100,
       642, 643, 644, 645, 646, 100, 648, 649, 650, 651, 652, 100, 654,
       655, 656, 657, 658, 100, 660, 661, 662, 663, 664, 100, 666, 667,
       668, 669, 670, 100, 672, 673, 674, 675, 676, 100, 678, 679, 680,
       681, 682, 100, 684, 685, 686, 687, 688, 100, 690, 691, 692, 693,
       694, 100, 696, 697, 698, 699, 700, 100, 702, 703, 704, 705, 706,
       100, 708, 709, 710, 711, 712, 100, 714, 715, 716, 717, 718, 100,
       720, 721, 722, 723, 724, 100, 726, 727, 728, 729, 730, 100, 732,
       733, 734, 735, 736, 100, 738, 739, 740, 741, 742, 100, 744, 745,
       746, 747, 748, 100])

2. Create a 3x3 matrix with values ranging from 0 to 8. Hint: Use np.arange and np.reshape method

In [6]:
#Create an array with the values from 0 to 8.
a=np.arange(9)
print(a)
#To create a 3x3 matrix, we reshape 'a' and put the dimensions
b=np.reshape(,(3,3))
print(b)

[0 1 2 3 4 5 6 7 8]
[[0 1 2]
 [3 4 5]
 [6 7 8]]

3. Consider an array `Z = [1,2,3,4,5,6,7,8,9,10]`, generate an array `R = [ [ 1, 2, 3, 4], [ 2, 3, 4, 5 ], [ 3, 4, 5, 6 ], ..., [ 7, 8, 9, 10 ] ]`?.**Hint: Use `np.arange` and `np.concatenate`** <br><br>

In [7]:
#Create an array Z with values from 1 to 10
Z = np.arange(1,11)
#Generate a new array 'R' by concatenating intervals of 'Z'
#Each interval contains four elements
R = np.concatenate(([Z[0:4]], [Z[1:5]], [Z[2:6]], [Z[3:7]], [Z[4:8]], [Z[5:9]], [Z[6:10]]), axis=0)
R

array([[ 1,  2,  3,  4],
       [ 2,  3,  4,  5],
       [ 3,  4,  5,  6],
       [ 4,  5,  6,  7],
       [ 5,  6,  7,  8],
       [ 6,  7,  8,  9],
       [ 7,  8,  9, 10]])

4. Create a 3x3x3 array with random values. **Hint: Use [`np.random.random`](https://docs.scipy.org/doc/numpy-1.15.0/reference/generated/numpy.random.random.html).** <br><br>

In [22]:
#First, I created and array with random values indicating it is 3x3x3, using np.random.random
array = np.random.random((3,3,3))
#Next I printed the output
print(array)

[[[0.53782742 0.59577428 0.21330486]
  [0.37023132 0.38115797 0.78936462]
  [0.67138119 0.73383594 0.13626683]]

 [[0.47537952 0.9263402  0.54434102]
  [0.80408486 0.41346292 0.92569562]
  [0.12252464 0.10250705 0.35699555]]

 [[0.3973671  0.70295335 0.20824051]
  [0.5001293  0.49553133 0.36636986]
  [0.57103084 0.95094085 0.53773297]]]

5. Comment why this expression `np.nan == np.nan` is False. **Hint: Use stackoverflow.** <br><br>

np.nan == np.nan

In [23]:
np.nan == np.nan
#The reason the expression np.nan == np.nan is False may be in that NaN are just substitutes or "place-holders" for missing numerical values. 
#Nonetheless, that does not imply that the original numerical values of different NaN are the same: NaN is just working as a constant. 
#Hence, the expression np.nan == np.nan is False as far as the original numerical values are unknown, 
# so it is not possible to assert they are equivalent.

False

6. Print the `mean` and `standard deviation` of `np2`. **Hint: Use `f-string`, `np.mean`, and `np.var` methods.**

In [19]:
#First I calculated the mean for np2 using np.mean and saved it
mean = np.mean(np2)
#Then I rounded the mean to two digits
mean = str(round(mean, 2))

#Second I calculated the standard deviation for np2 using np.mean and saved it
var = np.var(np2)
#Then I rounded the standard deviation to two digits
var = str(round(var, 2))

#Finally I printed the output with f-string
print(f"The mean of np2 is {mean}, and the standard deviation is {var} ")

The mean of np2 is 49.91, and the standard deviation is 18.18

# Pandas

Run the code bellow uncomment the second line to install savReaderWriter library. The `dict_varlabels` has the labels of the columns of rec1.

1. Check if CASEID identifies each observation uniquely. **[Hint: Use is_unique method.](https://pandas.pydata.org/docs/reference/api/pandas.Series.is_unique.html)**
2. Make the CASEID column the index of your data set. **[Hint: Use set_index](https://pandas.pydata.org/docs/reference/api/pandas.DataFrame.set_index.html)**. 
3. Keep women who are 15-30 years old and live in Urban areas. **[Hint: Use query](https://pandas.pydata.org/docs/reference/api/pandas.DataFrame.query.html)**.
4. Generate a new column with the month of born. Just use the first three letters.  Use the English names of the months.

In [14]:
import pandas as pd

In [15]:
pip install savReaderWriter

Requirement already satisfied: savReaderWriter in c:\users\usuario\anaconda3\lib\site-packages (3.4.2)
Note: you may need to restart the kernel to use updated packages.

In [16]:
pip install pyreadstat

Requirement already satisfied: pyreadstat in c:\users\usuario\anaconda3\lib\site-packages (1.2.0)
Requirement already satisfied: pandas>=1.2.0 in c:\users\usuario\anaconda3\lib\site-packages (from pyreadstat) (1.4.4)
Requirement already satisfied: numpy>=1.18.5 in c:\users\usuario\anaconda3\lib\site-packages (from pandas>=1.2.0->pyreadstat) (1.21.5)
Requirement already satisfied: python-dateutil>=2.8.1 in c:\users\usuario\anaconda3\lib\site-packages (from pandas>=1.2.0->pyreadstat) (2.8.2)
Requirement already satisfied: pytz>=2020.1 in c:\users\usuario\anaconda3\lib\site-packages (from pandas>=1.2.0->pyreadstat) (2022.1)
Requirement already satisfied: six>=1.5 in c:\users\usuario\anaconda3\lib\site-packages (from python-dateutil>=2.8.1->pandas>=1.2.0->pyreadstat) (1.16.0)
Note: you may need to restart the kernel to use updated packages.

In [17]:
#We install the requested library
import savReaderWriter as sav

In [20]:
# read REC0111 data
#!pip install savReaderWriter
import savReaderWriter as sav
rec1 = pd.read_spss( fr"C:/QLAB_Summer_Python/_data/endes/2019/REC0111.sav" )

# Get labels from sav file
with sav.SavHeaderReader( fr"C:/QLAB_Summer_Python/_data/endes/2019/REC0111.sav", ioUtf8=True) as header:
    metadata = header.all()

dict_varlabels = metadata[3]

In [21]:
dict_varlabels

{'ID1': 'Año',
 'HHID': 'Identificación Cuestionario del Hogar',
 'CASEID': 'Identificación Cuestionario Individual',
 'V001': 'Conglomerado',
 'V002': 'Número de vivienda',
 'V003': 'Número de línea de entrevistada',
 'V004': 'Unidad de área final',
 'V007': 'Año de la entrevista',
 'V008': 'Fecha de la entrevista, Codificación centenaria de meses (CMC)',
 'V009': 'Mes de nacimiento de la entrevistada',
 'V010': 'Año de nacimiento de la entrevistada',
 'V011': 'Fecha de nacimiento, Codificación centenaria de meses (CMC)',
 'V012': 'Edad actual - entrevistada',
 'V013': 'Edad actual por grupos de 5 años',
 'V014': 'Integridad de la información para la fecha de nacimiento ',
 'V015': 'Resultado entrevista individual',
 'V017': 'Inicio del calendario, Codificación centenaria de mesesl CMC',
 'V018': 'Columna del mes de la entrevista',
 'V019': 'Duración del calendario',
 'V019A': 'Número de columnas de calendario',
 'V020': 'Muestra alguna vez casada',
 'V021': 'Unidad de muestreo primario - conglomerado',
 'V023': 'Dominio de ejemplo - Departamento',
 'V024': 'Región',
 'V025': 'Tipo de lugar de residencia',
 'V026': 'El lugar de residencia en el que se entrevistó - De Facto',
 'V027': 'Número de visitas',
 'V028': 'Identificación del entrevistador',
 'V029': 'Identificador del digitador',
 'V030': 'Supervisor de campo',
 'V031': 'Editor de campo',
 'V032': 'Editor de la oficina',
 'V033': 'Selección final del área de probabilidad',
 'V034': 'Número de orden del esposo',
 'V040': 'Altitud del conglomerado en metros',
 'V042': 'Selección de hogar para hemoglobina',
 'V043': 'Selección para módulo de estatus de mujeres',
 'V044': 'Selección para módulo de violencia domestica',
 'V000': 'Código y fase del país',
 'Q105DD': 'Dia de nacimeinto de la entrevistada',
 'V101': 'Región',
 'V102': 'Tipo de lugar de residencia',
 'V103': 'Lugar de residencia de la infancia',
 'V104': 'Cuanto tiempo tiene viviendo continuamente en el lugar de residencia actual',
 'V105': 'Tipo de lugar de residencia anteriormente',
 'V106': 'Nivel educativo más alto',
 'V107': 'Año/grado de educación más alto aprobado',
 'V113': 'Fuente principal de abasteciemiento de agua potable que utilizan en su hogar para tomar o beber',
 'V115': 'Tiempo para llegar a la fuente de agua',
 'V116': 'Tipo de instalación sanitaria',
 'V119': 'En su hogar tiene: electricidad',
 'V120': 'En su hogar tiene: radio',
 'V121': 'En su hogar tiene: televisión',
 'V122': 'En su hogar tiene: refrigerador',
 'V123': 'En su hogar tiene: bicicleta',
 'V124': 'En su hogar tiene: motocicleta/motocar',
 'V125': 'En su hogar tiene: coche/camión',
 'V127': 'Material predominante del piso de la vivienda',
 'V128': 'Material predominante de las paredes exteriores de la vivienda',
 'V129': 'Material predominante del techo de la vivienda',
 'V130': 'Religión',
 'V131': 'Etnicidad',
 'V133': 'Educación en años simples',
 'V134': 'El lugar en el que se realizó la entrevista  De-facto',
 'V135': 'Residente habitual o visitante',
 'V136': 'Número de miembros del hogar',
 'V137': 'Número de niños de 6 años de edad ',
 'V138': 'Número de mujeres de 15 a 49 años de edad elegibles en el hogar ',
 'V139': 'Región, residencia habitual De-jure',
 'V140': 'Tipo de área de residencia De-jure',
 'V141': 'Lugar de residencia De-jure',
 'V149': 'Logro educativo',
 'V150': 'Relación con el jefe del hogar',
 'V151': 'Sexo del Jefe del Hogar',
 'V152': 'Edad del jefe del hogar',
 'V153': 'En su hogar tiene: teléfono',
 'AWFACTT': 'Factor todas las mujeres - total',
 'AWFACTU': 'Factor todas las mujeres - urbano/rural',
 'AWFACTR': 'Factor todas las mujeres - regional',
 'AWFACTE': 'Factor todas las mujeres - educación',
 'AWFACTW': 'Factor todas las mujeres - índice de riqueza',
 'V155': 'Alfabetización',
 'V156': 'Alguna vez participó en un programa de alfabetización (no incluyendo la escuela primaria)',
 'V157': 'Frecuencia de lectura de un periódico o revista',
 'V158': 'Frecuencia de escuchar radio',
 'V159': 'Frecuencia de ver televisión',
 'V160': 'Baño compartido con otros hogares',
 'V161': 'Tipo de combustible para cocinar',
 'V166': 'Resultados de la prueba del yodo en la sal',
 'V167': 'Número de viajes en los últimos 12 meses',
 'V168': 'Afuera más de un mes en los últimos 12 meses',
 'ML101': 'Tipo de mosquitero que utilizo para dormir última noche',
 'QD333_1': 'Alguna dificultad o limitación permanente para ver, aún usando anteojos',
 'QD333_2': 'Alguna dificultad o limitación permanente para oir, aún usando audífonos',
 'QD333_3': 'Alguna dificultad o limitación permanente para hablar o comunicarse, aún usando la lengua de señas u otro',
 'QD333_4': 'Alguna dificultad o limitación permanente para moverse o caminar para usar brazos y/o piernas',
 'QD333_5': 'Alguna dificultad o limitación permanente para entender o aprender (concentrarse y recordarse)',
 'QD333_6': 'Alguna dificultad o limitación permanente para relacionarse con los demás, por sus pensamientos, sentimientos, emociones o conductas',
 'UBIGEO': 'Código de Ubicación Gegráfica',
 'V022': 'Estratos',
 'V005': 'Factor de ponderacion',
 'V190': 'Índice de riqueza',
 'V191': 'Factor de puntuación del índice de riqueza (5 decimales)',
 'mujeres12a49': 'Mujeres de 12 a 49 años de edad',
 'NCONGLOME': 'Número de Conglomerado (proveniente del marco)'}

In [26]:
#ACT1
# We check if CASEID uniquely identifies each observation with the "is_unique" function

( rec1[ 'CASEID' ] ).is_unique

True

In [27]:
#ACT2
# Make the CASEISD column the index of its data set with "set_index"

rec1.set_index('CASEID')

,ID1,HHID,V001,V002,V003,V004,V007,V008,V009,V010,...,QD333_4,QD333_5,QD333_6,UBIGEO,V022,V005,V190,V191,mujeres12a49,NCONGLOME
CASEID,,,,,,,,,,,,,,,,,,,,,
000100201 2,2019.0,000100201,1.0,2.0,2.0,1.0,2019.0,1434.0,4.0,1986.0,...,No,No,No,010101,3.0,154803.0,Rico,1.234450,Mujeres de 15 a 49 años de edad,7065.0
000100201 3,2019.0,000100201,1.0,2.0,3.0,1.0,2019.0,1434.0,1.0,2007.0,...,No,No,No,010101,3.0,154803.0,Rico,1.234450,"Mujeres de 12 a 14 de edad, nunca embarazadas",7065.0
000102801 2,2019.0,000102801,1.0,28.0,2.0,1.0,2019.0,1434.0,6.0,1983.0,...,No,No,No,010101,3.0,154803.0,Rico,1.295611,Mujeres de 15 a 49 años de edad,7065.0
000102801 6,2019.0,000102801,1.0,28.0,6.0,1.0,2019.0,1434.0,3.0,1970.0,...,No,No,No,010101,3.0,154803.0,Rico,1.295611,Mujeres de 15 a 49 años de edad,7065.0
000104801 2,2019.0,000104801,1.0,48.0,2.0,1.0,2019.0,1434.0,5.0,1991.0,...,No,No,No,010101,3.0,154803.0,Pobrer,-0.256431,Mujeres de 15 a 49 años de edad,7065.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
325406201 2,2019.0,325406201,3254.0,62.0,2.0,3254.0,2019.0,1440.0,12.0,1971.0,...,No,No,No,250401,249.0,244995.0,El más pobre,-1.750187,Mujeres de 15 a 49 años de edad,15783.0
325406301 2,2019.0,325406301,3254.0,63.0,2.0,3254.0,2019.0,1440.0,6.0,1988.0,...,No,No,No,250401,249.0,244995.0,El más pobre,-1.676861,Mujeres de 15 a 49 años de edad,15783.0
325407001 2,2019.0,325407001,3254.0,70.0,2.0,3254.0,2019.0,1440.0,7.0,1973.0,...,No,No,No,250401,249.0,459792.0,El más pobre,-1.585333,Mujeres de 15 a 49 años de edad,15783.0
325407201 2,2019.0,325407201,3254.0,72.0,2.0,3254.0,2019.0,1440.0,12.0,1994.0,...,No,No,No,250401,249.0,459792.0,El más pobre,-1.650159,Mujeres de 15 a 49 años de edad,15783.0
325407401 2,2019.0,325407401,3254.0,74.0,2.0,3254.0,2019.0,1440.0,10.0,1996.0,...,No,No,No,250401,249.0,244995.0,El más pobre,-1.644720,Mujeres de 15 a 49 años de edad,15783.0

In [29]:
#ACT3
# Keep women who are 15-30 years old and live in Urban areas. Hint: Use query.
rec1.query('V012>15 & V012<30 & V025=="Urbano"')

,ID1,HHID,CASEID,V001,V002,V003,V004,V007,V008,V009,...,QD333_4,QD333_5,QD333_6,UBIGEO,V022,V005,V190,V191,mujeres12a49,NCONGLOME
4,2019.0,000104801,000104801 2,1.0,48.0,2.0,1.0,2019.0,1434.0,5.0,...,No,No,No,010101,3.0,154803.0,Pobrer,-0.256431,Mujeres de 15 a 49 años de edad,7065.0
8,2019.0,000116701,000116701 1,1.0,167.0,1.0,1.0,2019.0,1434.0,6.0,...,No,No,No,010101,3.0,154803.0,Más rico,1.672440,Mujeres de 15 a 49 años de edad,7065.0
9,2019.0,000119101,000119101 1,1.0,191.0,1.0,1.0,2019.0,1434.0,9.0,...,No,No,No,010101,3.0,154803.0,Pobrer,0.234148,Mujeres de 15 a 49 años de edad,7065.0
12,2019.0,000203001,000203001 2,2.0,30.0,2.0,2.0,2019.0,1432.0,5.0,...,No,No,No,010101,2.0,65298.0,Pobrer,-0.196449,Mujeres de 15 a 49 años de edad,7068.0
14,2019.0,000204001,000204001 3,2.0,40.0,3.0,2.0,2019.0,1432.0,9.0,...,No,No,No,010101,2.0,65298.0,Medio,0.560448,Mujeres de 15 a 49 años de edad,7068.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
38162,2019.0,324202401,324202401 2,3242.0,24.0,2.0,3242.0,2019.0,1436.0,2.0,...,No,No,No,250302,248.0,203603.0,Pobrer,-0.463931,Mujeres de 15 a 49 años de edad,45556.0
38163,2019.0,324202501,324202501 3,3242.0,25.0,3.0,3242.0,2019.0,1436.0,5.0,...,No,No,No,250302,248.0,567613.0,Pobrer,-0.576118,Mujeres de 15 a 49 años de edad,45556.0
38164,2019.0,324203901,324203901 1,3242.0,39.0,1.0,3242.0,2019.0,1436.0,8.0,...,No,No,No,250302,248.0,567613.0,El más pobre,-0.940013,Mujeres de 15 a 49 años de edad,45556.0
38165,2019.0,324204501,324204501 2,3242.0,45.0,2.0,3242.0,2019.0,1436.0,5.0,...,No,No,No,250302,248.0,203603.0,El más pobre,-0.656011,Mujeres de 15 a 49 años de edad,45556.0
38170,2019.0,324206901,324206901 3,3242.0,69.0,3.0,3242.0,2019.0,1436.0,10.0,...,No,No,No,250302,248.0,567613.0,Pobrer,-0.574662,Mujeres de 15 a 49 años de edad,45556.0

In [31]:
#ACT4
# Generate a new column with the month of born. Just use the first three letters. Use the English names of the months.
rec1['month']= pd.to_datetime(rec1['V009'], format='%m').dt.month_name().str.slice(stop=3)
rec1

,ID1,HHID,CASEID,V001,V002,V003,V004,V007,V008,V009,...,QD333_5,QD333_6,UBIGEO,V022,V005,V190,V191,mujeres12a49,NCONGLOME,month
0,2019.0,000100201,000100201 2,1.0,2.0,2.0,1.0,2019.0,1434.0,4.0,...,No,No,010101,3.0,154803.0,Rico,1.234450,Mujeres de 15 a 49 años de edad,7065.0,Apr
1,2019.0,000100201,000100201 3,1.0,2.0,3.0,1.0,2019.0,1434.0,1.0,...,No,No,010101,3.0,154803.0,Rico,1.234450,"Mujeres de 12 a 14 de edad, nunca embarazadas",7065.0,Jan
2,2019.0,000102801,000102801 2,1.0,28.0,2.0,1.0,2019.0,1434.0,6.0,...,No,No,010101,3.0,154803.0,Rico,1.295611,Mujeres de 15 a 49 años de edad,7065.0,Jun
3,2019.0,000102801,000102801 6,1.0,28.0,6.0,1.0,2019.0,1434.0,3.0,...,No,No,010101,3.0,154803.0,Rico,1.295611,Mujeres de 15 a 49 años de edad,7065.0,Mar
4,2019.0,000104801,000104801 2,1.0,48.0,2.0,1.0,2019.0,1434.0,5.0,...,No,No,010101,3.0,154803.0,Pobrer,-0.256431,Mujeres de 15 a 49 años de edad,7065.0,May
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
38330,2019.0,325406201,325406201 2,3254.0,62.0,2.0,3254.0,2019.0,1440.0,12.0,...,No,No,250401,249.0,244995.0,El más pobre,-1.750187,Mujeres de 15 a 49 años de edad,15783.0,Dec
38331,2019.0,325406301,325406301 2,3254.0,63.0,2.0,3254.0,2019.0,1440.0,6.0,...,No,No,250401,249.0,244995.0,El más pobre,-1.676861,Mujeres de 15 a 49 años de edad,15783.0,Jun
38332,2019.0,325407001,325407001 2,3254.0,70.0,2.0,3254.0,2019.0,1440.0,7.0,...,No,No,250401,249.0,459792.0,El más pobre,-1.585333,Mujeres de 15 a 49 años de edad,15783.0,Jul
38333,2019.0,325407201,325407201 2,3254.0,72.0,2.0,3254.0,2019.0,1440.0,12.0,...,No,No,250401,249.0,459792.0,El más pobre,-1.650159,Mujeres de 15 a 49 años de edad,15783.0,Dec
38334,2019.0,325407401,325407401 2,3254.0,74.0,2.0,3254.0,2019.0,1440.0,10.0,...,No,No,250401,249.0,244995.0,El más pobre,-1.644720,Mujeres de 15 a 49 años de edad,15783.0,Oct