# Assigment 5

This assigment will be graded if everything works well. I will run the script as once and everything should be done without errors and mistakes. I should be able to run your scripts in my computer and get all the results. **USE RELATIVE PATHS**. An error or exception or anything that breaks the code will means NO GRADE (0). Additionally, you are not able to modify any file handly. It also means NO GRADE (0). Comment everything you think will help others read your script. We expect 0 errors using GitHub. Everything will be graded!

**ASK EVERYTHING! WE ARE HERE TO HELP YOU!**

1. Generate a folder with the name of your group in this folder **QLAB_Summer_Python/assignments/assignment_5/**. The code should run even if the folder exists.
2. Scrape all the available information in this [link](https://www.sbs.gob.pe/app/pp/EstadisticasSAEEPortal/Paginas/TIActivaTipoCreditoEmpresa.aspx?tip=C). Save an excel file by year and month request. The excel file should be name using the month and year of the sheet.

In [1]:
#Import all the libraries we're going to use
from selenium import webdriver
from selenium.webdriver.common.keys import Keys
from selenium.common.exceptions import NoSuchElementException
from selenium.webdriver import ActionChains
import pandas as pd
import numpy as np
import os
import time
import re
import unidecode
import time 
from selenium.webdriver.support.ui import Select
from webdriver_manager.chrome import ChromeDriverManager
from selenium.webdriver.common.by import By
from selenium.webdriver.chrome.options import Options
from pandas import json_normalize
import time
from time import sleep
import random
import json

In [2]:
#Firstly, we open the driver 
driver = webdriver.Chrome( ChromeDriverManager().install() )

# Maximize window
driver.maximize_window()

C:\Users\XIMENA\AppData\Local\Temp\ipykernel_32760\4227828464.py:2: DeprecationWarning: executable_path has been deprecated, please pass in a Service object
  driver = webdriver.Chrome( ChromeDriverManager().install() )

In [3]:
#We establish the link of the website we're going to scrap
url_sbs = "https://www.sbs.gob.pe/app/pp/EstadisticasSAEEPortal/Paginas/TIActivaTipoCreditoEmpresa.aspx?tip=C"
driver.get( url_sbs )

In [4]:
driver.find_element( By.XPATH, "/html/body/form/div[4]/div/div/div[2]/div/div/div/div[1]/div/div/table/tbody")

In [5]:
sbs_table = pd.read_html( driver.find_element ( By.XPATH, "/html/body/form/div[4]/div/div/div[2]/div/div/div/div[1]/div/div/table/tbody").get_attribute('outerHTML'))
sbs_table

[   CMAC Arequipa CMAC Cusco CMAC del Santa CMAC Huancayo CMAC Ica CMAC Maynas  \
 0              -          -              -             -        -           -
 1              -          -              -             -        -           -
 2              -          -              -             -        -           -
 3              -          -              -             -        -           -
 4              -          -              -             -        -           -
 5              -          -              -             -        -           -
 6              -          -              -             -        -           -
 7              -          -              -             -        -           -
 8              -          -              -             -        -           -
 9              -          -              -             -        -           -
 10             -          -              -             -        -           -
 11             -          -              -             -        -           -
 12             -          -              -             -        -           -
 13             -          -              -             -        -           -
 14         13.46      18.28          19.56         20.70    21.91       16.15
 15             -          -              -             -        -           -
 16         31.76      79.59              -             -    83.40           -
 17         13.78      21.19              -         22.71        -           -
 18         23.24      19.53              -         17.00        -           -
 19         18.54      19.61              -         36.07    19.56       18.86
 20         13.29      16.29          19.56             -    20.83       16.14
 21         21.58      20.54          27.80         21.27    23.42       26.02
 22             -          -              -             -        -           -
 23         20.44      26.63              -         22.40    74.79       73.52
 24         22.59      23.32          31.78         28.87    33.55       35.92
 25         21.85      24.94          26.45         27.63    30.19       34.43
 26         20.99      23.10          28.21         27.62    25.74       31.73
 27         21.59      19.66          27.76         20.81    22.50       24.13
 28         31.26      25.86          38.76         30.99    32.82       42.61
 29             -      29.60              -             -        -           -
 30             -          -              -             -        -           -
 31         21.12          -              -             -        -           -
 32         30.36      42.22              -         42.79    83.40           -
 33         27.07      29.32          38.76         44.79    46.01       61.86
 34         34.05      34.42          44.41         43.88    42.09       52.34
 35         37.12      29.27          44.94         50.90    36.41       47.95
 36         31.02      23.38          37.76         29.24    31.38       35.64
 37         28.38      25.50          51.47         27.56    26.88       23.62
 38             -          -              -             -        -           -
 39             -          -              -             -        -           -
 40             -          -              -             -        -           -
 41         32.59      35.08          62.21         45.41    29.07       35.30
 42         28.22      19.99          48.90         26.06    26.47       19.47
 43         79.38      79.59          83.64         79.75    74.64       83.30
 44         14.19      13.34              -         12.79    14.53       13.22
 45         14.19      13.34              -         12.79    14.53       13.22

    CMAC Paita CMAC Piura CMAC Sullana CMAC Tacna CMAC Trujillo CMCP Lima  \
 0           -          -            -          -             -         -
 1           -          -            -          -             -         -
 2           -          -            -          -             -         -
 3           -          -            -          -             -         -
 4           -          -            -          -             -         -
 5           -          -            -          -             -         -
 6           -          -            -          -             -         -
 7           -      13.80            -          -             -         -
 8           -          -            -          -             -         -
 9           -          -            -          -             -         -
 10          -          -            -          -             -         -
 11          -          -            -          -             -         -
 12          -          -            -          -             -         -
 13          -      13.80            -          -             -         -
 14      13.08      17.50        18.66          -         13.99     20.20
 15          -          -            -          -             -         -
 16          -          -            -          -             -         -
 17          -          -        20.23          -             -         -
 18          -          -        19.62          -             -     20.20
 19          -      19.51        22.14          -         13.36         -
 20      13.08      17.30        17.34          -         17.98         -
 21      27.22      28.85        23.61      24.39         20.89     23.56
 22          -          -            -          -             -         -
 23          -      65.93            -          -         27.43         -
 24      27.86          -        28.67      36.38         22.84     25.18
 25      27.40      64.74        25.34      34.54         22.15     21.77
 26      32.06      34.95        27.08      30.31         23.38     26.35
 27      26.89      27.85        22.45      23.18         20.11     23.53
 28      40.70      45.58        35.99      31.79         30.14     30.37
 29          -          -            -          -             -         -
 30          -          -            -          -             -         -
 31          -          -            -          -             -         -
 32      49.76      65.89            -      41.75         33.66         -
 33      47.69          -        57.61      42.69         34.45     27.52
 34      44.14      66.98        40.91      41.54         41.54     47.32
 35      44.49      49.95        40.95      36.47         37.82     42.71
 36      39.24      45.14        33.82      30.83         25.61     29.28
 37      38.91      43.18        40.51      24.05         26.74     20.55
 38          -          -            -          -             -         -
 39          -          -            -          -             -         -
 40          -          -            -          -             -         -
 41      52.96      37.92        47.88      40.26         44.72     54.65
 42      37.50      43.64        39.51      22.60         20.99     18.64
 43      75.34      73.07        72.26      79.59         77.09     67.29
 44          -      16.85            -          -         13.14         -
 45          -      16.85            -          -         13.14         -

    Promedio
 0         -
 1         -
 2         -
 3         -
 4         -
 5         -
 6         -
 7     13.80
 8         -
 9         -
 10        -
 11        -
 12        -
 13    13.80
 14    16.83
 15        -
 16    79.73
 17    20.27
 18    19.67
 19    16.97
 20    16.40
 21    23.18
 22        -
 23    27.84
 24    24.62
 25    25.14
 26    27.41
 27    22.57
 28    33.43
 29    29.60
 30        -
 31    21.12
 32    46.56
 33    38.36
 34    39.84
 35    38.67
 36    32.36
 37    30.66
 38        -
 39        -
 40        -
 41    38.55
 42    29.38
 43    73.90
 44    14.45
 45    14.45  ]

In [6]:
# Dropdown button list
dropdown_button_year = driver.find_element( By.ID, "ctl00_cphContent_rAnio")
dropdown_button_year.click()

# List of years options
list_year = driver.find_element( By.ID,  "ctl00_cphContent_rAnio_DropDown" )
years_list = list_year.find_elements( By.TAG_NAME, 'li')
list_year_options = len(years_list)

# Dropdown button list
dropdown_button_month = driver.find_element( By.ID,  "ctl00_cphContent_rMes")
dropdown_button_month.click()

# # List of months options
list_month = driver.find_element( By.ID,  "ctl00_cphContent_rMes_DropDown" )
months_list = list_month.find_elements( By.TAG_NAME, 'li')
list_month_options = len(months_list)

driver.find_element( By.ID, "ctl00_cphContent_btnConsultaMensual").click()
driver.get("https://www.sbs.gob.pe/app/pp/EstadisticasSAEEPortal/Paginas/TIActivaTipoCreditoEmpresa.aspx?tip=C")

In [7]:
list_year_options

22

In [8]:
list_month_options

12

In [9]:
year_numbers_opt = np.array( [1, 0 ] + np.arange(2, list_year_options).tolist() )
month_numbers_opt = np.array( [1, 0 ] + np.arange(2, list_month_options).tolist() )

In [10]:
print(year_numbers_opt)
print(month_numbers_opt)

[ 1  0  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21]
[ 1  0  2  3  4  5  6  7  8  9 10 11]

In [11]:
month_numbers_opt2 = np.array(list(range(1, 13)))
year_numbers_opt2 = np.array(list(range(1, 23)))

In [12]:
month_numbers_opt3 = np.array([1] + list(range(1, list_month_options)))

In [13]:
print(month_numbers_opt3)
print(year_numbers_opt2)

[ 1  1  2  3  4  5  6  7  8  9 10 11]
[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22]

In [14]:
type(year_numbers_opt2)

numpy.ndarray

In [15]:
years_info_list = []
months_info_list = []
tables_info_list = []

for year_number in year_numbers_opt[0:22]:
    
    # Dropdown button list
    dropdown_button_year = driver.find_element( By.ID, "ctl00_cphContent_rAnio") 
    dropdown_button_year.click()

    # List of years options
    time.sleep(3)
    driver.find_element( By.XPATH,  f"/html/body/form/div[1]/div/ul/li[{year_number + 1 }]" ).click()
    year_text = driver.find_element( By.ID, "ctl00_cphContent_rAnio").text

    
        
    for month_number in month_numbers_opt[0:12]:
        
        # Dropdown button list
        dropdown_button_month = driver.find_element( By.ID, "ctl00_cphContent_rMes") 
        dropdown_button_month.click()
        
         # # List of months options
        time.sleep(2)
        driver.find_element( By.XPATH,  f"/html/body/form/div[1]/div/ul/li[{month_number + 1 }]" ).click()
        month_text = driver.find_element( By.ID, "ctl00_cphContent_rMes").text
        print( year_text )
        print( month_text )
        
        # Click consultar
        driver.find_element( By.ID,"ctl00_cphContent_btnConsultaMensual").click()
        time.sleep(5)
        
        year_float = int(year_text)
        
        try:
            # Switch elements
            driver.switch_to.frame(driver.find_element( By.ID,"ctl00_cphContent_pnContenidoAnteriorMnASP"))
            section_tab_table = driver.find_element( By.XPATH,  "/html/body/form/table/tbody" )
            table_html = section_tab_table.get_attribute('outerHTML')
            table_pd = pd.read_html( table_html )

            # Cleaning table
            table_clean_1 = table_pd[1].iloc[5:, :].copy().reset_index( drop = True )
            
            # Changing switch
            driver.switch_to.default_content()

            print("Table Tipo 1 - Cambiar de Frame y una tabla simple")

        except:
            print("No table Tipo 1")
            table_clean_1 = "Null"
            
            
        try:
            # Switch elements
            driver.switch_to.frame(driver.find_element( By.ID,"ctl00_cphContent_pnContenidoAnteriorMnASP"))
            section_tab_table = driver.find_element( By.XPATH,  "/html/body/form/table/tbody" )
            table_html = section_tab_table.get_attribute('outerHTML')
            table_pd = pd.read_html( table_html )

            # generate table objects
            table0, table1 = table_pd[0], table_pd[1]
            table_clean_2 = table1.copy()

            # Number of rows of second table
            tb1_rows = table1.shape[0]
            drop_rows = np.arange( 1, tb1_rows + 2 )

            # Clean first table
            table0 = table0.drop( drop_rows, axis = 0 )

            # Assign values to new table
            col_name = table0.iloc[0, 0]
            col_values = table0.iloc[1:, 0].tolist()
            table_clean_2.insert( loc = 0, column= col_name, value = col_values)
            
            print("Table Tipo 2 - Cambiar de Frame y una tabla Compleja")
            
             # Changing switch
            driver.switch_to.default_content()
            
        except:
            print("No table Tipo 2")
            table_clean_2 = "Null"
            

        try:
            # Get tables
            section_id_table = driver.find_element( By.ID, "ctl00_cphContent_rpgActualMn_OT" )
            table_html = section_id_table.get_attribute('outerHTML')
            table_pd = pd.read_html( table_html )

            # generate table objects
            table0, table1 = table_pd[0], table_pd[1]
            table_clean_3 = table1.copy()

            # Number of rows of second table
            tb1_rows = table1.shape[0]
            drop_rows = np.arange( 1, tb1_rows + 2 )

            # Clean first table
            table0 = table0.drop( drop_rows, axis = 0 )
            
            # Assign values to new table
            col_name = table0.iloc[0, 0]
            col_values = table0.iloc[1:, 0].tolist()
            table_clean_3.insert( loc = 0, column= col_name, value = col_values)
            
            print("Table Tipo 3 - No Cambiar de Frame y una tabla Compleja")
            
        except:
            print("No table Tipo 3")
            table_clean_3 = "Null"
            
            
        # Check what to save
        if ( ( isinstance( table_clean_3, str ) == False ) and ( table_clean_3.shape[1] > 5 ) ):
            
             # Data with no frame
                        
            table_clean_3.to_excel( fr"C:\Users\XIMENA\OneDrive\Documentos\QLAB_Summer_Python\assignments\assignment_5\group_5_ass_5_2023\tables_{year_text}_{month_text}.xlsx", index = False , header = False )
            
            years_info_list.append( year_float)
            months_info_list.append( month_text )
            tables_info_list.append( "Table 3" )
            print("guardo3")
            
        elif ( ( isinstance( table_clean_2, str ) == False ) and ( table_clean_2.shape[1] > 5 ) ):
            
            # Save to excel in folder where the script is located
            table_clean_2.to_excel( fr"C:\Users\XIMENA\OneDrive\Documentos\QLAB_Summer_Python\assignments\assignment_5\group_5_ass_5_2023\tables_{year_text}_{month_text}.xlsx", index = False , header = False )
            # To break
            years_info_list.append( year_float)
            months_info_list.append( month_text )
            tables_info_list.append( "Table 2" )
            print("guardo2")
            
        elif ( ( isinstance( table_clean_1, str ) == False ) and ( table_clean_1.shape[1] > 5 ) ):
            # Save to excel in folder where the script is located
            table_clean_1.to_excel( fr"C:\Users\XIMENA\OneDrive\Documentos\QLAB_Summer_Python\assignments\assignment_5\group_5_ass_5_2023\tables_{year_text}_{month_text}.xlsx", index = False , header = False )
            
            years_info_list.append( year_float)
            months_info_list.append( month_text )
            tables_info_list.append( "Table 1" )
            print("guardo1")
            
        # No table information
        # Go to a previous day
        else:
            # Day ago
            years_info_list.append( year_float)
            months_info_list.append( month_text )
            tables_info_list.append( "No Table" )
            
        driver.switch_to.default_content()

2022
Febrero
No table Tipo 1
No table Tipo 2
Table Tipo 3 - No Cambiar de Frame y una tabla Compleja
guardo3
2022
Enero
No table Tipo 1
No table Tipo 2
Table Tipo 3 - No Cambiar de Frame y una tabla Compleja
guardo3
2022
Marzo
No table Tipo 1
No table Tipo 2
Table Tipo 3 - No Cambiar de Frame y una tabla Compleja
guardo3
2022
Abril
No table Tipo 1
No table Tipo 2
Table Tipo 3 - No Cambiar de Frame y una tabla Compleja
guardo3
2022
Mayo
No table Tipo 1
No table Tipo 2
Table Tipo 3 - No Cambiar de Frame y una tabla Compleja
guardo3
2022
Junio
No table Tipo 1
No table Tipo 2
Table Tipo 3 - No Cambiar de Frame y una tabla Compleja
guardo3
2022
Julio
No table Tipo 1
No table Tipo 2
Table Tipo 3 - No Cambiar de Frame y una tabla Compleja
guardo3
2022
Agosto
No table Tipo 1
No table Tipo 2
Table Tipo 3 - No Cambiar de Frame y una tabla Compleja
guardo3
2022
Setiembre
No table Tipo 1
No table Tipo 2
Table Tipo 3 - No Cambiar de Frame y una tabla Compleja
guardo3
2022
Octubre
No table Tipo 1
No table Tipo 2
Table Tipo 3 - No Cambiar de Frame y una tabla Compleja
guardo3
2022
Noviembre
No table Tipo 1
No table Tipo 2
Table Tipo 3 - No Cambiar de Frame y una tabla Compleja
guardo3
2022
Diciembre
No table Tipo 1
No table Tipo 2
Table Tipo 3 - No Cambiar de Frame y una tabla Compleja
guardo3
2023
Febrero
No table Tipo 1
No table Tipo 2
No table Tipo 3
2023
Enero
No table Tipo 1
No table Tipo 2
Table Tipo 3 - No Cambiar de Frame y una tabla Compleja
guardo3
2023
Marzo
No table Tipo 1
No table Tipo 2
No table Tipo 3
2023
Abril
No table Tipo 1
No table Tipo 2
No table Tipo 3
2023
Mayo
No table Tipo 1
No table Tipo 2
No table Tipo 3
2023
Junio
No table Tipo 1
No table Tipo 2
No table Tipo 3
2023
Julio
No table Tipo 1
No table Tipo 2
No table Tipo 3
2023
Agosto
No table Tipo 1
No table Tipo 2
No table Tipo 3
2023
Setiembre
No table Tipo 1
No table Tipo 2
No table Tipo 3
2023
Octubre
No table Tipo 1
No table Tipo 2
No table Tipo 3
2023
Noviembre
No table Tipo 1
No table Tipo 2
No table Tipo 3
2023
Diciembre
No table Tipo 1
No table Tipo 2
No table Tipo 3
2021
Febrero
No table Tipo 1
No table Tipo 2
Table Tipo 3 - No Cambiar de Frame y una tabla Compleja
guardo3
2021
Enero
No table Tipo 1
No table Tipo 2
Table Tipo 3 - No Cambiar de Frame y una tabla Compleja
guardo3
2021
Marzo
No table Tipo 1
No table Tipo 2
Table Tipo 3 - No Cambiar de Frame y una tabla Compleja
guardo3
2021
Abril
No table Tipo 1
No table Tipo 2
Table Tipo 3 - No Cambiar de Frame y una tabla Compleja
guardo3
2021
Mayo
No table Tipo 1
No table Tipo 2
Table Tipo 3 - No Cambiar de Frame y una tabla Compleja
guardo3
2021
Junio
No table Tipo 1
No table Tipo 2
Table Tipo 3 - No Cambiar de Frame y una tabla Compleja
guardo3
2021
Julio
No table Tipo 1
No table Tipo 2
Table Tipo 3 - No Cambiar de Frame y una tabla Compleja
guardo3
2021
Agosto
No table Tipo 1
No table Tipo 2
Table Tipo 3 - No Cambiar de Frame y una tabla Compleja
guardo3
2021
Setiembre
No table Tipo 1
No table Tipo 2
Table Tipo 3 - No Cambiar de Frame y una tabla Compleja
guardo3
2021
Octubre
No table Tipo 1
No table Tipo 2
Table Tipo 3 - No Cambiar de Frame y una tabla Compleja
guardo3
2021
Noviembre
No table Tipo 1
No table Tipo 2
Table Tipo 3 - No Cambiar de Frame y una tabla Compleja
guardo3
2021
Diciembre
No table Tipo 1
No table Tipo 2
Table Tipo 3 - No Cambiar de Frame y una tabla Compleja
guardo3
2020
Febrero
No table Tipo 1
No table Tipo 2
Table Tipo 3 - No Cambiar de Frame y una tabla Compleja
guardo3
2020
Enero
No table Tipo 1
No table Tipo 2
Table Tipo 3 - No Cambiar de Frame y una tabla Compleja
guardo3
2020
Marzo
No table Tipo 1
No table Tipo 2
Table Tipo 3 - No Cambiar de Frame y una tabla Compleja
guardo3
2020
Abril
No table Tipo 1
No table Tipo 2
Table Tipo 3 - No Cambiar de Frame y una tabla Compleja
guardo3
2020
Mayo
No table Tipo 1
No table Tipo 2
Table Tipo 3 - No Cambiar de Frame y una tabla Compleja
guardo3
2020
Junio
No table Tipo 1
No table Tipo 2
Table Tipo 3 - No Cambiar de Frame y una tabla Compleja
guardo3
2020
Julio
No table Tipo 1
No table Tipo 2
Table Tipo 3 - No Cambiar de Frame y una tabla Compleja
guardo3
2020
Agosto
No table Tipo 1
No table Tipo 2
Table Tipo 3 - No Cambiar de Frame y una tabla Compleja
guardo3
2020
Setiembre
No table Tipo 1
No table Tipo 2
Table Tipo 3 - No Cambiar de Frame y una tabla Compleja
guardo3
2020
Octubre
No table Tipo 1
No table Tipo 2
Table Tipo 3 - No Cambiar de Frame y una tabla Compleja
guardo3
2020
Noviembre
No table Tipo 1
No table Tipo 2
Table Tipo 3 - No Cambiar de Frame y una tabla Compleja
guardo3
2020
Diciembre
No table Tipo 1
No table Tipo 2
Table Tipo 3 - No Cambiar de Frame y una tabla Compleja
guardo3
2019
Febrero
No table Tipo 1
No table Tipo 2
Table Tipo 3 - No Cambiar de Frame y una tabla Compleja
guardo3
2019
Enero
No table Tipo 1
No table Tipo 2
Table Tipo 3 - No Cambiar de Frame y una tabla Compleja
guardo3
2019
Marzo
No table Tipo 1
No table Tipo 2
Table Tipo 3 - No Cambiar de Frame y una tabla Compleja
guardo3
2019
Abril
No table Tipo 1
No table Tipo 2
Table Tipo 3 - No Cambiar de Frame y una tabla Compleja
guardo3
2019
Mayo
No table Tipo 1
No table Tipo 2
Table Tipo 3 - No Cambiar de Frame y una tabla Compleja
guardo3
2019
Junio
No table Tipo 1
No table Tipo 2
Table Tipo 3 - No Cambiar de Frame y una tabla Compleja
guardo3
2019
Julio
No table Tipo 1
No table Tipo 2
Table Tipo 3 - No Cambiar de Frame y una tabla Compleja
guardo3
2019
Agosto
No table Tipo 1
No table Tipo 2
Table Tipo 3 - No Cambiar de Frame y una tabla Compleja
guardo3
2019
Setiembre
No table Tipo 1
No table Tipo 2
Table Tipo 3 - No Cambiar de Frame y una tabla Compleja
guardo3
2019
Octubre
No table Tipo 1
No table Tipo 2
Table Tipo 3 - No Cambiar de Frame y una tabla Compleja
guardo3
2019
Noviembre
No table Tipo 1
No table Tipo 2
Table Tipo 3 - No Cambiar de Frame y una tabla Compleja
guardo3
2019
Diciembre
No table Tipo 1
No table Tipo 2
Table Tipo 3 - No Cambiar de Frame y una tabla Compleja
guardo3
2018
Febrero
No table Tipo 1
No table Tipo 2
Table Tipo 3 - No Cambiar de Frame y una tabla Compleja
guardo3
2018
Enero
No table Tipo 1
No table Tipo 2
Table Tipo 3 - No Cambiar de Frame y una tabla Compleja
guardo3
2018
Marzo
No table Tipo 1
No table Tipo 2
Table Tipo 3 - No Cambiar de Frame y una tabla Compleja
guardo3
2018
Abril
No table Tipo 1
No table Tipo 2
Table Tipo 3 - No Cambiar de Frame y una tabla Compleja
guardo3
2018
Mayo
No table Tipo 1
No table Tipo 2
Table Tipo 3 - No Cambiar de Frame y una tabla Compleja
guardo3
2018
Junio
No table Tipo 1
No table Tipo 2
Table Tipo 3 - No Cambiar de Frame y una tabla Compleja
guardo3
2018
Julio
No table Tipo 1
No table Tipo 2
Table Tipo 3 - No Cambiar de Frame y una tabla Compleja
guardo3
2018
Agosto
No table Tipo 1
No table Tipo 2
Table Tipo 3 - No Cambiar de Frame y una tabla Compleja
guardo3
2018
Setiembre
No table Tipo 1
No table Tipo 2
Table Tipo 3 - No Cambiar de Frame y una tabla Compleja
guardo3
2018
Octubre
No table Tipo 1
No table Tipo 2
Table Tipo 3 - No Cambiar de Frame y una tabla Compleja
guardo3
2018
Noviembre
No table Tipo 1
No table Tipo 2
Table Tipo 3 - No Cambiar de Frame y una tabla Compleja
guardo3
2018
Diciembre
No table Tipo 1
No table Tipo 2
Table Tipo 3 - No Cambiar de Frame y una tabla Compleja
guardo3
2017
Febrero
No table Tipo 1
No table Tipo 2
Table Tipo 3 - No Cambiar de Frame y una tabla Compleja
guardo3
2017
Enero
No table Tipo 1
No table Tipo 2
Table Tipo 3 - No Cambiar de Frame y una tabla Compleja
guardo3
2017
Marzo
No table Tipo 1
No table Tipo 2
Table Tipo 3 - No Cambiar de Frame y una tabla Compleja
guardo3
2017
Abril
No table Tipo 1
No table Tipo 2
Table Tipo 3 - No Cambiar de Frame y una tabla Compleja
guardo3
2017
Mayo
No table Tipo 1
No table Tipo 2
Table Tipo 3 - No Cambiar de Frame y una tabla Compleja
guardo3
2017
Junio
No table Tipo 1
No table Tipo 2
Table Tipo 3 - No Cambiar de Frame y una tabla Compleja
guardo3
2017
Julio
No table Tipo 1
No table Tipo 2
Table Tipo 3 - No Cambiar de Frame y una tabla Compleja
guardo3
2017
Agosto
No table Tipo 1
No table Tipo 2
Table Tipo 3 - No Cambiar de Frame y una tabla Compleja
guardo3
2017
Setiembre
No table Tipo 1
No table Tipo 2
Table Tipo 3 - No Cambiar de Frame y una tabla Compleja

guardo3
2017
Octubre
No table Tipo 1
No table Tipo 2
Table Tipo 3 - No Cambiar de Frame y una tabla Compleja
guardo3
2017
Noviembre
No table Tipo 1
No table Tipo 2
Table Tipo 3 - No Cambiar de Frame y una tabla Compleja
guardo3
2017
Diciembre
No table Tipo 1
No table Tipo 2
Table Tipo 3 - No Cambiar de Frame y una tabla Compleja
guardo3
2016
Febrero
No table Tipo 1
No table Tipo 2
Table Tipo 3 - No Cambiar de Frame y una tabla Compleja
guardo3
2016
Enero
No table Tipo 1
No table Tipo 2
Table Tipo 3 - No Cambiar de Frame y una tabla Compleja
guardo3
2016
Marzo
No table Tipo 1
No table Tipo 2
Table Tipo 3 - No Cambiar de Frame y una tabla Compleja
guardo3
2016
Abril
No table Tipo 1
No table Tipo 2
Table Tipo 3 - No Cambiar de Frame y una tabla Compleja
guardo3
2016
Mayo
No table Tipo 1
No table Tipo 2
Table Tipo 3 - No Cambiar de Frame y una tabla Compleja
guardo3
2016
Junio
No table Tipo 1
No table Tipo 2
Table Tipo 3 - No Cambiar de Frame y una tabla Compleja
guardo3
2016
Julio
No table Tipo 1
No table Tipo 2
Table Tipo 3 - No Cambiar de Frame y una tabla Compleja
guardo3
2016
Agosto
No table Tipo 1
No table Tipo 2
Table Tipo 3 - No Cambiar de Frame y una tabla Compleja
guardo3
2016
Setiembre
No table Tipo 1
No table Tipo 2
Table Tipo 3 - No Cambiar de Frame y una tabla Compleja
guardo3
2016
Octubre
No table Tipo 1
No table Tipo 2
Table Tipo 3 - No Cambiar de Frame y una tabla Compleja
guardo3
2016
Noviembre
No table Tipo 1
No table Tipo 2
Table Tipo 3 - No Cambiar de Frame y una tabla Compleja
guardo3
2016
Diciembre
No table Tipo 1
No table Tipo 2
Table Tipo 3 - No Cambiar de Frame y una tabla Compleja
guardo3
2015
Febrero
Table Tipo 1 - Cambiar de Frame y una tabla simple
No table Tipo 2
No table Tipo 3
guardo1
2015
Enero
Table Tipo 1 - Cambiar de Frame y una tabla simple
No table Tipo 2
No table Tipo 3
guardo1
2015
Marzo
Table Tipo 1 - Cambiar de Frame y una tabla simple
No table Tipo 2
No table Tipo 3
guardo1
2015
Abril
Table Tipo 1 - Cambiar de Frame y una tabla simple
No table Tipo 2
No table Tipo 3
guardo1
2015
Mayo
Table Tipo 1 - Cambiar de Frame y una tabla simple
No table Tipo 2
No table Tipo 3
guardo1
2015
Junio
Table Tipo 1 - Cambiar de Frame y una tabla simple
No table Tipo 2
No table Tipo 3
guardo1
2015
Julio
Table Tipo 1 - Cambiar de Frame y una tabla simple
No table Tipo 2
No table Tipo 3
guardo1
2015
Agosto
Table Tipo 1 - Cambiar de Frame y una tabla simple
No table Tipo 2
No table Tipo 3
guardo1
2015
Setiembre
Table Tipo 1 - Cambiar de Frame y una tabla simple
No table Tipo 2
No table Tipo 3
guardo1
2015
Octubre
No table Tipo 1
No table Tipo 2
Table Tipo 3 - No Cambiar de Frame y una tabla Compleja
guardo3
2015
Noviembre
No table Tipo 1
No table Tipo 2
Table Tipo 3 - No Cambiar de Frame y una tabla Compleja
guardo3
2015
Diciembre
No table Tipo 1
No table Tipo 2
Table Tipo 3 - No Cambiar de Frame y una tabla Compleja
guardo3
2014
Febrero
Table Tipo 1 - Cambiar de Frame y una tabla simple
No table Tipo 2
No table Tipo 3
guardo1
2014
Enero
Table Tipo 1 - Cambiar de Frame y una tabla simple
No table Tipo 2
No table Tipo 3
guardo1
2014
Marzo
Table Tipo 1 - Cambiar de Frame y una tabla simple
No table Tipo 2
No table Tipo 3
guardo1
2014
Abril
Table Tipo 1 - Cambiar de Frame y una tabla simple
No table Tipo 2
No table Tipo 3
guardo1
2014
Mayo
Table Tipo 1 - Cambiar de Frame y una tabla simple
No table Tipo 2
No table Tipo 3
guardo1
2014
Junio
Table Tipo 1 - Cambiar de Frame y una tabla simple
No table Tipo 2
No table Tipo 3
guardo1
2014
Julio
Table Tipo 1 - Cambiar de Frame y una tabla simple
No table Tipo 2
No table Tipo 3
guardo1
2014
Agosto
Table Tipo 1 - Cambiar de Frame y una tabla simple
No table Tipo 2
No table Tipo 3
guardo1
2014
Setiembre
Table Tipo 1 - Cambiar de Frame y una tabla simple
No table Tipo 2
No table Tipo 3
guardo1
2014
Octubre
Table Tipo 1 - Cambiar de Frame y una tabla simple
No table Tipo 2
No table Tipo 3
guardo1
2014
Noviembre
Table Tipo 1 - Cambiar de Frame y una tabla simple
No table Tipo 2
No table Tipo 3
guardo1
2014
Diciembre
Table Tipo 1 - Cambiar de Frame y una tabla simple
No table Tipo 2
No table Tipo 3
guardo1
2013
Febrero
Table Tipo 1 - Cambiar de Frame y una tabla simple
No table Tipo 2
No table Tipo 3
guardo1
2013
Enero
Table Tipo 1 - Cambiar de Frame y una tabla simple
No table Tipo 2
No table Tipo 3
guardo1
2013
Marzo
Table Tipo 1 - Cambiar de Frame y una tabla simple
No table Tipo 2
No table Tipo 3
guardo1
2013
Abril
Table Tipo 1 - Cambiar de Frame y una tabla simple
No table Tipo 2
No table Tipo 3
guardo1
2013
Mayo
Table Tipo 1 - Cambiar de Frame y una tabla simple
No table Tipo 2
No table Tipo 3
guardo1
2013
Junio
Table Tipo 1 - Cambiar de Frame y una tabla simple
No table Tipo 2
No table Tipo 3
guardo1
2013
Julio
Table Tipo 1 - Cambiar de Frame y una tabla simple
No table Tipo 2
No table Tipo 3
guardo1
2013
Agosto
Table Tipo 1 - Cambiar de Frame y una tabla simple
No table Tipo 2
No table Tipo 3
guardo1
2013
Setiembre
Table Tipo 1 - Cambiar de Frame y una tabla simple
No table Tipo 2
No table Tipo 3
guardo1
2013
Octubre
Table Tipo 1 - Cambiar de Frame y una tabla simple
No table Tipo 2
No table Tipo 3
guardo1
2013
Noviembre
Table Tipo 1 - Cambiar de Frame y una tabla simple
No table Tipo 2
No table Tipo 3
guardo1
2013
Diciembre
Table Tipo 1 - Cambiar de Frame y una tabla simple
No table Tipo 2
No table Tipo 3
guardo1
2012
Febrero
Table Tipo 1 - Cambiar de Frame y una tabla simple
No table Tipo 2
No table Tipo 3
guardo1
2012
Enero
Table Tipo 1 - Cambiar de Frame y una tabla simple
No table Tipo 2
No table Tipo 3
guardo1
2012
Marzo
Table Tipo 1 - Cambiar de Frame y una tabla simple
No table Tipo 2
No table Tipo 3
guardo1
2012
Abril
Table Tipo 1 - Cambiar de Frame y una tabla simple
No table Tipo 2
No table Tipo 3
guardo1
2012
Mayo
Table Tipo 1 - Cambiar de Frame y una tabla simple
No table Tipo 2
No table Tipo 3
guardo1
2012
Junio
Table Tipo 1 - Cambiar de Frame y una tabla simple
No table Tipo 2
No table Tipo 3
guardo1
2012
Julio
Table Tipo 1 - Cambiar de Frame y una tabla simple
No table Tipo 2
No table Tipo 3
guardo1
2012
Agosto
Table Tipo 1 - Cambiar de Frame y una tabla simple
No table Tipo 2
No table Tipo 3
guardo1
2012
Setiembre
Table Tipo 1 - Cambiar de Frame y una tabla simple
No table Tipo 2
No table Tipo 3
guardo1
2012
Octubre
Table Tipo 1 - Cambiar de Frame y una tabla simple
No table Tipo 2
No table Tipo 3
guardo1
2012
Noviembre
Table Tipo 1 - Cambiar de Frame y una tabla simple
No table Tipo 2
No table Tipo 3
guardo1
2012
Diciembre
Table Tipo 1 - Cambiar de Frame y una tabla simple
No table Tipo 2
No table Tipo 3
guardo1
2011
Febrero
Table Tipo 1 - Cambiar de Frame y una tabla simple
No table Tipo 2
No table Tipo 3
guardo1
2011
Enero
Table Tipo 1 - Cambiar de Frame y una tabla simple
No table Tipo 2
No table Tipo 3
guardo1
2011
Marzo
Table Tipo 1 - Cambiar de Frame y una tabla simple
No table Tipo 2
No table Tipo 3
guardo1
2011
Abril
Table Tipo 1 - Cambiar de Frame y una tabla simple
No table Tipo 2
No table Tipo 3
guardo1
2011
Mayo
Table Tipo 1 - Cambiar de Frame y una tabla simple
No table Tipo 2
No table Tipo 3
guardo1
2011
Junio
Table Tipo 1 - Cambiar de Frame y una tabla simple
No table Tipo 2
No table Tipo 3
guardo1
2011
Julio
Table Tipo 1 - Cambiar de Frame y una tabla simple
No table Tipo 2
No table Tipo 3
guardo1
2011
Agosto
Table Tipo 1 - Cambiar de Frame y una tabla simple
No table Tipo 2
No table Tipo 3
guardo1
2011
Setiembre
Table Tipo 1 - Cambiar de Frame y una tabla simple
No table Tipo 2
No table Tipo 3
guardo1
2011
Octubre
Table Tipo 1 - Cambiar de Frame y una tabla simple
No table Tipo 2
No table Tipo 3
guardo1
2011
Noviembre
Table Tipo 1 - Cambiar de Frame y una tabla simple
No table Tipo 2
No table Tipo 3
guardo1
2011
Diciembre
Table Tipo 1 - Cambiar de Frame y una tabla simple
No table Tipo 2
No table Tipo 3
guardo1
2010
Febrero
Table Tipo 1 - Cambiar de Frame y una tabla simple
No table Tipo 2
No table Tipo 3
guardo1
2010
Enero
Table Tipo 1 - Cambiar de Frame y una tabla simple
No table Tipo 2
No table Tipo 3
guardo1
2010
Marzo
Table Tipo 1 - Cambiar de Frame y una tabla simple
No table Tipo 2
No table Tipo 3
guardo1
2010
Abril
Table Tipo 1 - Cambiar de Frame y una tabla simple
No table Tipo 2
No table Tipo 3

guardo1
2010
Mayo
Table Tipo 1 - Cambiar de Frame y una tabla simple
No table Tipo 2
No table Tipo 3
guardo1
2010
Junio
Table Tipo 1 - Cambiar de Frame y una tabla simple
No table Tipo 2
No table Tipo 3
guardo1
2010
Julio
Table Tipo 1 - Cambiar de Frame y una tabla simple
No table Tipo 2
No table Tipo 3
guardo1
2010
Agosto
Table Tipo 1 - Cambiar de Frame y una tabla simple
No table Tipo 2
No table Tipo 3
guardo1
2010
Setiembre
Table Tipo 1 - Cambiar de Frame y una tabla simple
No table Tipo 2
No table Tipo 3
guardo1
2010
Octubre
Table Tipo 1 - Cambiar de Frame y una tabla simple
No table Tipo 2
No table Tipo 3
guardo1
2010
Noviembre
Table Tipo 1 - Cambiar de Frame y una tabla simple
No table Tipo 2
No table Tipo 3
guardo1
2010
Diciembre
Table Tipo 1 - Cambiar de Frame y una tabla simple
No table Tipo 2
No table Tipo 3
guardo1
2009
Febrero
Table Tipo 1 - Cambiar de Frame y una tabla simple
No table Tipo 2
No table Tipo 3
guardo1
2009
Enero
Table Tipo 1 - Cambiar de Frame y una tabla simple
No table Tipo 2
No table Tipo 3
guardo1
2009
Marzo
Table Tipo 1 - Cambiar de Frame y una tabla simple
No table Tipo 2
No table Tipo 3
guardo1
2009
Abril
Table Tipo 1 - Cambiar de Frame y una tabla simple
No table Tipo 2
No table Tipo 3
guardo1
2009
Mayo
Table Tipo 1 - Cambiar de Frame y una tabla simple
No table Tipo 2
No table Tipo 3
guardo1
2009
Junio
Table Tipo 1 - Cambiar de Frame y una tabla simple
No table Tipo 2
No table Tipo 3
guardo1
2009
Julio
Table Tipo 1 - Cambiar de Frame y una tabla simple
No table Tipo 2
No table Tipo 3
guardo1
2009
Agosto
Table Tipo 1 - Cambiar de Frame y una tabla simple
No table Tipo 2
No table Tipo 3
guardo1
2009
Setiembre
Table Tipo 1 - Cambiar de Frame y una tabla simple
No table Tipo 2
No table Tipo 3
guardo1
2009
Octubre
Table Tipo 1 - Cambiar de Frame y una tabla simple
No table Tipo 2
No table Tipo 3
guardo1
2009
Noviembre
Table Tipo 1 - Cambiar de Frame y una tabla simple
No table Tipo 2
No table Tipo 3
guardo1
2009
Diciembre
Table Tipo 1 - Cambiar de Frame y una tabla simple
No table Tipo 2
No table Tipo 3
guardo1
2008
Febrero
Table Tipo 1 - Cambiar de Frame y una tabla simple
No table Tipo 2
No table Tipo 3
guardo1
2008
Enero
Table Tipo 1 - Cambiar de Frame y una tabla simple
No table Tipo 2
No table Tipo 3
guardo1
2008
Marzo
Table Tipo 1 - Cambiar de Frame y una tabla simple
No table Tipo 2
No table Tipo 3
guardo1
2008
Abril
Table Tipo 1 - Cambiar de Frame y una tabla simple
No table Tipo 2
No table Tipo 3
guardo1
2008
Mayo
Table Tipo 1 - Cambiar de Frame y una tabla simple
No table Tipo 2
No table Tipo 3
guardo1
2008
Junio
Table Tipo 1 - Cambiar de Frame y una tabla simple
No table Tipo 2
No table Tipo 3
guardo1
2008
Julio
Table Tipo 1 - Cambiar de Frame y una tabla simple
No table Tipo 2
No table Tipo 3
guardo1
2008
Agosto
Table Tipo 1 - Cambiar de Frame y una tabla simple
No table Tipo 2
No table Tipo 3
guardo1
2008
Setiembre
Table Tipo 1 - Cambiar de Frame y una tabla simple
No table Tipo 2
No table Tipo 3
guardo1
2008
Octubre
Table Tipo 1 - Cambiar de Frame y una tabla simple
No table Tipo 2
No table Tipo 3
guardo1
2008
Noviembre
Table Tipo 1 - Cambiar de Frame y una tabla simple
No table Tipo 2
No table Tipo 3
guardo1
2008
Diciembre
Table Tipo 1 - Cambiar de Frame y una tabla simple
No table Tipo 2
No table Tipo 3
guardo1
2007
Febrero
Table Tipo 1 - Cambiar de Frame y una tabla simple
No table Tipo 2
No table Tipo 3
guardo1
2007
Enero
Table Tipo 1 - Cambiar de Frame y una tabla simple
No table Tipo 2
No table Tipo 3
guardo1
2007
Marzo
Table Tipo 1 - Cambiar de Frame y una tabla simple
No table Tipo 2
No table Tipo 3
guardo1
2007
Abril
Table Tipo 1 - Cambiar de Frame y una tabla simple
No table Tipo 2
No table Tipo 3
guardo1
2007
Mayo
Table Tipo 1 - Cambiar de Frame y una tabla simple
No table Tipo 2
No table Tipo 3
guardo1
2007
Junio
Table Tipo 1 - Cambiar de Frame y una tabla simple
No table Tipo 2
No table Tipo 3
guardo1
2007
Julio
Table Tipo 1 - Cambiar de Frame y una tabla simple
No table Tipo 2
No table Tipo 3
guardo1
2007
Agosto
Table Tipo 1 - Cambiar de Frame y una tabla simple
No table Tipo 2
No table Tipo 3
guardo1
2007
Setiembre
Table Tipo 1 - Cambiar de Frame y una tabla simple
No table Tipo 2
No table Tipo 3
guardo1
2007
Octubre
Table Tipo 1 - Cambiar de Frame y una tabla simple
No table Tipo 2
No table Tipo 3
guardo1
2007
Noviembre
Table Tipo 1 - Cambiar de Frame y una tabla simple
No table Tipo 2
No table Tipo 3
guardo1
2007
Diciembre
Table Tipo 1 - Cambiar de Frame y una tabla simple
No table Tipo 2
No table Tipo 3
guardo1
2006
Febrero
Table Tipo 1 - Cambiar de Frame y una tabla simple
No table Tipo 2
No table Tipo 3
guardo1
2006
Enero
Table Tipo 1 - Cambiar de Frame y una tabla simple
No table Tipo 2
No table Tipo 3
guardo1
2006
Marzo
Table Tipo 1 - Cambiar de Frame y una tabla simple
No table Tipo 2
No table Tipo 3
guardo1
2006
Abril
Table Tipo 1 - Cambiar de Frame y una tabla simple
No table Tipo 2
No table Tipo 3
guardo1
2006
Mayo
Table Tipo 1 - Cambiar de Frame y una tabla simple
No table Tipo 2
No table Tipo 3
guardo1
2006
Junio
Table Tipo 1 - Cambiar de Frame y una tabla simple
No table Tipo 2
No table Tipo 3
guardo1
2006
Julio
Table Tipo 1 - Cambiar de Frame y una tabla simple
No table Tipo 2
No table Tipo 3
guardo1
2006
Agosto
Table Tipo 1 - Cambiar de Frame y una tabla simple
No table Tipo 2
No table Tipo 3
guardo1
2006
Setiembre
Table Tipo 1 - Cambiar de Frame y una tabla simple
No table Tipo 2
No table Tipo 3
guardo1
2006
Octubre
Table Tipo 1 - Cambiar de Frame y una tabla simple
No table Tipo 2
No table Tipo 3
guardo1
2006
Noviembre
Table Tipo 1 - Cambiar de Frame y una tabla simple
No table Tipo 2
No table Tipo 3
guardo1
2006
Diciembre
Table Tipo 1 - Cambiar de Frame y una tabla simple
No table Tipo 2
No table Tipo 3
guardo1
2005
Febrero
Table Tipo 1 - Cambiar de Frame y una tabla simple
No table Tipo 2
No table Tipo 3
guardo1
2005
Enero
Table Tipo 1 - Cambiar de Frame y una tabla simple
No table Tipo 2
No table Tipo 3
guardo1
2005
Marzo
Table Tipo 1 - Cambiar de Frame y una tabla simple
No table Tipo 2
No table Tipo 3
guardo1
2005
Abril
Table Tipo 1 - Cambiar de Frame y una tabla simple
No table Tipo 2
No table Tipo 3
guardo1
2005
Mayo
Table Tipo 1 - Cambiar de Frame y una tabla simple
No table Tipo 2
No table Tipo 3
guardo1
2005
Junio
Table Tipo 1 - Cambiar de Frame y una tabla simple
No table Tipo 2
No table Tipo 3
guardo1
2005
Julio
Table Tipo 1 - Cambiar de Frame y una tabla simple
No table Tipo 2
No table Tipo 3
guardo1
2005
Agosto
Table Tipo 1 - Cambiar de Frame y una tabla simple
No table Tipo 2
No table Tipo 3
guardo1
2005
Setiembre
Table Tipo 1 - Cambiar de Frame y una tabla simple
No table Tipo 2
No table Tipo 3
guardo1
2005
Octubre
Table Tipo 1 - Cambiar de Frame y una tabla simple
No table Tipo 2
No table Tipo 3
guardo1
2005
Noviembre
Table Tipo 1 - Cambiar de Frame y una tabla simple
No table Tipo 2
No table Tipo 3
guardo1
2005
Diciembre
Table Tipo 1 - Cambiar de Frame y una tabla simple
No table Tipo 2
No table Tipo 3
guardo1
2004
Febrero
Table Tipo 1 - Cambiar de Frame y una tabla simple
No table Tipo 2
No table Tipo 3
guardo1
2004
Enero
Table Tipo 1 - Cambiar de Frame y una tabla simple
No table Tipo 2
No table Tipo 3
guardo1
2004
Marzo
Table Tipo 1 - Cambiar de Frame y una tabla simple
No table Tipo 2
No table Tipo 3
guardo1
2004
Abril
Table Tipo 1 - Cambiar de Frame y una tabla simple
No table Tipo 2
No table Tipo 3
guardo1
2004
Mayo
Table Tipo 1 - Cambiar de Frame y una tabla simple
No table Tipo 2
No table Tipo 3
guardo1
2004
Junio
Table Tipo 1 - Cambiar de Frame y una tabla simple
No table Tipo 2
No table Tipo 3
guardo1
2004
Julio
Table Tipo 1 - Cambiar de Frame y una tabla simple
No table Tipo 2
No table Tipo 3
guardo1
2004
Agosto
Table Tipo 1 - Cambiar de Frame y una tabla simple
No table Tipo 2
No table Tipo 3
guardo1
2004
Setiembre
Table Tipo 1 - Cambiar de Frame y una tabla simple
No table Tipo 2
No table Tipo 3
guardo1
2004
Octubre
Table Tipo 1 - Cambiar de Frame y una tabla simple
No table Tipo 2
No table Tipo 3
guardo1
2004
Noviembre
Table Tipo 1 - Cambiar de Frame y una tabla simple
No table Tipo 2
No table Tipo 3
guardo1
2004
Diciembre
Table Tipo 1 - Cambiar de Frame y una tabla simple
No table Tipo 2
No table Tipo 3
guardo1

2003
Febrero
Table Tipo 1 - Cambiar de Frame y una tabla simple
No table Tipo 2
No table Tipo 3
guardo1
2003
Enero
Table Tipo 1 - Cambiar de Frame y una tabla simple
No table Tipo 2
No table Tipo 3
guardo1
2003
Marzo
Table Tipo 1 - Cambiar de Frame y una tabla simple
No table Tipo 2
No table Tipo 3
guardo1
2003
Abril
Table Tipo 1 - Cambiar de Frame y una tabla simple
No table Tipo 2
No table Tipo 3
guardo1
2003
Mayo
Table Tipo 1 - Cambiar de Frame y una tabla simple
No table Tipo 2
No table Tipo 3
guardo1
2003
Junio
Table Tipo 1 - Cambiar de Frame y una tabla simple
No table Tipo 2
No table Tipo 3
guardo1
2003
Julio
Table Tipo 1 - Cambiar de Frame y una tabla simple
No table Tipo 2
No table Tipo 3
guardo1
2003
Agosto
Table Tipo 1 - Cambiar de Frame y una tabla simple
No table Tipo 2
No table Tipo 3
guardo1
2003
Setiembre
Table Tipo 1 - Cambiar de Frame y una tabla simple
No table Tipo 2
No table Tipo 3
guardo1
2003
Octubre
Table Tipo 1 - Cambiar de Frame y una tabla simple
No table Tipo 2
No table Tipo 3
guardo1
2003
Noviembre
Table Tipo 1 - Cambiar de Frame y una tabla simple
No table Tipo 2
No table Tipo 3
guardo1
2003
Diciembre
Table Tipo 1 - Cambiar de Frame y una tabla simple
No table Tipo 2
No table Tipo 3
guardo1
2002
Febrero
Table Tipo 1 - Cambiar de Frame y una tabla simple
No table Tipo 2
No table Tipo 3
2002
Enero
Table Tipo 1 - Cambiar de Frame y una tabla simple
No table Tipo 2
No table Tipo 3
2002
Marzo
Table Tipo 1 - Cambiar de Frame y una tabla simple
No table Tipo 2
No table Tipo 3
2002
Abril
Table Tipo 1 - Cambiar de Frame y una tabla simple
No table Tipo 2
No table Tipo 3
2002
Mayo
Table Tipo 1 - Cambiar de Frame y una tabla simple
No table Tipo 2
No table Tipo 3
2002
Junio
Table Tipo 1 - Cambiar de Frame y una tabla simple
No table Tipo 2
No table Tipo 3
2002
Julio
Table Tipo 1 - Cambiar de Frame y una tabla simple
No table Tipo 2
No table Tipo 3
2002
Agosto
Table Tipo 1 - Cambiar de Frame y una tabla simple
No table Tipo 2
No table Tipo 3
2002
Setiembre
Table Tipo 1 - Cambiar de Frame y una tabla simple
No table Tipo 2
No table Tipo 3
2002
Octubre
Table Tipo 1 - Cambiar de Frame y una tabla simple
No table Tipo 2
No table Tipo 3
guardo1
2002
Noviembre
Table Tipo 1 - Cambiar de Frame y una tabla simple
No table Tipo 2
No table Tipo 3
guardo1
2002
Diciembre
Table Tipo 1 - Cambiar de Frame y una tabla simple
No table Tipo 2
No table Tipo 3