# 1 Assignment 3

1. Generate a function named **beta_OLS**. This function must return the estimated beta using OLS. The inputs of this function should be `X`, `y`, and `intercept`. `X` (covariables) must be a **pd.DataFrame** and `y` (endog) must be a **pd.Series** and `intercept` can be `True` or `False`, by default `True`. When `intercept` is `False`, the estimated beta does not include **intercept**. Also, you must specify the type of your function's parameters and output and It must raise an error if the inputs do not meet the requirements. The function's output must be a **pd.DataFrame** (`n`, 1) where `n` is the total number of regressors ( it includes the **Intercept** when `intercept` is `True`). The column should be named as **Coef.** and the row index should be named as the original name of the columns in `X` input. Your results should look like `output_example` being `X_input`, `y_input` and `intercept_input` your inputs. Apply your function to find $\widehat{\boldsymbol{\beta}}^{(OLS)}$ of the equation below. Use greene data.  **Hint: Use NumPy to generate the OLS beta and check [this link](https://pandas.pydata.org/docs/reference/api/pandas.DataFrame.set_index.html) to change the index name of a pd.Dataframe, [link](https://notebooks.githubusercontent.com/view/ipynb?browser=chrome&color_mode=auto&commit=69c80e1f2c1c268f0480a32932262201785a576c&device=unknown_device&enc_url=68747470733a2f2f7261772e67697468756275736572636f6e74656e742e636f6d2f616c6578616e6465727175697370652f4469706c6f6d61646f5f505543502f363963383065316632633163323638663034383061333239333232363232303137383561353736632f4c6563747572655f352f4c6563747572655f352e6970796e62&logged_in=true&nwo=alexanderquispe%2FDiplomado_PUCP&path=Lecture_5%2FLecture_5.ipynb&platform=windows&repository_id=427747212&repository_type=Repository&version=96##5.1.7.).**

$$
\widehat{\boldsymbol{\beta}}^{(OLS)} = \left( \mathbf{X}^\top \mathbf{X}\right)^{-1} \mathbf{X}^\top \mathbf{Y}
$$

$$
\begin{aligned} 
lnCT &= \beta_{0}+\beta_{q}lnq+ \beta_{qq}(lnq)^2+\beta_{q1}lnqlnp_1+\beta_{q2}lnqlnp_2+ \beta_{q3}lnqlnp_{3} +\beta_{1}lnp_1+\beta_{2}lnp_2+ \beta_{3}lnp_3 \\
& + \beta_{11}(lnp_{1})^2+ \beta_{22}(lnp_{2})^2+ \beta_{33}(lnp_{3})^2 + \beta_{12}lnp_{1}lnp_{2}+ \beta_{13}lnp_{1}lnp_{3}+\beta_{23}lnp_{2}lnp_{3} 
\end{aligned}
$$

In [1]:
import tqdm
import pickle
import pandas as pd
import numpy as np
greene = pd.read_csv(r"../../_data/christensen_greene_f4.csv")

In [2]:
import statsmodels.formula.api as smf

In [3]:
results = smf.ols( 'np.log( COST ) ~ np.log( Q ) + np.log(PL)+ np.log(PF) + np.log(PK)', data = greene)

In [4]:
X_input = pd.DataFrame(results.exog, columns = results.exog_names).iloc[ : , 1: ]
y_input = pd.Series(results.endog , name = results.endog_names )
intercept_input = True

In [5]:
beta_OLS_output = results.fit().summary2().tables[1].iloc[ :, [0]]

In [6]:
beta_OLS_output

               Coef.
Intercept  -7.472227
np.log(Q)   0.838111
np.log(PL)  0.044258
np.log(PF)  0.713098
np.log(PK)  0.188449

In [7]:
y_input

0     -1.546463
1      1.112745
2      2.241337
3     -0.273648
4      0.814789
         ...
153    1.921222
154    1.324552
155    1.381834
156    3.407444
157    4.217391
Name: np.log(COST), Length: 158, dtype: float64

In [8]:
X_input

     np.log(Q)  np.log(PL)  np.log(PF)  np.log(PK)
0     2.079442    8.834842    2.890372    4.173541
1     6.767343    9.032763    3.047708    4.222840
2     7.252762    8.982297    3.726416    3.706032
3     4.174387    9.101852    3.351272    3.719481
4     5.686975    9.014131    3.668677    4.275832
..         ...         ...         ...         ...
153   6.852877    9.272579    3.940863    3.775057
154   5.932245    8.913583    3.509633    4.305685
155   5.968708    8.670093    3.798473    4.360394
156   8.578665    9.168125    3.733853    4.356811
157   9.630366    8.851676    3.245011    4.304403

[158 rows x 4 columns]

In [9]:
ct = greene.COST.values
q = greene.Q.values
p1 = greene.PL.values
p2 = greene.PF.values
p3 = greene.PK.values

In [10]:
# First input - y
y_0 = pd.DataFrame ([np.log(ct)]) # lnCT
y_1 = y_0.T.iloc[:,0]
y=y_1.rename("np.log(COST)", inplace =True)
y

0     -1.546463
1      1.112745
2      2.241337
3     -0.273648
4      0.814789
         ...
153    1.921222
154    1.324552
155    1.381834
156    3.407444
157    4.217391
Name: np.log(COST), Length: 158, dtype: float64

$$𝑙𝑛𝐶𝑇=𝛽0+𝛽𝑞𝑙𝑛𝑞+𝛽𝑞𝑞(𝑙𝑛𝑞)2+𝛽𝑞1𝑙𝑛𝑞𝑙𝑛𝑝1+𝛽𝑞2𝑙𝑛𝑞𝑙𝑛𝑝2+𝛽𝑞3𝑙𝑛𝑞𝑙𝑛𝑝3+𝛽1𝑙𝑛𝑝1+𝛽2𝑙𝑛𝑝2+𝛽3𝑙𝑛𝑝3+𝛽11(𝑙𝑛𝑝1)2+𝛽22(𝑙𝑛𝑝2)2+𝛽33(𝑙𝑛𝑝3)2+𝛽12𝑙𝑛𝑝1𝑙𝑛𝑝2+𝛽13𝑙𝑛𝑝1𝑙𝑛𝑝3+𝛽23𝑙𝑛𝑝2𝑙𝑛𝑝3$$

In [11]:
# Second input - x
ln_q = np.log(q) # lnq
ln_q_2 = np.multiply(ln_q,ln_q)

ln_p1 = np.log(p1) # lnpl
ln_p2 = np.log(p2) # lnpf
ln_p3 = np.log(p3) # lnpk

ln_q_ln_p1 = np.multiply(ln_q,ln_p1)
ln_q_ln_p2 = np.multiply(ln_q,ln_p2)
ln_q_ln_p3 = np.multiply(ln_q,ln_p3)


ln_p1_2 = np.multiply(ln_p1,ln_p1) 
ln_p2_2 = np.multiply(ln_p2,ln_p2) 
ln_p3_2 = np.multiply(ln_p3,ln_p3) 

ln_p1_ln_p2 = np.multiply (ln_p1,ln_p2)
ln_p1_ln_p3 = np.multiply (ln_p1,ln_p3)
ln_p2_ln_p3 = np.multiply (ln_p2,ln_p3)

x = pd.DataFrame([ln_q, ln_q_2, ln_q_ln_p1, ln_q_ln_p2, ln_q_ln_p3, ln_p1, ln_p2, ln_p3, ln_p1_2, ln_p2_2, ln_p3_2, ln_p1_ln_p2, ln_p1_ln_p3, ln_p2_ln_p3]).T

x.rename(columns = {0:'lnq', 1:'lnq2', 2:'lnqlnp1', 3:'lnqlnp2', 4:'lnqlnp3',
                    5:'lnp1', 6:'lnp2', 7:'lnp3',
                    8:'lnp1_2', 9:'lnp2_2', 10:'lnp3_2',
                    11:'lnp1lnp2', 12:'lnp1lnp3', 13:'lnp2lnp3'}, inplace = True)
x

,lnq,lnq2,lnqlnp1,lnqlnp2,lnqlnp3,lnp1,lnp2,lnp3,lnp1_2,lnp2_2,lnp3_2,lnp1lnp2,lnp1lnp3,lnp2lnp3
0,2.079442,4.324077,18.371538,6.010359,8.678634,8.834842,2.890372,4.173541,78.054437,8.354249,17.418442,25.535978,36.872574,12.063084
1,6.767343,45.796933,61.127805,20.624885,28.577410,9.032763,3.047708,4.222840,81.590803,9.288523,17.832381,27.529222,38.143915,12.869984
2,7.252762,52.602563,65.146469,27.026810,26.878966,8.982297,3.726416,3.706032,80.681665,13.886177,13.734670,33.471777,33.288677,13.810215
3,4.174387,17.425509,37.994654,13.989505,15.526556,9.101852,3.351272,3.719481,82.843703,11.231021,13.834542,30.502777,33.854168,12.464992
4,5.686975,32.341689,51.263140,20.863674,24.316554,9.014131,3.668677,4.275832,81.254554,13.459189,18.282743,33.069932,38.542913,15.686647
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
153,6.852877,46.961918,63.543838,27.006249,25.870001,9.272579,3.940863,3.775057,85.980717,15.530402,14.251056,36.541963,35.004515,14.876983
154,5.932245,35.191533,52.877557,20.820004,25.542382,8.913583,3.509633,4.305685,79.451954,12.317525,18.538927,31.283405,38.379082,15.111376
155,5.968708,35.625470,51.749248,22.671977,26.025919,8.670093,3.798473,4.360394,75.170509,14.428401,19.013039,32.933118,37.805024,16.562842
156,8.578665,73.593485,78.650266,32.031471,37.375623,9.168125,3.733853,4.356811,84.054510,13.941657,18.981805,34.232428,39.943790,16.267692
157,9.630366,92.743942,85.244879,31.250645,41.452974,8.851676,3.245011,4.304403,78.352173,10.530098,18.527884,28.723790,38.101181,13.967836

In [12]:
# Beta_OLS function
def beta_OLS( X : pd.DataFrame, y : pd.Series, intercept = True ):
        
    if not isinstance( X, pd.DataFrame ):
        raise TypeError( 'X is not a pd.DataFrame' )
    
    if not isinstance( y, pd.Series ):
        raise TypeError( 'y is not a pd.Series' )
    
    if not isinstance( intercept, bool ):
        raise TypeError( 'intercept is not a bool' )
        
    if len( X ) != len( y ):
        raise ValueError( 'X and y do not have the same number of rows' )
    
    X_mat = X.copy()
    y_vec = y.copy()
    
    if intercept == True:
        const = np.ones( len( X_mat ) )
        X_mat.insert(0, "Intercept", const)
    
    var_names = list( X_mat.columns )
    X_mat = X_mat.to_numpy()
    y_vec = y_vec.to_numpy()
    
    xtx_inv = np.linalg.inv( np.dot( np.transpose( X_mat ), X_mat ) )
    coefs = np.dot( xtx_inv, np.dot( np.transpose( X_mat ), y_vec ) )
    coefs = pd.DataFrame( coefs, index = var_names, columns = [ 'Coef.' ] )
    
    return coefs

In [13]:
beta_OLS(x,y,True)

               Coef.
Intercept -76.259258
lnq        -1.080425
lnq2        0.026489
lnqlnp1     0.131041
lnqlnp2     0.058652
lnqlnp3     0.040144
lnp1       14.718292
lnp2       -0.894733
lnp3        6.380797
lnp1_2     -0.769264
lnp2_2     -0.036753
lnp3_2     -0.163707
lnp1lnp2    0.162283
lnp1lnp3   -0.572050
lnp2lnp3   -0.024025

2. Generate a new function named **var_OLS**. This function must return the estimated variance for OLS. The inputs of this function should be `X`, `y`, and `intercept`. `X` (covariables) must be a **pd.DataFrame** and `y` (endog) must be a **pd.Series** and `intercept` can be `True` or `False`, by default `True`. When `intercept` is `False`, the estimated variance does not include **intercept** in the `X` regressor. Also, you must specify the type of your function's parameters and output and It must raise an error if the inputs do not meet the requirements. The output of the function should look like `var_ols` where the columns and the index use the name of `X` columns.  Apply your function to find $\mathbb{V}{\rm ar} (\widehat{\boldsymbol{\beta}}^{(OLS)})$ of the equation below. Use greene data.  **Hint: Use numpy, `def` function, and `columns` method, [link](https://notebooks.githubusercontent.com/view/ipynb?browser=chrome&color_mode=auto&commit=69c80e1f2c1c268f0480a32932262201785a576c&device=unknown_device&enc_url=68747470733a2f2f7261772e67697468756275736572636f6e74656e742e636f6d2f616c6578616e6465727175697370652f4469706c6f6d61646f5f505543502f363963383065316632633163323638663034383061333239333232363232303137383561353736632f4c6563747572655f352f4c6563747572655f352e6970796e62&logged_in=true&nwo=alexanderquispe%2FDiplomado_PUCP&path=Lecture_5%2FLecture_5.ipynb&platform=windows&repository_id=427747212&repository_type=Repository&version=96##5.1.7.).**


$$
\begin{aligned}
\mathbb{V}{\rm ar} (\widehat{\boldsymbol{\beta}}^{(OLS)}) = 
\sigma^2 \left( \mathbf{X}^\top  \mathbf{X}\right)^{-1}
\end{aligned}
$$

$$
\begin{aligned} 
lnCT &= \beta_{0}+\beta_{q}lnq+ \beta_{qq}(lnq)^2+\beta_{q1}lnqlnp_1+\beta_{q2}lnqlnp_2+ \beta_{q3}lnqlnp_{3} +\beta_{1}lnp_1+\beta_{2}lnp_2+ \beta_{3}lnp_3 \\
& + \beta_{11}(lnp_{1})^2+ \beta_{22}(lnp_{2})^2+ \beta_{33}(lnp_{3})^2 + \beta_{12}lnp_{1}lnp_{2}+ \beta_{13}lnp_{1}lnp_{3}+\beta_{23}lnp_{2}lnp_{3} 
\end{aligned}
$$

In [14]:
var_OLS_output = results.fit().cov_params()

In [15]:
var_OLS_output

            Intercept  np.log(Q)  np.log(PL)  np.log(PF)  np.log(PK)
Intercept    1.130476   0.001167   -0.104116    0.004928   -0.052305
np.log(Q)    0.001167   0.000088   -0.000179    0.000055   -0.000111
np.log(PL)  -0.104116  -0.000179    0.011198   -0.001794    0.002636
np.log(PF)   0.004928   0.000055   -0.001794    0.004142   -0.000782
np.log(PK)  -0.052305  -0.000111    0.002636   -0.000782    0.007581

In [16]:
# var_OLS function
def var_OLS( X : pd.DataFrame, y : pd.Series, intercept = True ):
        
    if not isinstance( X, pd.DataFrame ):
        raise TypeError( 'X is not a pd.DataFrame' )
    
    if not isinstance( y, pd.Series ):
        raise TypeError( 'y is not a pd.Series' )
    
    if not isinstance( intercept, bool ):
        raise TypeError( 'intercept is not a bool' )
        
    if len( X ) != len( y ):
        raise ValueError( 'X and y do not have the same number of rows' )
    
    X_mat = X.copy()
    y_vec = y.copy()
    
    if intercept == True:
        const = np.ones( len( X_mat ) )
        X_mat.insert(0, "Intercept", const)
    
    var_names = list( X_mat.columns )
    X_mat = X_mat.to_numpy()
    y_vec = y_vec.to_numpy()
    
    xtx_inv = np.linalg.inv( np.dot( np.transpose( X_mat ), X_mat ) )
    coefs = np.dot( xtx_inv, np.dot( np.transpose( X_mat ), y_vec ) )
    
    errores=np.add(y_vec,-np.dot( X_mat , coefs ))
    var_error=np.dot(np.transpose(errores),errores)/(len(errores)-14-1)

    var_coef=var_error*xtx_inv
    
    var_coef = pd.DataFrame( var_coef, index = var_names, columns=var_names)

    
    return var_coef

In [17]:
var_OLS(x,y,True)

,Intercept,lnq,lnq2,lnqlnp1,lnqlnp2,lnqlnp3,lnp1,lnp2,lnp3,lnp1_2,lnp2_2,lnp3_2,lnp1lnp2,lnp1lnp3,lnp2lnp3
Intercept,1465.361105,0.192537,-0.011698,-0.026677,0.015949,0.039538,-262.932564,-8.392679,-128.192045,11.880856,-0.266944,3.540639,0.990253,10.902440,0.197435
lnq,0.192537,0.141034,0.000308,-0.013459,0.000161,-0.006089,-0.186223,0.148320,-0.090714,0.015321,0.000381,-0.000898,-0.015046,0.017546,-0.003570
lnq2,-0.011698,0.000308,0.000006,-0.000036,-0.000005,-0.000011,0.001491,0.001052,0.000862,-0.000043,0.000013,-0.000060,-0.000099,-0.000014,-0.000048
lnqlnp1,-0.026677,-0.013459,-0.000036,0.001466,-0.000168,0.000348,0.021561,-0.015127,0.005430,-0.001961,0.000019,0.000285,0.001850,-0.001141,-0.000085
lnqlnp2,0.015949,0.000161,-0.000005,-0.000168,0.000653,-0.000189,-0.008293,0.003306,0.008035,0.000587,-0.000170,-0.000103,-0.000170,-0.000144,-0.001375
lnqlnp3,0.039538,-0.006089,-0.000011,0.000348,-0.000189,0.000888,-0.000337,-0.008853,0.000268,0.000211,-0.000033,-0.000067,0.000102,-0.001537,0.002212
lnp1,-262.932564,-0.186223,0.001491,0.021561,-0.008293,-0.000337,50.194721,-1.253531,19.099542,-2.388986,0.070493,-0.420154,0.038416,-1.788158,0.132157
lnp2,-8.392679,0.148320,0.001052,-0.015127,0.003306,-0.008853,-1.253531,8.078742,-0.214871,0.161643,-0.058647,-0.033147,-0.685050,0.199482,-0.367388
lnp3,-128.192045,-0.090714,0.000862,0.005430,0.008035,0.000268,19.099542,-0.214871,20.513714,-0.705214,0.023665,-0.763050,0.036229,-1.555553,-0.072591
lnp1_2,11.880856,0.015321,-0.000043,-0.001961,0.000587,0.000211,-2.388986,0.161643,-0.705214,0.119855,-0.003079,0.011353,-0.013413,0.070381,-0.006656
lnp2_2,-0.266944,0.000381,0.000013,0.000019,-0.000170,-0.000033,0.070493,-0.058647,0.023665,-0.003079,0.008285,-0.002049,-0.001552,-0.002485,0.004467
lnp3_2,3.540639,-0.000898,-0.000060,0.000285,-0.000103,-0.000067,-0.420154,-0.033147,-0.763050,0.011353,-0.002049,0.048556,0.008386,0.043314,-0.006653
lnp1lnp2,0.990253,-0.015046,-0.000099,0.001850,-0.000170,0.000102,0.038416,-0.685050,0.036229,-0.013413,-0.001552,0.008386,0.072939,-0.015413,0.009949
lnp1lnp3,10.902440,0.017546,-0.000014,-0.001141,-0.000144,-0.001537,-1.788158,0.199482,-1.555553,0.070381,-0.002485,0.043314,-0.015413,0.138302,-0.010534
lnp2lnp3,0.197435,-0.003570,-0.000048,-0.000085,-0.001375,0.002212,0.132157,-0.367388,-0.072591,-0.006656,0.004467,-0.006653,0.009949,-0.010534,0.060678

3. Generate a new function named as `reg_OLS` that uses your previos functions `beta_OLS` and `var_OLS` to return an ouput similar to `reg_OLS_output`. The inputs of this function should be `X`, `y`, and `intercept`. `X` (covariables) must be a **pd.DataFrame** and `y` (endog) must be a **pd.Series** and `intercept` can be `True` or `False`, by default `True`. When `intercept` is `False`, the output does not include **intercept**. Also, you must specify the type of your function's parameters and output and It must raise an error if the inputs do not meet the requirements. Apply your function to the equation below. Use greene data.**Hint: Use numpy, `def` function, and `columns` method, [link](https://notebooks.githubusercontent.com/view/ipynb?browser=chrome&color_mode=auto&commit=69c80e1f2c1c268f0480a32932262201785a576c&device=unknown_device&enc_url=68747470733a2f2f7261772e67697468756275736572636f6e74656e742e636f6d2f616c6578616e6465727175697370652f4469706c6f6d61646f5f505543502f363963383065316632633163323638663034383061333239333232363232303137383561353736632f4c6563747572655f352f4c6563747572655f352e6970796e62&logged_in=true&nwo=alexanderquispe%2FDiplomado_PUCP&path=Lecture_5%2FLecture_5.ipynb&platform=windows&repository_id=427747212&repository_type=Repository&version=96##5.1.7.).**

$$
\begin{aligned} 
lnCT &= \beta_{0}+\beta_{q}lnq+ \beta_{qq}(lnq)^2+\beta_{q1}lnqlnp_1+\beta_{q2}lnqlnp_2+ \beta_{q3}lnqlnp_{3} +\beta_{1}lnp_1+\beta_{2}lnp_2+ \beta_{3}lnp_3 \\
& + \beta_{11}(lnp_{1})^2+ \beta_{22}(lnp_{2})^2+ \beta_{33}(lnp_{3})^2 + \beta_{12}lnp_{1}lnp_{2}+ \beta_{13}lnp_{1}lnp_{3}+\beta_{23}lnp_{2}lnp_{3} 
\end{aligned}
$$

In [18]:
reg_OLS_output = results.fit().summary2().tables[1]
reg_OLS_output

               Coef.  Std.Err.          t          P>|t|    [0.025    0.975]
Intercept  -7.472227  1.063238  -7.027801   6.490901e-11 -9.572750 -5.371704
np.log(Q)   0.838111  0.009387  89.284492  6.942379e-134  0.819566  0.856656
np.log(PL)  0.044258  0.105820   0.418238   6.763595e-01 -0.164798  0.253314
np.log(PF)  0.713098  0.064355  11.080610   2.552882e-21  0.585958  0.840238
np.log(PK)  0.188449  0.087066   2.164432   3.198211e-02  0.016442  0.360457

In [19]:
import scipy.stats as stats
def reg_OLS( x : pd.DataFrame, y : pd.Series, intercept = True ):
    
    if not isinstance( x, pd.DataFrame ):
        raise TypeError( 'x is not a pd.DataFrame' )
    
    if not isinstance( y, pd.Series ):
        raise TypeError( 'y is not a pd.Series' )
    
    if not isinstance( intercept, bool ):
        raise TypeError( 'intercept is not a bool' )
        
    if (intercept == True):
        
        beta = beta_OLS( x, y, intercept = True )
        var = var_OLS( x, y, intercept = True )
                     
        reg_OLS = pd.DataFrame( beta )
        
        var_cov = var.to_numpy() 
        
        diagonal = [var_cov[i][i] for i in range( len(var_cov[0]) )] #extract diagonal
        
        std_error = np.sqrt( np.array(diagonal) )

        reg_OLS[ 'Std.Err.' ] = std_error 

        reg_OLS[ 't' ] = reg_OLS[ 'Coef.' ] / reg_OLS[ 'Std.Err.' ]
        
        p = stats.t.sf( abs( reg_OLS[ 't' ] ), df = len( y ) - len( beta ) ) * 2
        
        reg_OLS[ 'P>|t|' ] = p
                
        reg_OLS['[0.025'] = reg_OLS[ 'Coef.' ] - stats.t.ppf(q = 1 - 0.05 / 2, df = len(y)-len(beta)) * reg_OLS[ 'Std.Err.' ]
               
        reg_OLS['0.975]'] = reg_OLS[ 'Coef.' ] + stats.t.ppf(q = 1 - 0.05 / 2, df = len(y)-len(beta)) * reg_OLS[ 'Std.Err.' ]

        
    else:
        
        beta = beta_OLS( X, y, intercept = False )
        var = var_OLS( X, y, intercept = False )
            
        reg_OLS = pd.DataFrame( beta )
        
        var_cov = var.to_numpy() 
        
        diagonal = [var_cov[i][i] for i in range( len(var_cov[0]) )] #extract diagonal
        
        std_error = np.sqrt( np.array(diagonal) )

        reg_OLS[ 'Std.Err.' ] = std_error 
        
        reg_OLS[ 't' ] = reg_OLS[ 'Coef.' ] / reg_OLS[ 'Std.Err.' ]
        
        p = stats.t.sf( abs( reg_OLS[ 't' ] ), df = len( y ) - len( beta ) ) * 2
        
        reg_OLS[ 'P>|t|' ] = p
               
        reg_OLS['[0.025'] = reg_OLS[ 'Coef.' ] - stats.t.ppf(q = 1 - 0.05 / 2, df = len(y)-len(beta)) * reg_OLS[ 'Std.Err.' ]
               
        reg_OLS['0.975]'] = reg_OLS[ 'Coef.' ] + stats.t.ppf(q = 1 - 0.05 / 2, df = len(y)-len(beta)) * reg_OLS[ 'Std.Err.' ]

        
    return reg_OLS

In [20]:
reg_OLS(x, y, intercept = True )

,Coef.,Std.Err.,t,P>|t|,[0.025,0.975]
Intercept,-76.259258,38.280035,-1.992142,4.825953e-02,-151.927105,-0.591411
lnq,-1.080425,0.375545,-2.876952,4.630885e-03,-1.822762,-0.338088
lnq2,0.026489,0.002357,11.240060,2.112040e-21,0.021831,0.031148
lnqlnp1,0.131041,0.038284,3.422854,8.084864e-04,0.055365,0.206716
lnqlnp2,0.058652,0.025549,2.295650,2.315002e-02,0.008149,0.109155
lnqlnp3,0.040144,0.029791,1.347518,1.799447e-01,-0.018744,0.099033
lnp1,14.718292,7.084823,2.077440,3.954949e-02,0.713777,28.722807
lnp2,-0.894733,2.842313,-0.314790,7.533796e-01,-6.513110,4.723645
lnp3,6.380797,4.529207,1.408811,1.610617e-01,-2.572051,15.333644
lnp1_2,-0.769264,0.346201,-2.222011,2.785341e-02,-1.453597,-0.084930
lnp2_2,-0.036753,0.091019,-0.403791,6.869699e-01,-0.216670,0.143165
lnp3_2,-0.163707,0.220354,-0.742927,4.587448e-01,-0.599280,0.271866
lnp1lnp2,0.162283,0.270072,0.600888,5.488659e-01,-0.371566,0.696132
lnp1lnp3,-0.572050,0.371890,-1.538224,1.262037e-01,-1.307163,0.163062
lnp2lnp3,-0.024025,0.246329,-0.097531,9.224414e-01,-0.510942,0.462892

4. Generate a new function named as `restricted_OLS` that uses your previos functions `beta_OLS` and `var_OLS` to return an ouput similar to `reg_OLS_output`. The inputs of this function should be `X`, `y`,  `L`, `r`, and `intercept`. `X` (covariables) must be a **pd.DataFrame** and `y` (endog) must be a **pd.Series**,  `L` (coef) must be a **np.array**, `r` must be a **np.array**,  and `intercept` can be `True` or `False`.  When `intercept` is `False`, the estimated beta does not include **intercept**. Also, you must specify the type of your function's parameters and output and It must raise an error if the inputs do not meet the requirements. The ouput of this function should look like `reg_OLS_ouput`. Apply your function to the equation below. Use greene data.
 **Hint: Use numpy, `def` function, and `columns` method, [link](https://notebooks.githubusercontent.com/view/ipynb?browser=chrome&color_mode=auto&commit=69c80e1f2c1c268f0480a32932262201785a576c&device=unknown_device&enc_url=68747470733a2f2f7261772e67697468756275736572636f6e74656e742e636f6d2f616c6578616e6465727175697370652f4469706c6f6d61646f5f505543502f363963383065316632633163323638663034383061333239333232363232303137383561353736632f4c6563747572655f352f4c6563747572655f352e6970796e62&logged_in=true&nwo=alexanderquispe%2FDiplomado_PUCP&path=Lecture_5%2FLecture_5.ipynb&platform=windows&repository_id=427747212&repository_type=Repository&version=96##5.1.7.).**

$$
\hat{\boldsymbol{\beta}}^{(RLS)} =\hat{\boldsymbol{\beta}}^{(OLS)} - \left( \boldsymbol{X}^\top \boldsymbol{X} \right)^{-1} \boldsymbol{L}^\top \left( \boldsymbol{L}\left( \boldsymbol{X}^\top \boldsymbol{X} \right)^{-1} \boldsymbol{L}^\top \right)^{-1} \left( \boldsymbol{L}\widehat{\boldsymbol{\beta}}^{(OLS)} - \boldsymbol{r} \right)
$$

$$
\begin{aligned}
\mathbb{V}{\rm ar} \left(\widehat{\boldsymbol{\beta}}^{(RLS)} \right) 
&= \sigma^2 \left( \mathbf{X}^\top  \mathbf{X}\right)^{-1} - \sigma^2 \left( \mathbf{X}^\top  \mathbf{X}\right)^{-1}  \mathbf{L}^\top \left( \mathbf{L}\left( \mathbf{X}^\top \mathbf{X} \right)^{-1} \mathbf{L}^\top \right)^{-1}  \mathbf{L} \left( \mathbf{X}^\top  \mathbf{X}\right)^{-1}
\end{aligned}
$$

$$
\begin{aligned} 
lnCT &= \beta_{0}+\beta_{q}lnq+ \beta_{qq}(lnq)^2+\beta_{q1}lnqlnp_1+\beta_{q2}lnqlnp_2+ \beta_{q3}lnqlnp_{3} +\beta_{1}lnp_1+\beta_{2}lnp_2+ \beta_{3}lnp_3 \\
& + \beta_{11}(lnp_{1})^2+ \beta_{22}(lnp_{2})^2+ \beta_{33}(lnp_{3})^2 + \beta_{12}lnp_{1}lnp_{2}+ \beta_{13}lnp_{1}lnp_{3}+\beta_{23}lnp_{2}lnp_{3} 
\end{aligned}
$$

ST: 

<br>
$$
\begin{aligned} 
\beta_{1} + \beta_{2} + \beta_{3} &= 1 \\
\beta_{q1} + \beta_{q2} + \beta_{q3} &= 0 \\
\beta_{11} + \beta_{12} + \beta_{13} &= 0 \\
\beta_{21} + \beta_{22} + \beta_{23} &= 0 \\
\beta_{31} + \beta_{32} + \beta_{33} &= 0 \\
\beta_{ij} = \beta_{ji}
\end{aligned}
$$

In [21]:
#Restrictions
L = np.array(([0,0,0,0,0,1,1,1,0,0,0,0,0,0],
              [0,0,1,1,1,0,0,0,0,0,0,0,0,0],
              [0,0,0,0,0,0,0,0,1,0,0,1,1,0],
              [0,0,0,0,0,0,0,0,0,1,0,1,0,1],
              [0,0,0,0,0,0,0,0,0,0,1,0,1,1]))

r = np.array(([1], [0], [0], [0], [0]))
r

array([[1],
       [0],
       [0],
       [0],
       [0]])

In [101]:
def restricted_OLS( x : pd.DataFrame, y : pd.Series, L : np.array, r: np.array,intercept = True ):
    
    if not isinstance( x, pd.DataFrame ):
        raise TypeError( 'x is not a pd.DataFrame' )
    
    if not isinstance( y, pd.Series ):
        raise TypeError( 'y is not a pd.Series' )
    
    if not isinstance( intercept, bool ):
        raise TypeError( 'intercept is not a bool' )

    if not isinstance( L, np.ndarray ):
        raise TypeError( "L is not a np.array.")  

    if not isinstance( r, np.ndarray ):
        raise TypeError( "r is not a np.array.")
     
    X_mat = x.copy()
    y_vec = y.copy()
    
    
    if intercept == True:
        #Names of variables
        var_names = list( X_mat.columns )
        var_names.insert(0,"Intercept")
        #
        const = np.ones( len( y_vec ) )
        X_mat_rs = np.c_[const,X_mat]
        #
        L_0      = np.zeros(len(r))
        L_rs        = np.c_[L_0, L]
        #
        beta = beta_OLS( x, y, intercept = True ).to_numpy()
        var = var_OLS( x, y, intercept = True ).to_numpy()       
    
        
    if intercept == False:        
        beta = beta_OLS( x, y, intercept = False ).to_numpy()
        var = var_OLS( x, y, intercept = False ).to_numpy()  
        L_rs=L.to_numpy()  
        #Names of variables
        var_names = list( X_mat.columns )
        
        
    #Declarate var as vector and matrix
    #X_mat = X_mat.to_numpy()
    y_vec = y_vec.to_numpy()
    ########################    
    
    #
    xtx_inv = np.linalg.inv( np.dot( np.transpose( X_mat_rs ), X_mat_rs ) )
    coefs = np.dot( xtx_inv, np.dot( np.transpose( X_mat_rs ), y_vec ) )
    
    #restricted_OLS
    coef_restricted_OLS= beta - xtx_inv @ L_rs.T @ np.linalg.inv(L_rs @ xtx_inv @ L_rs.T) @ (L_rs @ beta -r)
    coef_restricted_OLS = pd.DataFrame( coef_restricted_OLS, index = var_names, columns = [ 'Coef.' ] )
    coef_restricted_OLS_2=coef_restricted_OLS
    #var_restricted_OLS
    
    # Defining errors and variance
    errores=np.add(y_vec,-np.dot( X_mat_rs , coefs ))
    var_sqr = np.dot(np.transpose(errores),errores) / (len(y_vec)-len(X_mat_rs[0])-1)

    # getting var_beta_rls
    var_restricted_OLS= var_sqr * xtx_inv - var_sqr * xtx_inv @ L_rs.T @ np.linalg.inv(L_rs @ xtx_inv @ L_rs.T) @  L_rs @ xtx_inv
    var_restricted_OLS= pd.DataFrame( var_restricted_OLS, index = var_names, columns=var_names)
    
    #
    reg_OLS = pd.DataFrame( coef_restricted_OLS_2 )
        
    var_cov = var_restricted_OLS.to_numpy() 
        
    diagonal = [var_cov[i][i] for i in range( len(var_cov[0]) )] #extract diagonal
        
    std_error = np.sqrt( np.array(diagonal) )

    reg_OLS[ 'Std.Err.' ] = std_error 

    reg_OLS[ 't' ] = reg_OLS[ 'Coef.' ] / reg_OLS[ 'Std.Err.' ]
        
    p = stats.t.sf( abs( reg_OLS[ 't' ] ), df = len( y ) - len( coef_restricted_OLS ) ) * 2
        
    reg_OLS[ 'P>|t|' ] = p
                
    reg_OLS['[0.025'] = reg_OLS[ 'Coef.' ] - stats.t.ppf(q = 1 - 0.05 / 2, df = len(y)-len(coef_restricted_OLS)) * reg_OLS[ 'Std.Err.' ]
               
    reg_OLS['0.975]'] = reg_OLS[ 'Coef.' ] + stats.t.ppf(q = 1 - 0.05 / 2, df = len(y)-len(coef_restricted_OLS)) * reg_OLS[ 'Std.Err.' ]

    reg_OLS_r=reg_OLS
    
    return coef_restricted_OLS, var_restricted_OLS, reg_OLS_r

In [102]:
coef_restricted_OLS, var_restricted_OLS, reg_OLS_r =restricted_OLS(x, y, L, r, intercept = True )

In [103]:
coef_restricted_OLS

              Coef.  Std.Err.          t         P>|t|     [0.025    0.975]
Intercept -7.111200  2.765553  -2.571348  1.115122e-02 -12.577847 -1.644553
lnq        0.461368  0.120142   3.840181  1.841235e-04   0.223884  0.698852
lnq2       0.029978  0.002128  14.085254  8.278278e-29   0.025771  0.034185
lnqlnp1   -0.004354  0.022961  -0.189644  8.498569e-01  -0.049741  0.041032
lnqlnp2    0.036778  0.024286   1.514345  1.321455e-01  -0.011229  0.084785
lnqlnp3   -0.032424  0.021494  -1.508478  1.336384e-01  -0.074911  0.010064
lnp1       0.215566  1.018774   0.211594  8.327252e-01  -1.798237  2.229369
lnp2       0.402923  0.556110   0.724538  4.699191e-01  -0.696335  1.502181
lnp3       0.381511  0.533184   0.715533  4.754465e-01  -0.672430  1.435451
lnp1_2    -0.004356  0.070728  -0.061590  9.509757e-01  -0.144164  0.135452
lnp2_2     0.002578  0.080448   0.032043  9.744821e-01  -0.156443  0.161599
lnp3_2    -0.007651  0.150686  -0.050773  9.595769e-01  -0.305510  0.290208
lnp1lnp2  -0.002936  0.114266  -0.025697  9.795350e-01  -0.228806  0.222933
lnp1lnp3   0.007292  0.073921   0.098652  9.215530e-01  -0.138826  0.153411
lnp2lnp3   0.000358  0.116129   0.003087  9.975416e-01  -0.229194  0.229910

In [104]:
var_restricted_OLS

,Intercept,lnq,lnq2,lnqlnp1,lnqlnp2,lnqlnp3,lnp1,lnp2,lnp3,lnp1_2,lnp2_2,lnp3_2,lnp1lnp2,lnp1lnp3,lnp2lnp3
Intercept,7.648283,-0.086668,0.000093,0.014129,-0.019922,0.005793,-2.749398,1.454277,1.295121,0.178690,-0.041430,-0.370497,-0.253878,0.075188,0.295308
lnq,-0.086668,0.014434,-0.000031,-0.002625,0.002046,0.000579,0.010989,-0.013284,0.002295,0.000718,-0.001315,-0.000593,0.000002,-0.000720,0.001313
lnq2,0.000093,-0.000031,0.000005,-0.000007,-0.000001,0.000008,-0.000017,0.000068,-0.000051,0.000006,0.000014,-0.000022,-0.000021,0.000015,0.000007
lnqlnp1,0.014129,-0.002625,-0.000007,0.000527,-0.000328,-0.000200,-0.001241,0.001534,-0.000292,-0.000216,0.000253,0.000259,0.000111,0.000105,-0.000364
lnqlnp2,-0.019922,0.002046,-0.000001,-0.000328,0.000590,-0.000262,0.004595,-0.005516,0.000921,-0.000150,0.000026,0.000208,0.000166,-0.000016,-0.000192
lnqlnp3,0.005793,0.000579,0.000008,-0.000200,-0.000262,0.000462,-0.003354,0.003983,-0.000629,0.000366,-0.000279,-0.000466,-0.000277,-0.000089,0.000556
lnp1,-2.749398,0.010989,-0.000017,-0.001241,0.004595,-0.003354,1.037901,-0.531437,-0.506464,-0.070509,0.020548,0.139556,0.094759,-0.024250,-0.115306
lnp2,1.454277,-0.013284,0.000068,0.001534,-0.005516,0.003983,-0.531437,0.309258,0.222179,0.035169,-0.001148,-0.077161,-0.055591,0.020422,0.056739
lnp3,1.295121,0.002295,-0.000051,-0.000292,0.000921,-0.000629,-0.506464,0.222179,0.284285,0.035340,-0.019400,-0.062395,-0.039167,0.003828,0.058567
lnp1_2,0.178690,0.000718,0.000006,-0.000216,-0.000150,0.000366,-0.070509,0.035169,0.035340,0.005002,-0.001860,-0.009453,-0.006298,0.001295,0.008158
lnp2_2,-0.041430,-0.001315,0.000014,0.000253,0.000026,-0.000279,0.020548,-0.001148,-0.019400,-0.001860,0.006472,-0.001431,-0.003021,0.004881,-0.003451
lnp3_2,-0.370497,-0.000593,-0.000022,0.000259,0.000208,-0.000466,0.139556,-0.077161,-0.062395,-0.009453,-0.001431,0.022706,0.016795,-0.007342,-0.015364
lnp1lnp2,-0.253878,0.000002,-0.000021,0.000111,0.000166,-0.000277,0.094759,-0.055591,-0.039167,-0.006298,-0.003021,0.016795,0.013057,-0.006759,-0.010035
lnp1lnp3,0.075188,-0.000720,0.000015,0.000105,-0.000016,-0.000089,-0.024250,0.020422,0.003828,0.001295,0.004881,-0.007342,-0.006759,0.005464,0.001878
lnp2lnp3,0.295308,0.001313,0.000007,-0.000364,-0.000192,0.000556,-0.115306,0.056739,0.058567,0.008158,-0.003451,-0.015364,-0.010035,0.001878,0.013486

In [105]:
reg_OLS_r

              Coef.  Std.Err.          t         P>|t|     [0.025    0.975]
Intercept -7.111200  2.765553  -2.571348  1.115122e-02 -12.577847 -1.644553
lnq        0.461368  0.120142   3.840181  1.841235e-04   0.223884  0.698852
lnq2       0.029978  0.002128  14.085254  8.278278e-29   0.025771  0.034185
lnqlnp1   -0.004354  0.022961  -0.189644  8.498569e-01  -0.049741  0.041032
lnqlnp2    0.036778  0.024286   1.514345  1.321455e-01  -0.011229  0.084785
lnqlnp3   -0.032424  0.021494  -1.508478  1.336384e-01  -0.074911  0.010064
lnp1       0.215566  1.018774   0.211594  8.327252e-01  -1.798237  2.229369
lnp2       0.402923  0.556110   0.724538  4.699191e-01  -0.696335  1.502181
lnp3       0.381511  0.533184   0.715533  4.754465e-01  -0.672430  1.435451
lnp1_2    -0.004356  0.070728  -0.061590  9.509757e-01  -0.144164  0.135452
lnp2_2     0.002578  0.080448   0.032043  9.744821e-01  -0.156443  0.161599
lnp3_2    -0.007651  0.150686  -0.050773  9.595769e-01  -0.305510  0.290208
lnp1lnp2  -0.002936  0.114266  -0.025697  9.795350e-01  -0.228806  0.222933
lnp1lnp3   0.007292  0.073921   0.098652  9.215530e-01  -0.138826  0.153411
lnp2lnp3   0.000358  0.116129   0.003087  9.975416e-01  -0.229194  0.229910

5. Generate a new class named `RegClass`. The initial attributes of your class must be `X`, `y`, and `intercept`. `X` (covariables) must be a **pd.DataFrame** and `y` (endog) must be a **pd.Series** and `intercept` can be `True` or `False`, by default `True`. Also, you must specify the type of your class' parameters, and output and It must raise an error if the inputs do not meet the requirements.  This class should have two methods: `reg_OLS` and `restricted_OLS` (You can add more if you think it is necessary). These methods should return the same output as the previously defined functions with the same name. The method `reg_OLS` does not need an extra parameter to be executed. After executing the method `reg_OLS`, any user should access the following attributes: `beta_OLS` and `var_OLS`. They should look like `beta_OLS_output` and `var_OLS_output`. The `restricted_OLS` method needs two extra parameters before being executed, `L` and `r`. They refer to the restrictions. After running the method `restricted_OLS`, any user should access the following attributes: `beta_OLS`, `var_OLS`, `rest_beta_OLS`, and `rest_var_OLS`. These attributes refer to the beta and variance estimated using OLS and restricted OLS. They should look like  `beta_OLS_output` and `var_OLS_output`. Fix all the methods and attributes. No user should be able to change them. **Hint: Use [lecture 6](https://notebooks.githubusercontent.com/view/ipynb?browser=chrome&color_mode=auto&commit=69c80e1f2c1c268f0480a32932262201785a576c&device=unknown_device&enc_url=68747470733a2f2f7261772e67697468756275736572636f6e74656e742e636f6d2f616c6578616e6465727175697370652f4469706c6f6d61646f5f505543502f363963383065316632633163323638663034383061333239333232363232303137383561353736632f4c6563747572655f362f4c6563747572655f362e6970796e62&logged_in=true&nwo=alexanderquispe%2FDiplomado_PUCP&path=Lecture_6%2FLecture_6.ipynb&platform=windows&repository_id=427747212&repository_type=Repository&version=96#6.3.).**

In [106]:
class RegClass( object ):
    
    
    def __init__( self, x : pd.DataFrame, y : pd.Series, L: np.ndarray , r: np.ndarray, intercept = True ):
        
        __slots__ = [ 'x', 'y', 'intercept', 'beta_OLS', 'var_OLS', 'coef_restricted_OLS', 'var_restricted_OLS', ]
        
        if not isinstance( x, pd.DataFrame ):
            raise TypeError( 'x is not a pd.DataFrame' )
    
        if not isinstance( y, pd.Series ):
            raise TypeError( 'y is not a pd.Series' )
    
        if not isinstance( intercept, bool ):
            raise TypeError( 'intercept is not a bool' )
        
        if len( x ) != len( y ):
            raise ValueError( 'x and y do not have the same number of rows' )
        
        self.x = x
        self.y = y
        self.L = L
        self.r = r
        self.intercept = intercept        
   

    def reg_OLS( self ):
        
        self.beta_OLS = beta_OLS( self.x, self.y, intercept = self.intercept)
        self.var_OLS = var_OLS( self.x, self.y, intercept = self.intercept)
    
        return self.beta_OLS, self.var_OLS    
        
    def restricted_OLS( self, L : np.ndarray, r : np.ndarray, ):
      
        self.coef_restricted_OLS, self.var_restricted_OLS, reg_OLS_r=restricted_OLS(self.x, self.y, self.L, self.r, intercept = self.intercept )
        
        return self.coef_restricted_OLS, self.var_restricted_OLS, reg_OLS_r

In [107]:
Clase1 = RegClass(x, y, L, r, True)

In [108]:
Clase1.reg_OLS()[0]

               Coef.
Intercept -76.259258
lnq        -1.080425
lnq2        0.026489
lnqlnp1     0.131041
lnqlnp2     0.058652
lnqlnp3     0.040144
lnp1       14.718292
lnp2       -0.894733
lnp3        6.380797
lnp1_2     -0.769264
lnp2_2     -0.036753
lnp3_2     -0.163707
lnp1lnp2    0.162283
lnp1lnp3   -0.572050
lnp2lnp3   -0.024025

In [109]:
Clase1.reg_OLS()[1]

,Intercept,lnq,lnq2,lnqlnp1,lnqlnp2,lnqlnp3,lnp1,lnp2,lnp3,lnp1_2,lnp2_2,lnp3_2,lnp1lnp2,lnp1lnp3,lnp2lnp3
Intercept,1465.361105,0.192537,-0.011698,-0.026677,0.015949,0.039538,-262.932564,-8.392679,-128.192045,11.880856,-0.266944,3.540639,0.990253,10.902440,0.197435
lnq,0.192537,0.141034,0.000308,-0.013459,0.000161,-0.006089,-0.186223,0.148320,-0.090714,0.015321,0.000381,-0.000898,-0.015046,0.017546,-0.003570
lnq2,-0.011698,0.000308,0.000006,-0.000036,-0.000005,-0.000011,0.001491,0.001052,0.000862,-0.000043,0.000013,-0.000060,-0.000099,-0.000014,-0.000048
lnqlnp1,-0.026677,-0.013459,-0.000036,0.001466,-0.000168,0.000348,0.021561,-0.015127,0.005430,-0.001961,0.000019,0.000285,0.001850,-0.001141,-0.000085
lnqlnp2,0.015949,0.000161,-0.000005,-0.000168,0.000653,-0.000189,-0.008293,0.003306,0.008035,0.000587,-0.000170,-0.000103,-0.000170,-0.000144,-0.001375
lnqlnp3,0.039538,-0.006089,-0.000011,0.000348,-0.000189,0.000888,-0.000337,-0.008853,0.000268,0.000211,-0.000033,-0.000067,0.000102,-0.001537,0.002212
lnp1,-262.932564,-0.186223,0.001491,0.021561,-0.008293,-0.000337,50.194721,-1.253531,19.099542,-2.388986,0.070493,-0.420154,0.038416,-1.788158,0.132157
lnp2,-8.392679,0.148320,0.001052,-0.015127,0.003306,-0.008853,-1.253531,8.078742,-0.214871,0.161643,-0.058647,-0.033147,-0.685050,0.199482,-0.367388
lnp3,-128.192045,-0.090714,0.000862,0.005430,0.008035,0.000268,19.099542,-0.214871,20.513714,-0.705214,0.023665,-0.763050,0.036229,-1.555553,-0.072591
lnp1_2,11.880856,0.015321,-0.000043,-0.001961,0.000587,0.000211,-2.388986,0.161643,-0.705214,0.119855,-0.003079,0.011353,-0.013413,0.070381,-0.006656
lnp2_2,-0.266944,0.000381,0.000013,0.000019,-0.000170,-0.000033,0.070493,-0.058647,0.023665,-0.003079,0.008285,-0.002049,-0.001552,-0.002485,0.004467
lnp3_2,3.540639,-0.000898,-0.000060,0.000285,-0.000103,-0.000067,-0.420154,-0.033147,-0.763050,0.011353,-0.002049,0.048556,0.008386,0.043314,-0.006653
lnp1lnp2,0.990253,-0.015046,-0.000099,0.001850,-0.000170,0.000102,0.038416,-0.685050,0.036229,-0.013413,-0.001552,0.008386,0.072939,-0.015413,0.009949
lnp1lnp3,10.902440,0.017546,-0.000014,-0.001141,-0.000144,-0.001537,-1.788158,0.199482,-1.555553,0.070381,-0.002485,0.043314,-0.015413,0.138302,-0.010534
lnp2lnp3,0.197435,-0.003570,-0.000048,-0.000085,-0.001375,0.002212,0.132157,-0.367388,-0.072591,-0.006656,0.004467,-0.006653,0.009949,-0.010534,0.060678

In [110]:
Clase1.restricted_OLS(L,r)[0]

              Coef.  Std.Err.          t         P>|t|     [0.025    0.975]
Intercept -7.111200  2.765553  -2.571348  1.115122e-02 -12.577847 -1.644553
lnq        0.461368  0.120142   3.840181  1.841235e-04   0.223884  0.698852
lnq2       0.029978  0.002128  14.085254  8.278278e-29   0.025771  0.034185
lnqlnp1   -0.004354  0.022961  -0.189644  8.498569e-01  -0.049741  0.041032
lnqlnp2    0.036778  0.024286   1.514345  1.321455e-01  -0.011229  0.084785
lnqlnp3   -0.032424  0.021494  -1.508478  1.336384e-01  -0.074911  0.010064
lnp1       0.215566  1.018774   0.211594  8.327252e-01  -1.798237  2.229369
lnp2       0.402923  0.556110   0.724538  4.699191e-01  -0.696335  1.502181
lnp3       0.381511  0.533184   0.715533  4.754465e-01  -0.672430  1.435451
lnp1_2    -0.004356  0.070728  -0.061590  9.509757e-01  -0.144164  0.135452
lnp2_2     0.002578  0.080448   0.032043  9.744821e-01  -0.156443  0.161599
lnp3_2    -0.007651  0.150686  -0.050773  9.595769e-01  -0.305510  0.290208
lnp1lnp2  -0.002936  0.114266  -0.025697  9.795350e-01  -0.228806  0.222933
lnp1lnp3   0.007292  0.073921   0.098652  9.215530e-01  -0.138826  0.153411
lnp2lnp3   0.000358  0.116129   0.003087  9.975416e-01  -0.229194  0.229910

In [111]:
Clase1.restricted_OLS(L,r)[1]

,Intercept,lnq,lnq2,lnqlnp1,lnqlnp2,lnqlnp3,lnp1,lnp2,lnp3,lnp1_2,lnp2_2,lnp3_2,lnp1lnp2,lnp1lnp3,lnp2lnp3
Intercept,7.648283,-0.086668,0.000093,0.014129,-0.019922,0.005793,-2.749398,1.454277,1.295121,0.178690,-0.041430,-0.370497,-0.253878,0.075188,0.295308
lnq,-0.086668,0.014434,-0.000031,-0.002625,0.002046,0.000579,0.010989,-0.013284,0.002295,0.000718,-0.001315,-0.000593,0.000002,-0.000720,0.001313
lnq2,0.000093,-0.000031,0.000005,-0.000007,-0.000001,0.000008,-0.000017,0.000068,-0.000051,0.000006,0.000014,-0.000022,-0.000021,0.000015,0.000007
lnqlnp1,0.014129,-0.002625,-0.000007,0.000527,-0.000328,-0.000200,-0.001241,0.001534,-0.000292,-0.000216,0.000253,0.000259,0.000111,0.000105,-0.000364
lnqlnp2,-0.019922,0.002046,-0.000001,-0.000328,0.000590,-0.000262,0.004595,-0.005516,0.000921,-0.000150,0.000026,0.000208,0.000166,-0.000016,-0.000192
lnqlnp3,0.005793,0.000579,0.000008,-0.000200,-0.000262,0.000462,-0.003354,0.003983,-0.000629,0.000366,-0.000279,-0.000466,-0.000277,-0.000089,0.000556
lnp1,-2.749398,0.010989,-0.000017,-0.001241,0.004595,-0.003354,1.037901,-0.531437,-0.506464,-0.070509,0.020548,0.139556,0.094759,-0.024250,-0.115306
lnp2,1.454277,-0.013284,0.000068,0.001534,-0.005516,0.003983,-0.531437,0.309258,0.222179,0.035169,-0.001148,-0.077161,-0.055591,0.020422,0.056739
lnp3,1.295121,0.002295,-0.000051,-0.000292,0.000921,-0.000629,-0.506464,0.222179,0.284285,0.035340,-0.019400,-0.062395,-0.039167,0.003828,0.058567
lnp1_2,0.178690,0.000718,0.000006,-0.000216,-0.000150,0.000366,-0.070509,0.035169,0.035340,0.005002,-0.001860,-0.009453,-0.006298,0.001295,0.008158
lnp2_2,-0.041430,-0.001315,0.000014,0.000253,0.000026,-0.000279,0.020548,-0.001148,-0.019400,-0.001860,0.006472,-0.001431,-0.003021,0.004881,-0.003451
lnp3_2,-0.370497,-0.000593,-0.000022,0.000259,0.000208,-0.000466,0.139556,-0.077161,-0.062395,-0.009453,-0.001431,0.022706,0.016795,-0.007342,-0.015364
lnp1lnp2,-0.253878,0.000002,-0.000021,0.000111,0.000166,-0.000277,0.094759,-0.055591,-0.039167,-0.006298,-0.003021,0.016795,0.013057,-0.006759,-0.010035
lnp1lnp3,0.075188,-0.000720,0.000015,0.000105,-0.000016,-0.000089,-0.024250,0.020422,0.003828,0.001295,0.004881,-0.007342,-0.006759,0.005464,0.001878
lnp2lnp3,0.295308,0.001313,0.000007,-0.000364,-0.000192,0.000556,-0.115306,0.056739,0.058567,0.008158,-0.003451,-0.015364,-0.010035,0.001878,0.013486