# 1 Assignment 3

1. Generate a function named **beta_OLS**. This function must return the estimated beta using OLS. The inputs of this function should be `X`, `y`, and `intercept`. `X` (covariables) must be a **pd.DataFrame** and `y` (endog) must be a **pd.Series** and `intercept` can be `True` or `False`, by default `True`. When `intercept` is `False`, the estimated beta does not include **intercept**. Also, you must specify the type of your function's parameters and output and It must raise an error if the inputs do not meet the requirements. The function's output must be a **pd.DataFrame** (`n`, 1) where `n` is the total number of regressors ( it includes the **Intercept** when `intercept` is `True`). The column should be named as **Coef.** and the row index should be named as the original name of the columns in `X` input. Your results should look like `output_example` being `X_input`, `y_input` and `intercept_input` your inputs. Apply your function to find $\widehat{\boldsymbol{\beta}}^{(OLS)}$ of the equation below. Use greene data.  **Hint: Use NumPy to generate the OLS beta and check [this link](https://pandas.pydata.org/docs/reference/api/pandas.DataFrame.set_index.html) to change the index name of a pd.Dataframe, [link](https://notebooks.githubusercontent.com/view/ipynb?browser=chrome&color_mode=auto&commit=69c80e1f2c1c268f0480a32932262201785a576c&device=unknown_device&enc_url=68747470733a2f2f7261772e67697468756275736572636f6e74656e742e636f6d2f616c6578616e6465727175697370652f4469706c6f6d61646f5f505543502f363963383065316632633163323638663034383061333239333232363232303137383561353736632f4c6563747572655f352f4c6563747572655f352e6970796e62&logged_in=true&nwo=alexanderquispe%2FDiplomado_PUCP&path=Lecture_5%2FLecture_5.ipynb&platform=windows&repository_id=427747212&repository_type=Repository&version=96##5.1.7.).**

$$
\widehat{\boldsymbol{\beta}}^{(OLS)} = \left( \mathbf{X}^\top \mathbf{X}\right)^{-1} \mathbf{X}^\top \mathbf{Y}
$$

$$
\begin{aligned} 
lnCT &= \beta_{0}+\beta_{q}lnq+ \beta_{qq}(lnq)^2+\beta_{q1}lnqlnp_1+\beta_{q2}lnqlnp_2+ \beta_{q3}lnqlnp_{3} +\beta_{1}lnp_1+\beta_{2}lnp_2+ \beta_{3}lnp_3 \\
& + \beta_{11}(lnp_{1})^2+ \beta_{22}(lnp_{2})^2+ \beta_{33}(lnp_{3})^2 + \beta_{12}lnp_{1}lnp_{2}+ \beta_{13}lnp_{1}lnp_{3}+\beta_{23}lnp_{2}lnp_{3} 
\end{aligned}
$$

In [3]:
import pandas as pd
import numpy as np
import statsmodels.formula.api as smf

In [4]:
greene = pd.read_csv(r"..\..\_data/christensen_greene_f4.csv")
greene

,id,YEAR,COST,Q,PL,SL,PK,SK,PF,SF
0,1,1970,0.2130,8.0,6869.47,0.3291,64.945,0.4197,18.000,0.2512
1,4,1970,3.0427,869.0,8372.96,0.1030,68.227,0.2913,21.067,0.6057
2,5,1970,9.4059,1412.0,7960.90,0.0891,40.692,0.1567,41.530,0.7542
3,14,1970,0.7606,65.0,8971.89,0.2802,41.243,0.1282,28.539,0.5916
4,15,1970,2.2587,295.0,8218.40,0.1772,71.940,0.1623,39.200,0.6606
...,...,...,...,...,...,...,...,...,...,...
153,214,1970,6.8293,946.6,10642.16,0.0883,43.600,0.1914,51.463,0.7203
154,215,1970,3.7605,377.0,7432.24,0.2117,74.120,0.2274,33.436,0.5609
155,216,1970,3.9822,391.0,5826.04,0.1926,78.288,0.0924,44.633,0.7151
156,217,1970,30.1880,5317.0,9586.63,0.0845,78.008,0.2009,41.840,0.7147
157,218,1970,67.8562,15220.0,6986.09,0.1451,74.025,0.2596,25.662,0.5945

In [5]:
# Defining beta_OLS function  

def beta_ols( X:pd.DataFrame , y:pd.Series, intercept:bool = True):
    
    if not isinstance( X , pd.DataFrame ):
        raise TypeError( "X is not a pd.DataFrame type." )
        
    if not isinstance( y , pd.Series ):
        raise TypeError( "y is not a pd.Series type." )
        
    if not isinstance( intercept , bool ):
        raise TypeError( "intercept is not a boolean type." )
    
    if intercept == True:
        X_new = X.copy() 
        X_new.insert(0, 'intercept', 1)
        beta_ols = np.linalg.inv(X_new.T @ X_new) @ X_new.T @ y 
        beta_ols = pd.DataFrame(beta_ols)
        beta_ols[' '] = X_new.columns.tolist()
        beta_ols.set_index(' ', inplace=True)
        beta_ols.rename(columns = {0:'Coef.'}, inplace=True)
        results = beta_ols
    
    else:
        X_new = X.copy() 
        beta_ols = np.linalg.inv(X_new.T @ X_new) @ X_new.T @ y 
        beta_ols = pd.DataFrame(beta_ols)
        beta_ols[' '] = X_new.columns.tolist()
        beta_ols.set_index(' ', inplace=True)
        beta_ols.rename(columns = {0:'Coef.'}, inplace=True)
        results = beta_ols 
    
    return results

In [6]:
# Defining variables for building Y vector and X covariate matrix

only_cost = greene.COST.values 
only_Q = greene.Q.values 
only_PL = greene.PL.values 
only_PK = greene.PK.values 
only_PF = greene.PF.values

lnct = np.log(only_cost)
lnq = np.log(only_Q)
lnp1 = np.log(only_PL)
lnp2 = np.log(only_PK)
lnp3 = np.log(only_PF)
lnq_2 = np.multiply(lnq,lnq)
lnqlnp1 = np.multiply(lnq,lnp1)
lnqlnp2 = np.multiply(lnq,lnp2)
lnqlnp3 = np.multiply(lnq,lnp3)
lnp1_2 = np.multiply(lnp1,lnp1) 
lnp2_2 = np.multiply(lnp2,lnp2) 
lnp3_2 = np.multiply(lnp3,lnp3) 
lnp1lnp2 = np.multiply (lnp1,lnp2)
lnp1lnp3 = np.multiply (lnp1,lnp3)
lnp2lnp3 = np.multiply (lnp2,lnp3)

In [7]:
# Bulding vector Y_input of dependent variable
y_input = pd.Series(lnct)
y_input

0     -1.546463
1      1.112745
2      2.241337
3     -0.273648
4      0.814789
         ...
153    1.921222
154    1.324552
155    1.381834
156    3.407444
157    4.217391
Length: 158, dtype: float64

In [8]:
# Building covariates matrix (X_input)

X_input = np.hstack(( lnq.reshape( -1, 1 ), lnq_2.reshape( -1, 1 ), lnqlnp1.reshape( -1, 1 ), lnqlnp2.reshape(-1, 1 ), 
                lnqlnp3.reshape( -1, 1 ), lnp1.reshape( -1, 1 ), lnp2.reshape( -1, 1 ), lnp3.reshape(-1, 1 ), lnp1_2.reshape( -1, 1 ), lnp2_2.reshape( -1, 1 ), 
                lnp3_2.reshape( -1, 1 ), lnp1lnp2.reshape(-1, 1 ), lnp1lnp3.reshape(-1, 1 ), lnp2lnp3.reshape(-1, 1 ) ))
X_input = pd.DataFrame(X_input)
X_input.rename(columns = {0:'lnq', 1:'lnq_2', 2:'lnqlnp1', 3:'lnqlnp2', 4:'lnqlnp3', 5:'lnp1', 6:'lnp2', 7:'lnp3', 8:'lnp1_2',
                          9:'lnp2_2', 10:'lnp3_2', 11:'lnp1lnp2', 12:'lnp1lnp3', 13:'lnp2lnp3'}, inplace = True)
intercept_input = True
X_input

,lnq,lnq_2,lnqlnp1,lnqlnp2,lnqlnp3,lnp1,lnp2,lnp3,lnp1_2,lnp2_2,lnp3_2,lnp1lnp2,lnp1lnp3,lnp2lnp3
0,2.079442,4.324077,18.371538,8.678634,6.010359,8.834842,4.173541,2.890372,78.054437,17.418442,8.354249,36.872574,25.535978,12.063084
1,6.767343,45.796933,61.127805,28.577410,20.624885,9.032763,4.222840,3.047708,81.590803,17.832381,9.288523,38.143915,27.529222,12.869984
2,7.252762,52.602563,65.146469,26.878966,27.026810,8.982297,3.706032,3.726416,80.681665,13.734670,13.886177,33.288677,33.471777,13.810215
3,4.174387,17.425509,37.994654,15.526556,13.989505,9.101852,3.719481,3.351272,82.843703,13.834542,11.231021,33.854168,30.502777,12.464992
4,5.686975,32.341689,51.263140,24.316554,20.863674,9.014131,4.275832,3.668677,81.254554,18.282743,13.459189,38.542913,33.069932,15.686647
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
153,6.852877,46.961918,63.543838,25.870001,27.006249,9.272579,3.775057,3.940863,85.980717,14.251056,15.530402,35.004515,36.541963,14.876983
154,5.932245,35.191533,52.877557,25.542382,20.820004,8.913583,4.305685,3.509633,79.451954,18.538927,12.317525,38.379082,31.283405,15.111376
155,5.968708,35.625470,51.749248,26.025919,22.671977,8.670093,4.360394,3.798473,75.170509,19.013039,14.428401,37.805024,32.933118,16.562842
156,8.578665,73.593485,78.650266,37.375623,32.031471,9.168125,4.356811,3.733853,84.054510,18.981805,13.941657,39.943790,34.232428,16.267692
157,9.630366,92.743942,85.244879,41.452974,31.250645,8.851676,4.304403,3.245011,78.352173,18.527884,10.530098,38.101181,28.723790,13.967836

In [9]:
# Applying beta_OLS function 

beta_ols( X_input, y_input, intercept_input )

               Coef.

intercept -76.259258
lnq        -1.080425
lnq_2       0.026489
lnqlnp1     0.131041
lnqlnp2     0.040144
lnqlnp3     0.058652
lnp1       14.718292
lnp2        6.380797
lnp3       -0.894733
lnp1_2     -0.769264
lnp2_2     -0.163707
lnp3_2     -0.036753
lnp1lnp2   -0.572050
lnp1lnp3    0.162283
lnp2lnp3   -0.024025

In [10]:
#Comparing results with OLS fuction 

results_r = smf.ols( 'lnct ~ lnq + lnq_2 + lnqlnp1 + lnqlnp2 + lnqlnp3 + lnp1 + lnp2 + lnp3 + lnp1_2 + lnp2_2 + lnp3_2 + lnp1lnp2 + lnp1lnp3 + lnp2lnp3', 
        data = greene)
X_r = pd.DataFrame(results_r.exog, columns = results_r.exog_names).iloc[ : , 1: ]
y_r = pd.Series(results_r.endog , name = results_r.endog_names )
intercept_r = True
beta_OLS_output_r = results_r.fit().summary2().tables[1].iloc[ :, [0]]
beta_OLS_output_r

               Coef.
Intercept -76.259261
lnq        -1.080425
lnq_2       0.026489
lnqlnp1     0.131041
lnqlnp2     0.040144
lnqlnp3     0.058652
lnp1       14.718293
lnp2        6.380797
lnp3       -0.894733
lnp1_2     -0.769264
lnp2_2     -0.163707
lnp3_2     -0.036753
lnp1lnp2   -0.572050
lnp1lnp3    0.162283
lnp2lnp3   -0.024025

2. Generate a new function named **var_OLS**. This function must return the estimated variance for OLS. The inputs of this function should be `X`, `y`, and `intercept`. `X` (covariables) must be a **pd.DataFrame** and `y` (endog) must be a **pd.Series** and `intercept` can be `True` or `False`, by default `True`. When `intercept` is `False`, the estimated variance does not include **intercept** in the `X` regressor. Also, you must specify the type of your function's parameters and output and It must raise an error if the inputs do not meet the requirements. The output of the function should look like `var_ols` where the columns and the index use the name of `X` columns.  Apply your function to find $\mathbb{V}{\rm ar} (\widehat{\boldsymbol{\beta}}^{(OLS)})$ of the equation below. Use greene data.  **Hint: Use numpy, `def` function, and `columns` method, [link](https://notebooks.githubusercontent.com/view/ipynb?browser=chrome&color_mode=auto&commit=69c80e1f2c1c268f0480a32932262201785a576c&device=unknown_device&enc_url=68747470733a2f2f7261772e67697468756275736572636f6e74656e742e636f6d2f616c6578616e6465727175697370652f4469706c6f6d61646f5f505543502f363963383065316632633163323638663034383061333239333232363232303137383561353736632f4c6563747572655f352f4c6563747572655f352e6970796e62&logged_in=true&nwo=alexanderquispe%2FDiplomado_PUCP&path=Lecture_5%2FLecture_5.ipynb&platform=windows&repository_id=427747212&repository_type=Repository&version=96##5.1.7.).**


$$
\begin{aligned}
\mathbb{V}{\rm ar} (\widehat{\boldsymbol{\beta}}^{(OLS)}) = 
\sigma^2 \left( \mathbf{X}^\top  \mathbf{X}\right)^{-1}
\end{aligned}
$$

$$
\begin{aligned} 
lnCT &= \beta_{0}+\beta_{q}lnq+ \beta_{qq}(lnq)^2+\beta_{q1}lnqlnp_1+\beta_{q2}lnqlnp_2+ \beta_{q3}lnqlnp_{3} +\beta_{1}lnp_1+\beta_{2}lnp_2+ \beta_{3}lnp_3 \\
& + \beta_{11}(lnp_{1})^2+ \beta_{22}(lnp_{2})^2+ \beta_{33}(lnp_{3})^2 + \beta_{12}lnp_{1}lnp_{2}+ \beta_{13}lnp_{1}lnp_{3}+\beta_{23}lnp_{2}lnp_{3} 
\end{aligned}
$$

In [11]:
# Defining var_OLS function  

def var_ols( X:pd.DataFrame , y:pd.Series, intercept:bool = True) -> pd.DataFrame:
    
    if not isinstance( X , pd.DataFrame ):
        raise TypeError( "X is not a pd.DataFrame type." )
        
    if not isinstance( y , pd.Series ):
        raise TypeError( "y is not a pd.Series type." )
        
    if not isinstance( intercept , bool ):
        raise TypeError( "intercept is not a boolean type." )
    
    if intercept == True:
        X_new = X.copy() 
        X_new.insert(0, 'intercept', 1) 
        names = X_new.columns.tolist()
        beta_est = beta_ols( X, y, intercept)   ### Estimating parameters
        y_pred = X_new @ beta_est               ### Calculating predicted values
        y_pred = y_pred.squeeze()
        n_data = X_new.shape[0]
        k_param = X_new.shape[1]
        sr2 = ( (1 / (n_data - k_param)) * (y_pred - y).T  @ (y_pred - y)) ### Calculating the variance of the regression
        var_beta = sr2*np.linalg.inv(X_new.T @ X_new)                ### Getting variance and covariance Matrix
        var_beta = pd.DataFrame(var_beta, columns=names)
        var_beta[' '] = names
        var_beta.set_index(' ', inplace=True)
        
    else:
        X_new = X.copy() 
        names = X_new.columns.tolist()
        beta_est = beta_ols( X, y, intercept)   ## Estimating parameters
        y_pred = X_new @ beta_est               ## Calculating predicted values
        y_pred = y_pred.squeeze()
        n_data = X_new.shape[0]
        k_param = X_new.shape[1]
        sr2 = ( (1 / (n_data - k_param)) * (y_pred - y).T  @ (y_pred - y)) ## Calculating the variance of the regression
        var_beta = sr2*np.linalg.inv(X_new.T @ X_new)  #### Getting variance and covariance Matrix
        var_beta = pd.DataFrame(var_beta, columns=names)
        var_beta[' '] = names
        var_beta.set_index(' ', inplace=True)
        
    results = var_beta
   
    return results

In [12]:
# Applying var_ols function 

var_ols(X_input, y_input, intercept = True)

,intercept,lnq,lnq_2,lnqlnp1,lnqlnp2,lnqlnp3,lnp1,lnp2,lnp3,lnp1_2,lnp2_2,lnp3_2,lnp1lnp2,lnp1lnp3,lnp2lnp3
,,,,,,,,,,,,,,,
intercept,1465.361102,0.192537,-0.011698,-0.026677,0.039538,0.015949,-262.932563,-128.192044,-8.392679,11.880856,3.540639,-0.266944,10.902440,0.990253,0.197435
lnq,0.192537,0.141034,0.000308,-0.013459,-0.006089,0.000161,-0.186223,-0.090714,0.148320,0.015321,-0.000898,0.000381,0.017546,-0.015046,-0.003570
lnq_2,-0.011698,0.000308,0.000006,-0.000036,-0.000011,-0.000005,0.001491,0.000862,0.001052,-0.000043,-0.000060,0.000013,-0.000014,-0.000099,-0.000048
lnqlnp1,-0.026677,-0.013459,-0.000036,0.001466,0.000348,-0.000168,0.021561,0.005430,-0.015127,-0.001961,0.000285,0.000019,-0.001141,0.001850,-0.000085
lnqlnp2,0.039538,-0.006089,-0.000011,0.000348,0.000888,-0.000189,-0.000337,0.000268,-0.008853,0.000211,-0.000067,-0.000033,-0.001537,0.000102,0.002212
lnqlnp3,0.015949,0.000161,-0.000005,-0.000168,-0.000189,0.000653,-0.008293,0.008035,0.003306,0.000587,-0.000103,-0.000170,-0.000144,-0.000170,-0.001375
lnp1,-262.932563,-0.186223,0.001491,0.021561,-0.000337,-0.008293,50.194721,19.099542,-1.253531,-2.388986,-0.420154,0.070493,-1.788158,0.038416,0.132157
lnp2,-128.192044,-0.090714,0.000862,0.005430,0.000268,0.008035,19.099542,20.513714,-0.214871,-0.705214,-0.763050,0.023665,-1.555553,0.036229,-0.072591
lnp3,-8.392679,0.148320,0.001052,-0.015127,-0.008853,0.003306,-1.253531,-0.214871,8.078742,0.161643,-0.033147,-0.058647,0.199482,-0.685050,-0.367388
lnp1_2,11.880856,0.015321,-0.000043,-0.001961,0.000211,0.000587,-2.388986,-0.705214,0.161643,0.119855,0.011353,-0.003079,0.070381,-0.013413,-0.006656
lnp2_2,3.540639,-0.000898,-0.000060,0.000285,-0.000067,-0.000103,-0.420154,-0.763050,-0.033147,0.011353,0.048556,-0.002049,0.043314,0.008386,-0.006653
lnp3_2,-0.266944,0.000381,0.000013,0.000019,-0.000033,-0.000170,0.070493,0.023665,-0.058647,-0.003079,-0.002049,0.008285,-0.002485,-0.001552,0.004467
lnp1lnp2,10.902440,0.017546,-0.000014,-0.001141,-0.001537,-0.000144,-1.788158,-1.555553,0.199482,0.070381,0.043314,-0.002485,0.138302,-0.015413,-0.010534
lnp1lnp3,0.990254,-0.015046,-0.000099,0.001850,0.000102,-0.000170,0.038416,0.036229,-0.685050,-0.013413,0.008386,-0.001552,-0.015413,0.072939,0.009949
lnp2lnp3,0.197435,-0.003570,-0.000048,-0.000085,0.002212,-0.001375,0.132157,-0.072591,-0.367388,-0.006656,-0.006653,0.004467,-0.010534,0.009949,0.060678

In [13]:
# Comparing results with results_code

var_OLS_output = results_r.fit().cov_params()
var_OLS_output

,Intercept,lnq,lnq_2,lnqlnp1,lnqlnp2,lnqlnp3,lnp1,lnp2,lnp3,lnp1_2,lnp2_2,lnp3_2,lnp1lnp2,lnp1lnp3,lnp2lnp3
Intercept,1465.361176,0.192537,-0.011698,-0.026677,0.039538,0.015949,-262.932577,-128.192050,-8.392679,11.880857,3.540639,-0.266944,10.902441,0.990253,0.197435
lnq,0.192537,0.141034,0.000308,-0.013459,-0.006089,0.000161,-0.186223,-0.090714,0.148320,0.015321,-0.000898,0.000381,0.017546,-0.015046,-0.003570
lnq_2,-0.011698,0.000308,0.000006,-0.000036,-0.000011,-0.000005,0.001491,0.000862,0.001052,-0.000043,-0.000060,0.000013,-0.000014,-0.000099,-0.000048
lnqlnp1,-0.026677,-0.013459,-0.000036,0.001466,0.000348,-0.000168,0.021561,0.005430,-0.015127,-0.001961,0.000285,0.000019,-0.001141,0.001850,-0.000085
lnqlnp2,0.039538,-0.006089,-0.000011,0.000348,0.000888,-0.000189,-0.000337,0.000268,-0.008853,0.000211,-0.000067,-0.000033,-0.001537,0.000102,0.002212
lnqlnp3,0.015949,0.000161,-0.000005,-0.000168,-0.000189,0.000653,-0.008293,0.008035,0.003306,0.000587,-0.000103,-0.000170,-0.000144,-0.000170,-0.001375
lnp1,-262.932577,-0.186223,0.001491,0.021561,-0.000337,-0.008293,50.194723,19.099543,-1.253531,-2.388986,-0.420154,0.070493,-1.788158,0.038416,0.132157
lnp2,-128.192050,-0.090714,0.000862,0.005430,0.000268,0.008035,19.099543,20.513715,-0.214871,-0.705214,-0.763050,0.023665,-1.555553,0.036229,-0.072591
lnp3,-8.392679,0.148320,0.001052,-0.015127,-0.008853,0.003306,-1.253531,-0.214871,8.078742,0.161643,-0.033147,-0.058647,0.199482,-0.685050,-0.367388
lnp1_2,11.880857,0.015321,-0.000043,-0.001961,0.000211,0.000587,-2.388986,-0.705214,0.161643,0.119855,0.011353,-0.003079,0.070381,-0.013413,-0.006656
lnp2_2,3.540639,-0.000898,-0.000060,0.000285,-0.000067,-0.000103,-0.420154,-0.763050,-0.033147,0.011353,0.048556,-0.002049,0.043314,0.008386,-0.006653
lnp3_2,-0.266944,0.000381,0.000013,0.000019,-0.000033,-0.000170,0.070493,0.023665,-0.058647,-0.003079,-0.002049,0.008285,-0.002485,-0.001552,0.004467
lnp1lnp2,10.902441,0.017546,-0.000014,-0.001141,-0.001537,-0.000144,-1.788158,-1.555553,0.199482,0.070381,0.043314,-0.002485,0.138302,-0.015413,-0.010534
lnp1lnp3,0.990253,-0.015046,-0.000099,0.001850,0.000102,-0.000170,0.038416,0.036229,-0.685050,-0.013413,0.008386,-0.001552,-0.015413,0.072939,0.009949
lnp2lnp3,0.197435,-0.003570,-0.000048,-0.000085,0.002212,-0.001375,0.132157,-0.072591,-0.367388,-0.006656,-0.006653,0.004467,-0.010534,0.009949,0.060678

3. Generate a new function named as `reg_OLS` that uses your previos functions `beta_OLS` and `var_OLS` to return an ouput similar to `reg_OLS_output`. The inputs of this function should be `X`, `y`, and `intercept`. `X` (covariables) must be a **pd.DataFrame** and `y` (endog) must be a **pd.Series** and `intercept` can be `True` or `False`, by default `True`. When `intercept` is `False`, the output does not include **intercept**. Also, you must specify the type of your function's parameters and output and It must raise an error if the inputs do not meet the requirements. Apply your function to the equation below. Use greene data.**Hint: Use numpy, `def` function, and `columns` method, [link](https://notebooks.githubusercontent.com/view/ipynb?browser=chrome&color_mode=auto&commit=69c80e1f2c1c268f0480a32932262201785a576c&device=unknown_device&enc_url=68747470733a2f2f7261772e67697468756275736572636f6e74656e742e636f6d2f616c6578616e6465727175697370652f4469706c6f6d61646f5f505543502f363963383065316632633163323638663034383061333239333232363232303137383561353736632f4c6563747572655f352f4c6563747572655f352e6970796e62&logged_in=true&nwo=alexanderquispe%2FDiplomado_PUCP&path=Lecture_5%2FLecture_5.ipynb&platform=windows&repository_id=427747212&repository_type=Repository&version=96##5.1.7.).**

$$
\begin{aligned} 
lnCT &= \beta_{0}+\beta_{q}lnq+ \beta_{qq}(lnq)^2+\beta_{q1}lnqlnp_1+\beta_{q2}lnqlnp_2+ \beta_{q3}lnqlnp_{3} +\beta_{1}lnp_1+\beta_{2}lnp_2+ \beta_{3}lnp_3 \\
& + \beta_{11}(lnp_{1})^2+ \beta_{22}(lnp_{2})^2+ \beta_{33}(lnp_{3})^2 + \beta_{12}lnp_{1}lnp_{2}+ \beta_{13}lnp_{1}lnp_{3}+\beta_{23}lnp_{2}lnp_{3} 
\end{aligned}
$$

In [14]:
# Defining reg_OLS function  

from scipy.stats import t
def reg_ols( X:pd.DataFrame , y:pd.Series, intercept:bool = True) -> pd.DataFrame:

    if not isinstance( X , pd.DataFrame ):
        raise TypeError( "X is not a pd.DataFrame type." )
        
    if not isinstance( y , pd.Series ):
        raise TypeError( "y is not a pd.Series type." )
        
    if not isinstance( intercept , bool ):
        raise TypeError( "intercept is not a boolean type." )
    
    if intercept == True:
        X_new = X.copy() 
        X_new.insert(0, 'intercept', 1) 
        names = X_new.columns.tolist()
        n_data = X_new.shape[0]
        k_param = X_new.shape[1]
        
        beta_est = beta_ols( X, y, intercept )   ### Estimating parameters
        beta_est.reset_index(inplace=True)
        var_beta = var_ols( X, y, intercept )   ### Estimating variance and covariance matrix
        stand_error = pd.DataFrame(np.sqrt(np.diag(var_beta)), columns= ['Std.Err'])  ## Extracting standard error of parameters
        resume_df = pd.concat([beta_est, stand_error], axis=1)
        resume_df['t'] = resume_df['Coef.']/resume_df['Std.Err']     ### Computing t value
        resume_df['P>|t|'] = 1 - 2*np.abs(0.5 - np.vectorize(t.cdf)(resume_df['t'], n_data-k_param-1))    ### Computing p-value
        resume_df['0.025'] = resume_df['Coef.'] - resume_df['Std.Err']*t.ppf( q = 1 - 0.05 / 2, df = n_data - k_param ) ### Computing lower interval
        resume_df['0.975'] = resume_df['Coef.'] + resume_df['Std.Err']*t.ppf( q = 1 - 0.05 / 2, df = n_data - k_param ) ### Computing upper interval
        resume_df[' '] = names
        resume_df.set_index(' ', inplace=True)
        
    else:
        X_new = X.copy() 
        names = X_new.columns.tolist()
        n_data = X_new.shape[0]
        k_param = X_new.shape[1]
        
        beta_est = beta_ols( X, y, intercept )   ### Estimating parameters
        beta_est.reset_index(inplace=True)
        var_beta = var_ols( X, y, intercept )   ### Estimating variance and covariance matrix
        stand_error = pd.DataFrame(np.sqrt(np.diag(var_beta)), columns= ['Std.Err'])  ## Extracting standard error of parameters
        resume_df = pd.concat([beta_est, stand_error], axis=1)
        resume_df['t'] = resume_df['Coef.']/resume_df['Std.Err']     ### Computing t value
        resume_df['P>|t|'] = 1 - 2*np.abs(0.5 - np.vectorize(t.cdf)(resume_df['t'], n_data-k_param-1))    ### Computing p-value
        resume_df['0.025'] = resume_df['Coef.'] - resume_df['Std.Err']*t.ppf( q = 1 - 0.05 / 2, df = n_data - k_param ) ### Computing lower interval
        resume_df['0.975'] = resume_df['Coef.'] + resume_df['Std.Err']*t.ppf( q = 1 - 0.05 / 2, df = n_data - k_param ) ### Computing upper interval
        resume_df[' '] = names
        resume_df.set_index(' ', inplace=True)
        
    results = resume_df
   
    return results

In [15]:
reg_ols(X_input, y_input, intercept = True)

               Coef.    Std.Err          t     P>|t|       0.025      0.975

intercept -76.259258  38.280035  -1.992142  0.048273 -151.927105  -0.591411
lnq        -1.080425   0.375545  -2.876952  0.004635   -1.822762  -0.338088
lnq_2       0.026489   0.002357  11.240060  0.000000    0.021831   0.031148
lnqlnp1     0.131041   0.038284   3.422854  0.000810    0.055365   0.206716
lnqlnp2     0.040144   0.029791   1.347518  0.179960   -0.018744   0.099033
lnqlnp3     0.058652   0.025549   2.295650  0.023160    0.008149   0.109155
lnp1       14.718292   7.084823   2.077440  0.039562    0.713777  28.722807
lnp2        6.380797   4.529207   1.408811  0.161077   -2.572051  15.333644
lnp3       -0.894733   2.842313  -0.314790  0.753383   -6.513110   4.723645
lnp1_2     -0.769264   0.346201  -2.222011  0.027865   -1.453597  -0.084930
lnp2_2     -0.163707   0.220354  -0.742927  0.458753   -0.599280   0.271866
lnp3_2     -0.036753   0.091019  -0.403791  0.686974   -0.216670   0.143165
lnp1lnp2   -0.572050   0.371890  -1.538224  0.126219   -1.307163   0.163062
lnp1lnp3    0.162283   0.270072   0.600888  0.548873   -0.371566   0.696132
lnp2lnp3   -0.024025   0.246329  -0.097531  0.922442   -0.510942   0.462892

4. Generate a new function named as `restricted_OLS` that uses your previos functions `beta_OLS` and `var_OLS` to return an ouput similar to `reg_OLS_output`. The inputs of this function should be `X`, `y`,  `L`, `r`, and `intercept`. `X` (covariables) must be a **pd.DataFrame** and `y` (endog) must be a **pd.Series**,  `L` (coef) must be a **np.array**, `r` must be a **np.array**,  and `intercept` can be `True` or `False`.  When `intercept` is `False`, the estimated beta does not include **intercept**. Also, you must specify the type of your function's parameters and output and It must raise an error if the inputs do not meet the requirements. The ouput of this function should look like `reg_OLS_ouput`. Apply your function to the equation below. Use greene data.
 **Hint: Use numpy, `def` function, and `columns` method, [link](https://notebooks.githubusercontent.com/view/ipynb?browser=chrome&color_mode=auto&commit=69c80e1f2c1c268f0480a32932262201785a576c&device=unknown_device&enc_url=68747470733a2f2f7261772e67697468756275736572636f6e74656e742e636f6d2f616c6578616e6465727175697370652f4469706c6f6d61646f5f505543502f363963383065316632633163323638663034383061333239333232363232303137383561353736632f4c6563747572655f352f4c6563747572655f352e6970796e62&logged_in=true&nwo=alexanderquispe%2FDiplomado_PUCP&path=Lecture_5%2FLecture_5.ipynb&platform=windows&repository_id=427747212&repository_type=Repository&version=96##5.1.7.).**

$$
\hat{\boldsymbol{\beta}}^{(RLS)} =\hat{\boldsymbol{\beta}}^{(OLS)} - \left( \boldsymbol{X}^\top \boldsymbol{X} \right)^{-1} \boldsymbol{L}^\top \left( \boldsymbol{L}\left( \boldsymbol{X}^\top \boldsymbol{X} \right)^{-1} \boldsymbol{L}^\top \right)^{-1} \left( \boldsymbol{L}\widehat{\boldsymbol{\beta}}^{(OLS)} - \boldsymbol{r} \right)
$$

$$
\begin{aligned}
\mathbb{V}{\rm ar} \left(\widehat{\boldsymbol{\beta}}^{(RLS)} \right) 
&= \sigma^2 \left( \mathbf{X}^\top  \mathbf{X}\right)^{-1} - \sigma^2 \left( \mathbf{X}^\top  \mathbf{X}\right)^{-1}  \mathbf{L}^\top \left( \mathbf{L}\left( \mathbf{X}^\top \mathbf{X} \right)^{-1} \mathbf{L}^\top \right)^{-1}  \mathbf{L} \left( \mathbf{X}^\top  \mathbf{X}\right)^{-1}
\end{aligned}
$$

$$
\begin{aligned} 
lnCT &= \beta_{0}+\beta_{q}lnq+ \beta_{qq}(lnq)^2+\beta_{q1}lnqlnp_1+\beta_{q2}lnqlnp_2+ \beta_{q3}lnqlnp_{3} +\beta_{1}lnp_1+\beta_{2}lnp_2+ \beta_{3}lnp_3 \\
& + \beta_{11}(lnp_{1})^2+ \beta_{22}(lnp_{2})^2+ \beta_{33}(lnp_{3})^2 + \beta_{12}lnp_{1}lnp_{2}+ \beta_{13}lnp_{1}lnp_{3}+\beta_{23}lnp_{2}lnp_{3} 
\end{aligned}
$$

ST: 

<br>
$$
\begin{aligned} 
\beta_{1} + \beta_{2} + \beta_{3} &= 1 \\
\beta_{q1} + \beta_{q2} + \beta_{q3} &= 0 \\
\beta_{11} + \beta_{12} + \beta_{13} &= 0 \\
\beta_{21} + \beta_{22} + \beta_{23} &= 0 \\
\beta_{31} + \beta_{32} + \beta_{33} &= 0 \\
\beta_{ij} = \beta_{ji}
\end{aligned}
$$

In [57]:
# Defining restricted_OLS function  

from scipy.stats import t
def restricted_OLS( X:pd.DataFrame , y:pd.Series, L:np.array, r:np.array, intercept:bool = True) -> pd.DataFrame:

    if not isinstance( X , pd.DataFrame ):
        raise TypeError( "X is not a pd.DataFrame type." )
        
    if not isinstance( y , pd.Series ):
        raise TypeError( "y is not a pd.Series type." )
        
    if not isinstance( L ,np.ndarray ):
        raise TypeError( "L is not a array type." )
        
    if not isinstance( r , np.ndarray):
        raise TypeError( "r is not a array type." )
        
    if not isinstance( intercept , bool ):
        raise TypeError( "intercept is not a boolean type." )
    
    if intercept == True:
        X_new = X.copy() 
        X_new.insert(0, 'intercept', 1) 
        L_new = L.copy() 
        L_new = np.append([[0],[0],[0],[0],[0]],L_new, axis = 1)
        r_new = r.copy() 
        names = X_new.columns.tolist()
        n_data = X_new.shape[0]
        k_param = X_new.shape[1]
        M_restric = L_new.shape[0]
        
        # RLS estimation
        beta_est = beta_ols( X, y, intercept )   ### Estimating parameters using OLS
        beta_est = beta_est.squeeze()
        beta_est_restric = beta_est - np.linalg.inv(X_new.T @ X_new) @ L_new.T@ np.linalg.inv(L_new @ (np.linalg.inv(X_new.T @ X_new)) @ L_new.T)@(L_new @ beta_est - r_new )   
        beta_est_restric = pd.DataFrame(beta_est_restric)
        
        # Variance and covariance Matrix of RLS estimation
        y_pred = X_new @ beta_est_restric               ### Calculating predicted values
        y_pred = y_pred.squeeze()
        sr2 = ( (1 / (n_data - (k_param + 1 - M_restric))) * (y_pred - y).T  @ (y_pred - y)) ### Calculating the variance of the regression
        var_rls_beta = sr2*np.linalg.inv(X_new.T @ X_new) - sr2*np.linalg.inv(X_new.T @ X_new)@ L_new.T@ np.linalg.inv((L_new @ np.linalg.inv(X_new.T @ X_new) @ L_new.T)) @ L_new @ np.linalg.inv(X_new.T @ X_new)  ### Getting variance and covariance Matrix
        var_rls_beta = pd.DataFrame(var_rls_beta, columns=names)
        var_rls_beta[' '] = names
        var_rls_beta.set_index(' ', inplace=True)
        
        beta_est_restric.reset_index(inplace=True)
        stand_error = pd.DataFrame(np.sqrt(np.diag(var_rls_beta)), columns= ['Std.Err'])  ## Extracting standard error of parameters
        resume_df = pd.concat([beta_est_restric, stand_error], axis=1)
        resume_df['t'] = resume_df['Coef.']/resume_df['Std.Err']     ### Computing t value
        resume_df['P>|t|'] = 1 - 2*np.abs(0.5 - np.vectorize(t.cdf)(resume_df['t'], n_data-k_param-1))    ### Computing p-value
        resume_df['0.025'] = resume_df['Coef.'] - resume_df['Std.Err']*t.ppf( q = 1 - 0.05 / 2, df = n_data - k_param ) ### Computing lower interval
        resume_df['0.975'] = resume_df['Coef.'] + resume_df['Std.Err']*t.ppf( q = 1 - 0.05 / 2, df = n_data - k_param ) ### Computing upper interval
        resume_df[' '] = names
        resume_df.set_index(' ', inplace=True)
        
    else:
        X_new = X.copy() 
        L_new = L.copy() 
        r_new = r.copy() 
        names = X_new.columns.tolist()
        n_data = X_new.shape[0]
        k_param = X_new.shape[1]
        M_restric = L_new.shape[0]
        
        # RLS estimation
        beta_est = beta_ols( X, y, intercept )   ### Estimating parameters using OLS
        beta_est = beta_est.squeeze()
        beta_est_restric = beta_est - np.linalg.inv(X_new.T @ X_new) @ L_new.T@ np.linalg.inv(L_new @ (np.linalg.inv(X_new.T @ X_new)) @ L_new.T)@(L_new @ beta_est - r_new )   
        beta_est_restric = pd.DataFrame(beta_est_restric)
        
        # Variance and covariance Matrix of RLS estimation
        y_pred = X_new @ beta_est_restric               ### Calculating predicted values
        y_pred = y_pred.squeeze()
        sr2 = ( (1 / (n_data - (k_param + 1 - M_restric))) * (y_pred - y).T  @ (y_pred - y)) ### Calculating the variance of the regression
        var_rls_beta = sr2*np.linalg.inv(X_new.T @ X_new) - sr2*np.linalg.inv(X_new.T @ X_new)@ L_new.T@ np.linalg.inv((L_new @ np.linalg.inv(X_new.T @ X_new) @ L_new.T)) @ L_new @ np.linalg.inv(X_new.T @ X_new)  ### Getting variance and covariance Matrix
        var_rls_beta = pd.DataFrame(var_rls_beta, columns=names)
        var_rls_beta[' '] = names
        var_rls_beta.set_index(' ', inplace=True)
        
        beta_est_restric.reset_index(inplace=True)
        stand_error = pd.DataFrame(np.sqrt(np.diag(var_rls_beta)), columns= ['Std.Err'])  ## Extracting standard error of parameters
        resume_df = pd.concat([beta_est_restric, stand_error], axis=1)
        resume_df['t'] = resume_df['Coef.']/resume_df['Std.Err']     ### Computing t value
        resume_df['P>|t|'] = 1 - 2*np.abs(0.5 - np.vectorize(t.cdf)(resume_df['t'], n_data-k_param-1))    ### Computing p-value
        resume_df['0.025'] = resume_df['Coef.'] - resume_df['Std.Err']*t.ppf( q = 1 - 0.05 / 2, df = n_data - k_param ) ### Computing lower interval
        resume_df['0.975'] = resume_df['Coef.'] + resume_df['Std.Err']*t.ppf( q = 1 - 0.05 / 2, df = n_data - k_param ) ### Computing upper interval
        resume_df[' '] = names
        resume_df.set_index(' ', inplace=True)
        
    results = resume_df
   
    return results, beta_est_restric, var_rls_beta

In [76]:
# Restriction matrix and vector 

rest_1 = np.array([0,0,0,0,0,1,1,1,0,0,0,0,0,0])
rest_2 = np.array([0,0,1,1,1,0,0,0,0,0,0,0,0,0])
rest_3 = np.array([0,0,0,0,0,0,0,0,1,0,0,1,1,0])
rest_4 = np.array([0,0,0,0,0,0,0,0,0,1,0,1,0,1])
rest_5 = np.array([0,0,0,0,0,0,0,0,0,0,1,0,1,1])

L_input = np.vstack(( rest_1, rest_2, rest_3, rest_4, rest_5 ))
r_input = np.array([1,0,0,0,0])

In [60]:
# Applying restricted_OLS function 

results_restric_OLS , beta_restric_OLS, var_restric_OLS = restricted_OLS(X_input, y_input, L_input, r_input, intercept = True)
results_restric_OLS

              Coef.   Std.Err          t     P>|t|      0.025     0.975

intercept -7.111200  2.922948  -2.432887  0.016223 -12.888968 -1.333433
lnq        0.461368  0.126980   3.633395  0.000390   0.210368  0.712368
lnq_2      0.029978  0.002249  13.326792  0.000000   0.025531  0.034424
lnqlnp1   -0.004354  0.024268  -0.179432  0.857854  -0.052324  0.043615
lnqlnp2   -0.032424  0.022718  -1.427250  0.155703  -0.077329  0.012482
lnqlnp3    0.036778  0.025669   1.432801  0.154113  -0.013961  0.087517
lnp1       0.215566  1.076755   0.200200  0.841611  -1.912847  2.343980
lnp2       0.381511  0.563529   0.677003  0.499505  -0.732412  1.495434
lnp3       0.402923  0.587760   0.685523  0.494131  -0.758897  1.564743
lnp1_2    -0.004356  0.074754  -0.058273  0.953613  -0.152121  0.143409
lnp2_2    -0.007651  0.159262  -0.048039  0.961752  -0.322462  0.307160
lnp3_2     0.002578  0.085027   0.030318  0.975856  -0.165494  0.170649
lnp1lnp2   0.007292  0.078128   0.093339  0.925765  -0.147142  0.161727
lnp1lnp3  -0.002936  0.120770  -0.024313  0.980637  -0.241661  0.235788
lnp2lnp3   0.000358  0.122739   0.002920  0.997674  -0.242258  0.242975

5. Generate a new class named `RegClass`. The initial attributes of your class must be `X`, `y`, and `intercept`. `X` (covariables) must be a **pd.DataFrame** and `y` (endog) must be a **pd.Series** and `intercept` can be `True` or `False`, by default `True`. Also, you must specify the type of your class' parameters, and output and It must raise an error if the inputs do not meet the requirements.  This class should have two methods: `reg_OLS` and `restricted_OLS` (You can add more if you think it is necessary). These methods should return the same output as the previously defined functions with the same name. The method `reg_OLS` does not need an extra parameter to be executed. After executing the method `reg_OLS`, any user should access the following attributes: `beta_OLS` and `var_OLS`. They should look like `beta_OLS_output` and `var_OLS_output`. The `restricted_OLS` method needs two extra parameters before being executed, `L` and `r`. They refer to the restrictions. After running the method `restricted_OLS`, any user should access the following attributes: `beta_OLS`, `var_OLS`, `rest_beta_OLS`, and `rest_var_OLS`. These attributes refer to the beta and variance estimated using OLS and restricted OLS. They should look like  `beta_OLS_output` and `var_OLS_output`. Fix all the methods and attributes. No user should be able to change them. **Hint: Use [lecture 6](https://notebooks.githubusercontent.com/view/ipynb?browser=chrome&color_mode=auto&commit=69c80e1f2c1c268f0480a32932262201785a576c&device=unknown_device&enc_url=68747470733a2f2f7261772e67697468756275736572636f6e74656e742e636f6d2f616c6578616e6465727175697370652f4469706c6f6d61646f5f505543502f363963383065316632633163323638663034383061333239333232363232303137383561353736632f4c6563747572655f362f4c6563747572655f362e6970796e62&logged_in=true&nwo=alexanderquispe%2FDiplomado_PUCP&path=Lecture_6%2FLecture_6.ipynb&platform=windows&repository_id=427747212&repository_type=Repository&version=96#6.3.).**

In [98]:
#Class object
class Regclass(object):
    #Atributes
    __slots__ = [ 'X', 'y', 'L', 'r', 'intercept', 'beta_OLS', 'var_OLS', 'rest_beta_OLS', 'rest_var_OLS', ]

    #Outputs
    def __init__( self, X : pd.DataFrame, y : pd.Series, L: np.ndarray , r: np.ndarray, intercept = True ):

        self.X = X
        self.y = y
        self.L = L
        self.r = r
        self.intercept = intercept     
        
    def reg_OLS( self ):
        
        self.beta_OLS = beta_ols( self.X, self.y, intercept = self.intercept)
        self.var_OLS = var_ols( self.X, self.y, intercept = self.intercept)
    
        return self.beta_OLS, self.var_OLS    
        
    def restricted_OLS( self, L : np.ndarray, r : np.ndarray, ):
      
        reg_OLS_r, self.rest_beta_OLS, self.rest_var_OLS = restricted_OLS(self.X, self.y, self.L, self.r, intercept = self.intercept )
        self.rest_beta_OLS = self.rest_beta_OLS
        self.rest_beta_OLS.set_index(' ', inplace=True)
        
        return self.rest_beta_OLS, self.rest_var_OLS

In [99]:
# Computing results

regression = Regclass( X_input, y_input, L_input, r_input, intercept_input )
regression.reg_OLS()[0]

               Coef.

intercept -76.259258
lnq        -1.080425
lnq_2       0.026489
lnqlnp1     0.131041
lnqlnp2     0.040144
lnqlnp3     0.058652
lnp1       14.718292
lnp2        6.380797
lnp3       -0.894733
lnp1_2     -0.769264
lnp2_2     -0.163707
lnp3_2     -0.036753
lnp1lnp2   -0.572050
lnp1lnp3    0.162283
lnp2lnp3   -0.024025

In [100]:
regression = Regclass( X_input, y_input, L_input, r_input, intercept_input )
regression.reg_OLS()[1]

,intercept,lnq,lnq_2,lnqlnp1,lnqlnp2,lnqlnp3,lnp1,lnp2,lnp3,lnp1_2,lnp2_2,lnp3_2,lnp1lnp2,lnp1lnp3,lnp2lnp3
,,,,,,,,,,,,,,,
intercept,1465.361102,0.192537,-0.011698,-0.026677,0.039538,0.015949,-262.932563,-128.192044,-8.392679,11.880856,3.540639,-0.266944,10.902440,0.990253,0.197435
lnq,0.192537,0.141034,0.000308,-0.013459,-0.006089,0.000161,-0.186223,-0.090714,0.148320,0.015321,-0.000898,0.000381,0.017546,-0.015046,-0.003570
lnq_2,-0.011698,0.000308,0.000006,-0.000036,-0.000011,-0.000005,0.001491,0.000862,0.001052,-0.000043,-0.000060,0.000013,-0.000014,-0.000099,-0.000048
lnqlnp1,-0.026677,-0.013459,-0.000036,0.001466,0.000348,-0.000168,0.021561,0.005430,-0.015127,-0.001961,0.000285,0.000019,-0.001141,0.001850,-0.000085
lnqlnp2,0.039538,-0.006089,-0.000011,0.000348,0.000888,-0.000189,-0.000337,0.000268,-0.008853,0.000211,-0.000067,-0.000033,-0.001537,0.000102,0.002212
lnqlnp3,0.015949,0.000161,-0.000005,-0.000168,-0.000189,0.000653,-0.008293,0.008035,0.003306,0.000587,-0.000103,-0.000170,-0.000144,-0.000170,-0.001375
lnp1,-262.932563,-0.186223,0.001491,0.021561,-0.000337,-0.008293,50.194721,19.099542,-1.253531,-2.388986,-0.420154,0.070493,-1.788158,0.038416,0.132157
lnp2,-128.192044,-0.090714,0.000862,0.005430,0.000268,0.008035,19.099542,20.513714,-0.214871,-0.705214,-0.763050,0.023665,-1.555553,0.036229,-0.072591
lnp3,-8.392679,0.148320,0.001052,-0.015127,-0.008853,0.003306,-1.253531,-0.214871,8.078742,0.161643,-0.033147,-0.058647,0.199482,-0.685050,-0.367388
lnp1_2,11.880856,0.015321,-0.000043,-0.001961,0.000211,0.000587,-2.388986,-0.705214,0.161643,0.119855,0.011353,-0.003079,0.070381,-0.013413,-0.006656
lnp2_2,3.540639,-0.000898,-0.000060,0.000285,-0.000067,-0.000103,-0.420154,-0.763050,-0.033147,0.011353,0.048556,-0.002049,0.043314,0.008386,-0.006653
lnp3_2,-0.266944,0.000381,0.000013,0.000019,-0.000033,-0.000170,0.070493,0.023665,-0.058647,-0.003079,-0.002049,0.008285,-0.002485,-0.001552,0.004467
lnp1lnp2,10.902440,0.017546,-0.000014,-0.001141,-0.001537,-0.000144,-1.788158,-1.555553,0.199482,0.070381,0.043314,-0.002485,0.138302,-0.015413,-0.010534
lnp1lnp3,0.990254,-0.015046,-0.000099,0.001850,0.000102,-0.000170,0.038416,0.036229,-0.685050,-0.013413,0.008386,-0.001552,-0.015413,0.072939,0.009949
lnp2lnp3,0.197435,-0.003570,-0.000048,-0.000085,0.002212,-0.001375,0.132157,-0.072591,-0.367388,-0.006656,-0.006653,0.004467,-0.010534,0.009949,0.060678

In [101]:
regression.restricted_OLS(L_input, r_input)[0]

              Coef.

intercept -7.111200
lnq        0.461368
lnq_2      0.029978
lnqlnp1   -0.004354
lnqlnp2   -0.032424
lnqlnp3    0.036778
lnp1       0.215566
lnp2       0.381511
lnp3       0.402923
lnp1_2    -0.004356
lnp2_2    -0.007651
lnp3_2     0.002578
lnp1lnp2   0.007292
lnp1lnp3  -0.002936
lnp2lnp3   0.000358

In [102]:
regression.restricted_OLS(L_input, r_input)[1]

,intercept,lnq,lnq_2,lnqlnp1,lnqlnp2,lnqlnp3,lnp1,lnp2,lnp3,lnp1_2,lnp2_2,lnp3_2,lnp1lnp2,lnp1lnp3,lnp2lnp3
,,,,,,,,,,,,,,,
intercept,8.543622,-0.096814,0.000104,0.015783,0.006471,-0.022254,-3.071253,1.446733,1.624521,0.199608,-0.413869,-0.046280,0.083990,-0.283598,0.329878
lnq,-0.096814,0.016124,-0.000035,-0.002932,0.000647,0.002285,0.012275,0.002563,-0.014839,0.000802,-0.000663,-0.001469,-0.000804,0.000002,0.001467
lnq_2,0.000104,-0.000035,0.000005,-0.000008,0.000009,-0.000001,-0.000019,-0.000057,0.000076,0.000006,-0.000024,0.000015,0.000017,-0.000023,0.000008
lnqlnp1,0.015783,-0.002932,-0.000008,0.000589,-0.000223,-0.000366,-0.001387,-0.000327,0.001713,-0.000241,0.000289,0.000283,0.000118,0.000124,-0.000407
lnqlnp2,0.006471,0.000647,0.000009,-0.000223,0.000516,-0.000293,-0.003747,-0.000702,0.004449,0.000409,-0.000521,-0.000312,-0.000100,-0.000309,0.000621
lnqlnp3,-0.022254,0.002285,-0.000001,-0.000366,-0.000293,0.000659,0.005133,0.001029,-0.006162,-0.000168,0.000232,0.000029,-0.000018,0.000185,-0.000214
lnp1,-3.071253,0.012275,-0.000019,-0.001387,-0.003747,0.005133,1.159402,-0.565752,-0.593649,-0.078763,0.155893,0.022953,-0.027089,0.105851,-0.128804
lnp2,1.446733,0.002563,-0.000057,-0.000327,-0.000702,0.001029,-0.565752,0.317565,0.248188,0.039477,-0.069699,-0.021671,0.004276,-0.043752,0.065423
lnp3,1.624521,-0.014839,0.000076,0.001713,0.004449,-0.006162,-0.593649,0.248188,0.345461,0.039286,-0.086194,-0.001282,0.022813,-0.062099,0.063381
lnp1_2,0.199608,0.000802,0.000006,-0.000241,0.000409,-0.000168,-0.078763,0.039477,0.039286,0.005588,-0.010559,-0.002078,0.001447,-0.007035,0.009112
lnp2_2,-0.413869,-0.000663,-0.000024,0.000289,-0.000521,0.000232,0.155893,-0.069699,-0.086194,-0.010559,0.025364,-0.001598,-0.008202,0.018761,-0.017163
lnp3_2,-0.046280,-0.001469,0.000015,0.000283,-0.000312,0.000029,0.022953,-0.021671,-0.001282,-0.002078,-0.001598,0.007230,0.005453,-0.003375,-0.003854
lnp1lnp2,0.083990,-0.000804,0.000017,0.000118,-0.000100,-0.000018,-0.027089,0.004276,0.022813,0.001447,-0.008202,0.005453,0.006104,-0.007551,0.002098
lnp1lnp3,-0.283598,0.000002,-0.000023,0.000124,-0.000309,0.000185,0.105851,-0.043752,-0.062099,-0.007035,0.018761,-0.003375,-0.007551,0.014585,-0.011210
lnp2lnp3,0.329878,0.001467,0.000008,-0.000407,0.000621,-0.000214,-0.128804,0.065423,0.063381,0.009112,-0.017163,-0.003854,0.002098,-0.011210,0.015065

In [18]:
beta_OLS_output_r

               Coef.
Intercept -76.259261
lnq        -1.080425
lnq_2       0.026489
lnqlnp1     0.131041
lnqlnp2     0.040144
lnqlnp3     0.058652
lnp1       14.718293
lnp2        6.380797
lnp3       -0.894733
lnp1_2     -0.769264
lnp2_2     -0.163707
lnp3_2     -0.036753
lnp1lnp2   -0.572050
lnp1lnp3    0.162283
lnp2lnp3   -0.024025

In [19]:
var_OLS_output

,Intercept,lnq,lnq_2,lnqlnp1,lnqlnp2,lnqlnp3,lnp1,lnp2,lnp3,lnp1_2,lnp2_2,lnp3_2,lnp1lnp2,lnp1lnp3,lnp2lnp3
Intercept,1465.361176,0.192537,-0.011698,-0.026677,0.039538,0.015949,-262.932577,-128.192050,-8.392679,11.880857,3.540639,-0.266944,10.902441,0.990253,0.197435
lnq,0.192537,0.141034,0.000308,-0.013459,-0.006089,0.000161,-0.186223,-0.090714,0.148320,0.015321,-0.000898,0.000381,0.017546,-0.015046,-0.003570
lnq_2,-0.011698,0.000308,0.000006,-0.000036,-0.000011,-0.000005,0.001491,0.000862,0.001052,-0.000043,-0.000060,0.000013,-0.000014,-0.000099,-0.000048
lnqlnp1,-0.026677,-0.013459,-0.000036,0.001466,0.000348,-0.000168,0.021561,0.005430,-0.015127,-0.001961,0.000285,0.000019,-0.001141,0.001850,-0.000085
lnqlnp2,0.039538,-0.006089,-0.000011,0.000348,0.000888,-0.000189,-0.000337,0.000268,-0.008853,0.000211,-0.000067,-0.000033,-0.001537,0.000102,0.002212
lnqlnp3,0.015949,0.000161,-0.000005,-0.000168,-0.000189,0.000653,-0.008293,0.008035,0.003306,0.000587,-0.000103,-0.000170,-0.000144,-0.000170,-0.001375
lnp1,-262.932577,-0.186223,0.001491,0.021561,-0.000337,-0.008293,50.194723,19.099543,-1.253531,-2.388986,-0.420154,0.070493,-1.788158,0.038416,0.132157
lnp2,-128.192050,-0.090714,0.000862,0.005430,0.000268,0.008035,19.099543,20.513715,-0.214871,-0.705214,-0.763050,0.023665,-1.555553,0.036229,-0.072591
lnp3,-8.392679,0.148320,0.001052,-0.015127,-0.008853,0.003306,-1.253531,-0.214871,8.078742,0.161643,-0.033147,-0.058647,0.199482,-0.685050,-0.367388
lnp1_2,11.880857,0.015321,-0.000043,-0.001961,0.000211,0.000587,-2.388986,-0.705214,0.161643,0.119855,0.011353,-0.003079,0.070381,-0.013413,-0.006656
lnp2_2,3.540639,-0.000898,-0.000060,0.000285,-0.000067,-0.000103,-0.420154,-0.763050,-0.033147,0.011353,0.048556,-0.002049,0.043314,0.008386,-0.006653
lnp3_2,-0.266944,0.000381,0.000013,0.000019,-0.000033,-0.000170,0.070493,0.023665,-0.058647,-0.003079,-0.002049,0.008285,-0.002485,-0.001552,0.004467
lnp1lnp2,10.902441,0.017546,-0.000014,-0.001141,-0.001537,-0.000144,-1.788158,-1.555553,0.199482,0.070381,0.043314,-0.002485,0.138302,-0.015413,-0.010534
lnp1lnp3,0.990253,-0.015046,-0.000099,0.001850,0.000102,-0.000170,0.038416,0.036229,-0.685050,-0.013413,0.008386,-0.001552,-0.015413,0.072939,0.009949
lnp2lnp3,0.197435,-0.003570,-0.000048,-0.000085,0.002212,-0.001375,0.132157,-0.072591,-0.367388,-0.006656,-0.006653,0.004467,-0.010534,0.009949,0.060678